// Code generated by sgoiter emit go1.26; DO NOT EDIT.
package monocypher

import (
	"encoding/binary"
	"math/bits"
)

type Crypto_aead_ctx struct {
	Counter uint64
	Key [32]uint8
	Nonce [8]uint8
}

type Crypto_blake2b_ctx struct {
	Hash [8]uint64
	Input_offset [2]uint64
	Input [16]uint64
	Input_idx uint64
	Hash_size uint64
}

type Crypto_argon2_config struct {
	Algorithm uint32
	Nb_blocks uint32
	Nb_passes uint32
	Nb_lanes uint32
}

type Crypto_argon2_inputs struct {
	Pass []uint8
	Salt []uint8
	Pass_size uint32
	Salt_size uint32
}

type Crypto_argon2_extras struct {
	Key []uint8
	Ad []uint8
	Key_size uint32
	Ad_size uint32
}

type Crypto_poly1305_ctx struct {
	C [16]uint8
	C_idx uint64
	R [4]uint32
	Pad [4]uint32
	H [5]uint32
}

type Blk struct {
	A [128]uint64
}

type S25 struct {
	X int64
}

type S26 struct {
	X int64
}

type Ge struct {
	X [10]int
	Y [10]int
	Z [10]int
	T [10]int
}

type Ge_cached struct {
	Yp [10]int
	Ym [10]int
	Z [10]int
	T2 [10]int
}

type Ge_precomp struct {
	Yp [10]int
	Ym [10]int
	T2 [10]int
}



var chacha20_constant = []byte("expand 32-byte k")
var zero_arr [128]byte
var zero = zero_arr[:]
var key_block = make([]byte, 128)
var sigma = [192]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}
var iv = [8]uint64{0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1, 0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179}
var base_point = [32]byte{9}
var L = []uint32{0x5cf5d3ed, 0x5812631a, 0xa2f79cd6, 0x14def9de, 0x00000000, 0x00000000, 0x00000000, 0x10000000}
var r = [9]uint32{0x0a2c131b, 0xed9ce5a3, 0x086329a7, 0x2106215d, 0xffffffeb, 0xffffffff, 0xffffffff, 0xffffffff, 0xf}
var xr = [1]uint32{0}
var zero_point = [1]byte{1}
var half_mod_L = [32]byte{247, 233, 122, 46, 141, 49, 9, 44, 107, 206, 123, 81, 239, 124, 111, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8}
var half_ones = [32]byte{142, 74, 204, 70, 186, 24, 118, 107, 184, 231, 190, 57, 250, 173, 119, 99, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 7}
var dirty_base_point = [32]byte{0xd8, 0x86, 0x1a, 0xa2, 0x78, 0x7a, 0xd9, 0x26, 0x8b, 0x74, 0x74, 0xb6, 0x82, 0xe3, 0xbe, 0xc3, 0xce, 0x36, 0x9a, 0x1e, 0x5e, 0x31, 0x47, 0xa2, 0x6d, 0x37, 0x7c, 0xfd, 0x20, 0xb5, 0xdf, 0x75}
var k = [8]uint32{0x12547e1b, 0xd2b51da3, 0xfdba84ff, 0xb1a206f2, 0xffa36bea, 0x14e75438, 0x6fe91836, 0x9db6c6f2}
var s = [1]uint32{0}
var t = [1]uint32{0}
var Lm2 = [32]byte{0xeb, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10}
var m_inv = [8]uint32{0x8d98951d, 0xd6ec3174, 0x737dcf70, 0xc6ef5bf4, 0xfffffffe, 0xffffffff, 0xffffffff, 0x0fffffff}
var fe_one = []int{1, 0, 0, 0, 0, 0, 0, 0, 0, 0}
var sqrtm1 = []int{-32595792, -7943725, 9377950, 3500415, 12389472, -272473, -25146209, -2005654, 326686, 11406482}
var d = []int{-10913610, 13857413, -15372611, 6949391, 114729, -8787816, -6275908, -3247719, -18696448, -12055116}
var D2 = []int{-21827239, -5839606, -30745221, 13898782, 229458, 15978800, -12551817, -6495438, 29715968, 9444199}
var lop_x = []int{21352778, 5345713, 4660180, -8347857, 24143090, 14568123, 30185756, -12247770, -33528939, 8345319}
var lop_y = []int{-6952922, -1265500, 6862341, -7057498, -4037696, -5447722, 31680899, -15325402, -19365852, 1569102}
var ufactor = []int{-1917299, 15887451, -18755900, -7000830, -24778944, 544946, -16816446, 4011309, -653372, 10741468}
var A2 = []int{12721188, 3529, 0, 0, 0, 0, 0, 0, 0, 0}
var A = []int{486662, 0, 0, 0, 0, 0, 0, 0, 0, 0}
var blake2b_compress_sigma = [192]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}
var crypto_blake2b_keyed_init_key_block = make([]byte, 128)
var crypto_x25519_public_key_base_point = func() []byte { var b [32]byte; b[0]=9; return b[:] }()
var crypto_x25519_dirty_small_dirty_base_point = []byte{0xd8, 0x86, 0x1a, 0xa2, 0x78, 0x7a, 0xd9, 0x26, 0x8b, 0x74, 0x74, 0xb6, 0x82, 0xe3, 0xbe, 0xc3, 0xce, 0x36, 0x9a, 0x1e, 0x5e, 0x31, 0x47, 0xa2, 0x6d, 0x37, 0x7c, 0xfd, 0x20, 0xb5, 0xdf, 0x75}
var crypto_x25519_inverse_Lm2 = []byte{0xeb, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10}

func Gap(x uint64, pow_2 uint64) uint64 {
	return uint64((^x + 1) & (pow_2 - 1))
}

func Load24_le(s []byte) uint32 {
	return uint32((uint32(s[0]) | (uint32(s[1]) << 8)) | (uint32(s[2]) << 16))
}

func Load32_le(s []byte) uint32 {
	return binary.LittleEndian.Uint32(s)
}

func Load64_le(s []byte) uint64 {
	return binary.LittleEndian.Uint64(s)
}

func Store32_le(out []byte, in uint32) {
	binary.LittleEndian.PutUint32(out, in)
}

func Store64_le(out []byte, in uint64) {
	binary.LittleEndian.PutUint64(out, in)
}

func Load32_le_buf(dst []uint32, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[v3] = Load32_le(src[int(v3 * 4):])
		v3++
	}
}

func Load64_le_buf(dst []uint64, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[v3] = Load64_le(src[int(v3 * 8):])
		v3++
	}
}

func Store32_le_buf(dst []byte, src []uint32, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store32_le(dst[int(v3 * 4):], src[v3])
		v3++
	}
}

func Store64_le_buf(dst []byte, src []uint64, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store64_le(dst[int(v3 * 8):], src[v3])
		v3++
	}
}

func Rotl32(x uint32, n uint32) uint32 {
	return uint32(bits.RotateLeft32(x, int(n)))
}

func Neq0(diff uint64) int {
	return int((uint64(1) & ((((diff >> 32) | uint64(uint32(diff))) - uint64(1)) >> 32)) - uint64(1))
}

func X16(a []byte, b []byte) uint64 {
	return uint64((Load64_le(a) ^ Load64_le(b)) | (Load64_le(a[8:]) ^ Load64_le(b[8:])))
}

func X32(a []byte, b []byte) uint64 {
	return uint64(X16(a, b) | X16(a[16:], b[16:]))
}

func X64(a []byte, b []byte) uint64 {
	return uint64(X32(a, b) | X32(a[32:], b[32:]))
}

func Crypto_verify16(a []byte, b []byte) int {
	return Neq0(X16(a, b))
}

func Crypto_verify32(a []byte, b []byte) int {
	return Neq0(X32(a, b))
}

func Crypto_verify64(a []byte, b []byte) int {
	return Neq0(X64(a, b))
}

func Crypto_wipe(secret []byte, size uint64) {
	clear(secret[:size])
}

func Chacha20_rounds(out []uint32, in []uint32) {
	var v2 uint32
	var v5 uint32
	var v8 uint32
	var v11 uint32
	var v14 uint32
	var v17 uint32
	var v20 uint32
	var v23 uint32
	var v26 uint32
	var v29 uint32
	var v32 uint32
	var v35 uint32
	var v38 uint32
	var v41 uint32
	var v44 uint32
	var v47 uint32
	var v50 uint64
	v2 = in[0]
	v5 = in[1]
	v8 = in[2]
	v11 = in[3]
	v14 = in[4]
	v17 = in[5]
	v20 = in[6]
	v23 = in[7]
	v26 = in[8]
	v29 = in[9]
	v32 = in[10]
	v35 = in[11]
	v38 = in[12]
	v41 = in[13]
	v44 = in[14]
	v47 = in[15]
	v50 = 0
	for v50 < 10 {
		v2 += v14
		v38 = bits.RotateLeft32((v38 ^ v2), 16)
		v26 += v38
		v14 = bits.RotateLeft32((v14 ^ v26), 12)
		v2 += v14
		v38 = bits.RotateLeft32((v38 ^ v2), 8)
		v26 += v38
		v14 = bits.RotateLeft32((v14 ^ v26), 7)
		v5 += v17
		v41 = bits.RotateLeft32((v41 ^ v5), 16)
		v29 += v41
		v17 = bits.RotateLeft32((v17 ^ v29), 12)
		v5 += v17
		v41 = bits.RotateLeft32((v41 ^ v5), 8)
		v29 += v41
		v17 = bits.RotateLeft32((v17 ^ v29), 7)
		v8 += v20
		v44 = bits.RotateLeft32((v44 ^ v8), 16)
		v32 += v44
		v20 = bits.RotateLeft32((v20 ^ v32), 12)
		v8 += v20
		v44 = bits.RotateLeft32((v44 ^ v8), 8)
		v32 += v44
		v20 = bits.RotateLeft32((v20 ^ v32), 7)
		v11 += v23
		v47 = bits.RotateLeft32((v47 ^ v11), 16)
		v35 += v47
		v23 = bits.RotateLeft32((v23 ^ v35), 12)
		v11 += v23
		v47 = bits.RotateLeft32((v47 ^ v11), 8)
		v35 += v47
		v23 = bits.RotateLeft32((v23 ^ v35), 7)
		v2 += v17
		v47 = bits.RotateLeft32((v47 ^ v2), 16)
		v32 += v47
		v17 = bits.RotateLeft32((v17 ^ v32), 12)
		v2 += v17
		v47 = bits.RotateLeft32((v47 ^ v2), 8)
		v32 += v47
		v17 = bits.RotateLeft32((v17 ^ v32), 7)
		v5 += v20
		v38 = bits.RotateLeft32((v38 ^ v5), 16)
		v35 += v38
		v20 = bits.RotateLeft32((v20 ^ v35), 12)
		v5 += v20
		v38 = bits.RotateLeft32((v38 ^ v5), 8)
		v35 += v38
		v20 = bits.RotateLeft32((v20 ^ v35), 7)
		v8 += v23
		v41 = bits.RotateLeft32((v41 ^ v8), 16)
		v26 += v41
		v23 = bits.RotateLeft32((v23 ^ v26), 12)
		v8 += v23
		v41 = bits.RotateLeft32((v41 ^ v8), 8)
		v26 += v41
		v23 = bits.RotateLeft32((v23 ^ v26), 7)
		v11 += v14
		v44 = bits.RotateLeft32((v44 ^ v11), 16)
		v29 += v44
		v14 = bits.RotateLeft32((v14 ^ v29), 12)
		v11 += v14
		v44 = bits.RotateLeft32((v44 ^ v11), 8)
		v29 += v44
		v14 = bits.RotateLeft32((v14 ^ v29), 7)
		v50++
	}
	out[0] = v2
	out[1] = v5
	out[2] = v8
	out[3] = v11
	out[4] = v14
	out[5] = v17
	out[6] = v20
	out[7] = v23
	out[8] = v26
	out[9] = v29
	out[10] = v32
	out[11] = v35
	out[12] = v38
	out[13] = v41
	out[14] = v44
	out[15] = v47
}

func Crypto_chacha20_h(out []byte, key []byte, in []byte) {
	var _arr_v4 [16]uint32
	v4 := _arr_v4[:]
	Load32_le_buf(v4, chacha20_constant, uint64(4))
	Load32_le_buf(v4[4:], key, uint64(8))
	v14 := v4[12:]
	Load32_le_buf(v14, in, uint64(4))
	Chacha20_rounds(v4, v4)
	Store32_le_buf(out, v4, uint64(4))
	Store32_le_buf(out[16:], v14, uint64(4))
	clear(v4)
}


func Crypto_chacha20_ietf(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint32) uint32 {
	return uint32(Crypto_chacha20_djb(cipher_text, plain_text, text_size, key, nonce[4:], (uint64(ctr) + (uint64(Load32_le(nonce)) << 32))))
}

func Crypto_chacha20_x(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint64) uint64 {
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	Crypto_chacha20_h(v6, key, nonce)
	ctr = Crypto_chacha20_djb(cipher_text, plain_text, text_size, v6, nonce[16:], ctr)
	clear(v6)
	return ctr
}


func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	var v3 uint64
	var v20 uint64
	var v30 uint64
	v3 = 0
	for v3 < 5 {
		ctx.H[v3] = uint32(0)
		v3++
	}
	ctx.C_idx = uint64(0)
	Load32_le_buf(ctx.R[:], key, uint64(4))
	Load32_le_buf(ctx.Pad[:], key[16:], uint64(4))
	v20 = 0
	for v20 < 1 {
		ctx.R[v20] &= uint32(0xfffffff)
		v20++
	}
	v30 = 1
	for v30 < 4 {
		ctx.R[v30] &= uint32(0xffffffc)
		v30++
	}
}

func Crypto_poly1305_update(ctx *Crypto_poly1305_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v15 uint64
	var v47 uint64
	v3 = 0
	if message_size == 0 {
		return
	}
	v14 := func() uint64 { if (func() int { if Gap(ctx.C_idx, uint64(16)) <= message_size { return 1 }; return 0 }()) != 0 { return Gap(ctx.C_idx, uint64(16)) }; return message_size }()
	v15 = 0
	for v15 < v14 {
		ctx.C[int(ctx.C_idx)] = message[v3]
		v24 := ctx.C_idx + uint64(1)
		ctx.C_idx = v24
		v3++
		message_size--
		v15++
	}
	if ctx.C_idx == 16 {
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(1))
		ctx.C_idx = uint64(0)
	}
	v38 := message_size >> 4
	Poly_blocks(ctx, message[v3:], v38, uint32(1))
	v3 += (v38 << 4)
	message_size &= 15
	v47 = 0
	for v47 < message_size {
		ctx.C[int(ctx.C_idx)] = message[int(v3 + v47)]
		v57 := ctx.C_idx + uint64(1)
		ctx.C_idx = v57
		v47++
	}
}

func Crypto_poly1305_final(ctx *Crypto_poly1305_ctx, mac []byte) {
	var v4 uint64
	var v23 uint64
	var v25 uint64
	var v43 uint64
	if ctx.C_idx != 0 {
		v4 = 0
		for v4 < (uint64(16) - ctx.C_idx) {
			ctx.C[int(ctx.C_idx + v4)] = uint8(0)
			v4++
		}
		ctx.C[int(ctx.C_idx)] = uint8(1)
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(0))
	}
	v23 = 5
	v25 = 0
	for v25 < 4 {
		v23 += uint64(ctx.H[v25])
		v23 >>= 32
		v25++
	}
	v23 += uint64(ctx.H[4])
	v23 = (v23 >> 2) * 5
	v43 = 0
	for v43 < 4 {
		v23 += (uint64(ctx.H[v43]) + uint64(ctx.Pad[v43]))
		Store32_le(mac[int(v43 * 4):], uint32(v23))
		v23 >>= 32
		v43++
	}
}

func Crypto_poly1305(mac []byte, message []byte, message_size uint64, key []byte) {
	var v4 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v4, key)
	Crypto_poly1305_update(&v4, message, message_size)
	Crypto_poly1305_final(&v4, mac)
}

func Blake2b_compress(ctx *Crypto_blake2b_ctx, is_last_block int) {
	var v16 uint64
	var v20 uint64
	var v24 uint64
	var v27 uint64
	var v31 uint64
	var v34 uint64
	var v38 uint64
	var v41 uint64
	var v45 uint64
	var v48 uint64
	var v52 uint64
	var v59 uint64
	var v63 uint64
	var v70 uint64
	var v74 uint64
	var v82 uint64
	var v86 uint64
	var v91 uint64
	v7 := ctx.Input_idx
	ctx.Input_offset[0] += v7
	if ctx.Input_offset[0] < v7 {
		v16 = ctx.Input_offset[1]
		v18 := v16 + 1
		v16 = v18
		ctx.Input_offset[1] = v18
	}
	v20 = ctx.Hash[0]
	v24 = 0x6a09e667f3bcc908
	v27 = ctx.Hash[1]
	v31 = 0xbb67ae8584caa73b
	v34 = ctx.Hash[2]
	v38 = 0x3c6ef372fe94f82b
	v41 = ctx.Hash[3]
	v45 = 0xa54ff53a5f1d36f1
	v48 = ctx.Hash[4]
	v52 = 0x510e527fade682d1 ^ ctx.Input_offset[0]
	v59 = ctx.Hash[5]
	v63 = 0x9b05688c2b3e6c1f ^ ctx.Input_offset[1]
	v70 = ctx.Hash[6]
	v74 = 0x1f83d9abfb41bd6b ^ uint64(^(is_last_block - 1))
	v82 = ctx.Hash[7]
	v86 = 0x5be0cd19137e2179
	v91 = 0
	for v91 < 12 {
		v99 := v91 * 16
		v20 += (v48 + ctx.Input[int(blake2b_compress_sigma[v99])])
		v52 = bits.RotateLeft64((v52 ^ v20), 64-32)
		v24 += v52
		v48 = bits.RotateLeft64((v48 ^ v24), 64-24)
		v20 += (v48 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 1)])])
		v52 = bits.RotateLeft64((v52 ^ v20), 64-16)
		v24 += v52
		v48 = bits.RotateLeft64((v48 ^ v24), 64-63)
		v27 += (v59 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 2)])])
		v63 = bits.RotateLeft64((v63 ^ v27), 64-32)
		v31 += v63
		v59 = bits.RotateLeft64((v59 ^ v31), 64-24)
		v27 += (v59 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 3)])])
		v63 = bits.RotateLeft64((v63 ^ v27), 64-16)
		v31 += v63
		v59 = bits.RotateLeft64((v59 ^ v31), 64-63)
		v34 += (v70 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 4)])])
		v74 = bits.RotateLeft64((v74 ^ v34), 64-32)
		v38 += v74
		v70 = bits.RotateLeft64((v70 ^ v38), 64-24)
		v34 += (v70 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 5)])])
		v74 = bits.RotateLeft64((v74 ^ v34), 64-16)
		v38 += v74
		v70 = bits.RotateLeft64((v70 ^ v38), 64-63)
		v41 += (v82 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 6)])])
		v86 = bits.RotateLeft64((v86 ^ v41), 64-32)
		v45 += v86
		v82 = bits.RotateLeft64((v82 ^ v45), 64-24)
		v41 += (v82 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 7)])])
		v86 = bits.RotateLeft64((v86 ^ v41), 64-16)
		v45 += v86
		v82 = bits.RotateLeft64((v82 ^ v45), 64-63)
		v20 += (v59 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 8)])])
		v86 = bits.RotateLeft64((v86 ^ v20), 64-32)
		v38 += v86
		v59 = bits.RotateLeft64((v59 ^ v38), 64-24)
		v20 += (v59 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 9)])])
		v86 = bits.RotateLeft64((v86 ^ v20), 64-16)
		v38 += v86
		v59 = bits.RotateLeft64((v59 ^ v38), 64-63)
		v27 += (v70 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 10)])])
		v52 = bits.RotateLeft64((v52 ^ v27), 64-32)
		v45 += v52
		v70 = bits.RotateLeft64((v70 ^ v45), 64-24)
		v27 += (v70 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 11)])])
		v52 = bits.RotateLeft64((v52 ^ v27), 64-16)
		v45 += v52
		v70 = bits.RotateLeft64((v70 ^ v45), 64-63)
		v34 += (v82 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 12)])])
		v63 = bits.RotateLeft64((v63 ^ v34), 64-32)
		v24 += v63
		v82 = bits.RotateLeft64((v82 ^ v24), 64-24)
		v34 += (v82 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 13)])])
		v63 = bits.RotateLeft64((v63 ^ v34), 64-16)
		v24 += v63
		v82 = bits.RotateLeft64((v82 ^ v24), 64-63)
		v41 += (v48 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 14)])])
		v74 = bits.RotateLeft64((v74 ^ v41), 64-32)
		v31 += v74
		v48 = bits.RotateLeft64((v48 ^ v31), 64-24)
		v41 += (v48 + ctx.Input[int(blake2b_compress_sigma[int(v99 + 15)])])
		v74 = bits.RotateLeft64((v74 ^ v41), 64-16)
		v31 += v74
		v48 = bits.RotateLeft64((v48 ^ v31), 64-63)
		v91++
	}
	ctx.Hash[0] ^= (v20 ^ v24)
	ctx.Hash[1] ^= (v27 ^ v31)
	ctx.Hash[2] ^= (v34 ^ v38)
	ctx.Hash[3] ^= (v41 ^ v45)
	ctx.Hash[4] ^= (v48 ^ v52)
	ctx.Hash[5] ^= (v59 ^ v63)
	ctx.Hash[6] ^= (v70 ^ v74)
	ctx.Hash[7] ^= (v82 ^ v86)
}

func Crypto_blake2b_keyed_init(ctx *Crypto_blake2b_ctx, hash_size uint64, key []byte, key_size uint64) {
	var v6 uint64
	var v31 uint64
	var v40 uint64
	v6 = 0
	for v6 < 8 {
		ctx.Hash[v6] = iv[v6]
		v6++
	}
	ctx.Hash[0] ^= ((uint64(0x1010000) ^ (key_size << 8)) ^ hash_size)
	ctx.Input_offset[0] = uint64(0)
	ctx.Input_offset[1] = uint64(0)
	ctx.Hash_size = hash_size
	ctx.Input_idx = uint64(0)
	v31 = 0
	for v31 < 16 {
		ctx.Input[v31] = uint64(0)
		v31++
	}
	if key_size > 0 {
		v40 = 0
		for v40 < key_size {
			crypto_blake2b_keyed_init_key_block[v40] = key[v40]
			v40++
		}
		Load64_le_buf(ctx.Input[:], crypto_blake2b_keyed_init_key_block, uint64(16))
		ctx.Input_idx = uint64(0x80)
	}
}

func Crypto_blake2b_init(ctx *Crypto_blake2b_ctx, hash_size uint64) {
	Crypto_blake2b_keyed_init(ctx, hash_size, nil, uint64(0))
}

func Crypto_blake2b_update(ctx *Crypto_blake2b_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v27 uint64
	var v82 uint64
	var v107 uint64
	var v130 uint64
	v3 = 0
	if message_size == 0 {
		return
	}
	if (ctx.Input_idx & uint64(7)) != 0 {
		v18 := func() uint64 { if (func() int { if Gap(ctx.Input_idx, uint64(8)) <= message_size { return 1 }; return 0 }()) != 0 { return Gap(ctx.Input_idx, uint64(8)) }; return message_size }()
		v27 = 0
		for v27 < v18 {
			ctx.Input[int(ctx.Input_idx >> 3)] = ctx.Input[int(ctx.Input_idx >> 3)] | (uint64(message[int(v3 + v27)]) << uint8(((ctx.Input_idx & uint64(7)) + v27) << 3))
			v27++
		}
		ctx.Input_idx += v18
		v3 += v18
		message_size -= v18
	}
	if (ctx.Input_idx & uint64(0x7f)) != 0 {
		v60 := (func() uint64 { if (func() int { if Gap(ctx.Input_idx, uint64(0x80)) <= message_size { return 1 }; return 0 }()) != 0 { return Gap(ctx.Input_idx, uint64(0x80)) }; return message_size }()) >> 3
		Load64_le_buf(ctx.Input[int(ctx.Input_idx >> 3):], message[v3:], v60)
		v70 := v60 << 3
		ctx.Input_idx += v70
		v3 += v70
		message_size -= v70
	}
	v81 := message_size >> 7
	v82 = 0
	for v82 < v81 {
		if ctx.Input_idx == uint64(0x80) {
			Blake2b_compress(ctx, 0)
		}
		Load64_le_buf(ctx.Input[:], message[v3:], uint64(16))
		v3 += 0x80
		ctx.Input_idx = uint64(0x80)
		v82++
	}
	message_size &= 0x7f
	if message_size != 0 {
		if ctx.Input_idx == uint64(0x80) {
			Blake2b_compress(ctx, 0)
			ctx.Input_idx = uint64(0)
		}
		if ctx.Input_idx == 0 {
			v107 = 0
			for v107 < 16 {
				ctx.Input[v107] = uint64(0)
				v107++
			}
		}
		v116 := message_size >> 3
		Load64_le_buf(ctx.Input[:], message[v3:], v116)
		v121 := v116 << 3
		ctx.Input_idx += v121
		v3 += v121
		message_size -= v121
		v130 = 0
		for v130 < message_size {
			ctx.Input[int(ctx.Input_idx >> 3)] = ctx.Input[int(ctx.Input_idx >> 3)] | (uint64(message[int(v3 + v130)]) << uint8((ctx.Input_idx & uint64(7)) << 3))
			v154 := ctx.Input_idx + uint64(1)
			ctx.Input_idx = v154
			v130++
		}
	}
}

func Crypto_blake2b_final(ctx *Crypto_blake2b_ctx, hash []byte) {
	var v16 uint64
	Blake2b_compress(ctx, 1)
	v10 := func() uint64 { if (func() int { if ctx.Hash_size <= uint64(64) { return 1 }; return 0 }()) != 0 { return ctx.Hash_size }; return uint64(64) }()
	v13 := v10 >> 3
	Store64_le_buf(hash, ctx.Hash[:], v13)
	v16 = v13 << 3
	for v16 < v10 {
		hash[v16] = uint8((ctx.Hash[int(v16 >> 3)] >> uint8(8 * int(v16 & 7))) & uint64(0xff))
		v16++
	}
}

func Crypto_blake2b_keyed(hash []byte, hash_size uint64, key []byte, key_size uint64, message []byte, message_size uint64) {
	var v6 Crypto_blake2b_ctx
	Crypto_blake2b_keyed_init(&v6, hash_size, key, key_size)
	Crypto_blake2b_update(&v6, message, message_size)
	Crypto_blake2b_final(&v6, hash)
}

func Crypto_blake2b(hash []byte, hash_size uint64, msg []byte, msg_size uint64) {
	Crypto_blake2b_keyed(hash, hash_size, nil, uint64(0), msg, msg_size)
}

func Blake_update_32(ctx *Crypto_blake2b_ctx, input uint32) {
	var _arr_v2 [4]uint8
	v2 := _arr_v2[:]
	Store32_le(v2, input)
	Crypto_blake2b_update(ctx, v2, uint64(4))
	clear(v2)
}

func Blake_update_32_buf(ctx *Crypto_blake2b_ctx, buf []byte, size uint32) {
	Blake_update_32(ctx, size)
	Crypto_blake2b_update(ctx, buf, uint64(size))
}

func Copy_block(o *Blk, in *Blk) {
	o.A = in.A
}

func Xor_block(o *Blk, in *Blk) {
	var v2 uint64
	v2 = 0
	for v2 < 0x80 {
		o.A[v2] ^= in.A[v2]
		v2++
	}
}

func Extended_hash(digest []byte, digest_size uint32, input []byte, input_size uint32) {
	var v28 uint32
	var v30 uint32
	var v32 uint32
	var v5 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v5, uint64(func() uint32 { if (func() int { if digest_size <= 64 { return 1 }; return 0 }()) != 0 { return digest_size }; return uint32(64) }()))
	Blake_update_32(&v5, digest_size)
	Crypto_blake2b_update(&v5, input, uint64(input_size))
	Crypto_blake2b_final(&v5, digest)
	if digest_size > 64 {
		v27 := uint32((uint64(digest_size) + uint64(31)) >> 5) - uint32(2)
		v28 = 1
		v30 = 0
		v32 = 32
		for v28 < v27 {
			Crypto_blake2b(digest[v32:], uint64(64), digest[v30:], uint64(64))
			v28++
			v30 += 32
			v32 += 32
		}
		Crypto_blake2b(digest[v32:], uint64(digest_size - (uint32(32) * v27)), digest[v30:], uint64(64))
	}
}

func G_rounds(b *Blk) {
	var v1 int
	var v1542 int
	v1 = 0
	for v1 < 128 {
		v8 := v1 + 4
		b.A[v1] += (b.A[v8] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8]))) << 1))
		v32 := v1 + 12
		b.A[v32] ^= b.A[v1]
		b.A[v32] = bits.RotateLeft64(b.A[v32], 64-32)
		v53 := v1 + 8
		b.A[v53] += (b.A[v32] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = bits.RotateLeft64(b.A[v8], 64-24)
		b.A[v1] += (b.A[v8] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v32] ^= b.A[v1]
		b.A[v32] = bits.RotateLeft64(b.A[v32], 64-16)
		b.A[v53] += (b.A[v32] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = bits.RotateLeft64(b.A[v8], 64-63)
		v188 := v1 + 5
		v192 := v1 + 1
		b.A[v192] += (b.A[v188] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188]))) << 1))
		v220 := v1 + 13
		b.A[v220] ^= b.A[v192]
		b.A[v220] = bits.RotateLeft64(b.A[v220], 64-32)
		v241 := v1 + 9
		b.A[v241] += (b.A[v220] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = bits.RotateLeft64(b.A[v188], 64-24)
		b.A[v192] += (b.A[v188] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v220] ^= b.A[v192]
		b.A[v220] = bits.RotateLeft64(b.A[v220], 64-16)
		b.A[v241] += (b.A[v220] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = bits.RotateLeft64(b.A[v188], 64-63)
		v384 := v1 + 6
		v388 := v1 + 2
		b.A[v388] += (b.A[v384] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384]))) << 1))
		v416 := v1 + 14
		b.A[v416] ^= b.A[v388]
		b.A[v416] = bits.RotateLeft64(b.A[v416], 64-32)
		v437 := v1 + 10
		b.A[v437] += (b.A[v416] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = bits.RotateLeft64(b.A[v384], 64-24)
		b.A[v388] += (b.A[v384] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v416] ^= b.A[v388]
		b.A[v416] = bits.RotateLeft64(b.A[v416], 64-16)
		b.A[v437] += (b.A[v416] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = bits.RotateLeft64(b.A[v384], 64-63)
		v580 := v1 + 7
		v584 := v1 + 3
		b.A[v584] += (b.A[v580] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580]))) << 1))
		v612 := v1 + 15
		b.A[v612] ^= b.A[v584]
		b.A[v612] = bits.RotateLeft64(b.A[v612], 64-32)
		v633 := v1 + 11
		b.A[v633] += (b.A[v612] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = bits.RotateLeft64(b.A[v580], 64-24)
		b.A[v584] += (b.A[v580] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v612] ^= b.A[v584]
		b.A[v612] = bits.RotateLeft64(b.A[v612], 64-16)
		b.A[v633] += (b.A[v612] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = bits.RotateLeft64(b.A[v580], 64-63)
		b.A[v1] += (b.A[v188] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = bits.RotateLeft64(b.A[v612], 64-32)
		b.A[v437] += (b.A[v612] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = bits.RotateLeft64(b.A[v188], 64-24)
		b.A[v1] += (b.A[v188] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = bits.RotateLeft64(b.A[v612], 64-16)
		b.A[v437] += (b.A[v612] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = bits.RotateLeft64(b.A[v188], 64-63)
		b.A[v192] += (b.A[v384] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = bits.RotateLeft64(b.A[v32], 64-32)
		b.A[v633] += (b.A[v32] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = bits.RotateLeft64(b.A[v384], 64-24)
		b.A[v192] += (b.A[v384] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = bits.RotateLeft64(b.A[v32], 64-16)
		b.A[v633] += (b.A[v32] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = bits.RotateLeft64(b.A[v384], 64-63)
		b.A[v388] += (b.A[v580] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = bits.RotateLeft64(b.A[v220], 64-32)
		b.A[v53] += (b.A[v220] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = bits.RotateLeft64(b.A[v580], 64-24)
		b.A[v388] += (b.A[v580] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = bits.RotateLeft64(b.A[v220], 64-16)
		b.A[v53] += (b.A[v220] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = bits.RotateLeft64(b.A[v580], 64-63)
		b.A[v584] += (b.A[v8] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = bits.RotateLeft64(b.A[v416], 64-32)
		b.A[v241] += (b.A[v416] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = bits.RotateLeft64(b.A[v8], 64-24)
		b.A[v584] += (b.A[v8] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = bits.RotateLeft64(b.A[v416], 64-16)
		b.A[v241] += (b.A[v416] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = bits.RotateLeft64(b.A[v8], 64-63)
		v1 += 16
	}
	v1542 = 0
	for v1542 < 16 {
		v1549 := v1542 + 32
		b.A[v1542] += (b.A[v1549] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549]))) << 1))
		v1573 := v1542 + 96
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], 64-32)
		v1594 := v1542 + 64
		b.A[v1594] += (b.A[v1573] + ((uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573]))) << 1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = bits.RotateLeft64(b.A[v1549], 64-24)
		b.A[v1542] += (b.A[v1549] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549]))) << 1))
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], 64-16)
		b.A[v1594] += (b.A[v1573] + ((uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573]))) << 1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = bits.RotateLeft64(b.A[v1549], 64-63)
		v1729 := v1542 + 33
		v1733 := v1542 + 1
		b.A[v1733] += (b.A[v1729] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729]))) << 1))
		v1761 := v1542 + 97
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = bits.RotateLeft64(b.A[v1761], 64-32)
		v1782 := v1542 + 65
		b.A[v1782] += (b.A[v1761] + ((uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761]))) << 1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], 64-24)
		b.A[v1733] += (b.A[v1729] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = bits.RotateLeft64(b.A[v1761], 64-16)
		b.A[v1782] += (b.A[v1761] + ((uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761]))) << 1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], 64-63)
		v1925 := v1542 + 48
		v1929 := v1542 + 16
		b.A[v1929] += (b.A[v1925] + ((uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925]))) << 1))
		v1957 := v1542 + 112
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = bits.RotateLeft64(b.A[v1957], 64-32)
		v1978 := v1542 + 80
		b.A[v1978] += (b.A[v1957] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957]))) << 1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = bits.RotateLeft64(b.A[v1925], 64-24)
		b.A[v1929] += (b.A[v1925] + ((uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925]))) << 1))
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = bits.RotateLeft64(b.A[v1957], 64-16)
		b.A[v1978] += (b.A[v1957] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957]))) << 1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = bits.RotateLeft64(b.A[v1925], 64-63)
		v2121 := v1542 + 49
		v2125 := v1542 + 17
		b.A[v2125] += (b.A[v2121] + ((uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121]))) << 1))
		v2153 := v1542 + 113
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], 64-32)
		v2174 := v1542 + 81
		b.A[v2174] += (b.A[v2153] + ((uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = bits.RotateLeft64(b.A[v2121], 64-24)
		b.A[v2125] += (b.A[v2121] + ((uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121]))) << 1))
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], 64-16)
		b.A[v2174] += (b.A[v2153] + ((uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = bits.RotateLeft64(b.A[v2121], 64-63)
		b.A[v1542] += (b.A[v1729] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], 64-32)
		b.A[v1978] += (b.A[v2153] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], 64-24)
		b.A[v1542] += (b.A[v1729] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], 64-16)
		b.A[v1978] += (b.A[v2153] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], 64-63)
		b.A[v1733] += (b.A[v1925] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1925]))) << 1))
		b.A[v1573] ^= b.A[v1733]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], 64-32)
		v2547 := b.A[v1573]
		v2551 := b.A[v2174]
		v2562 := (uint64(uint32(v2551)) * uint64(uint32(v2547))) << 1
		v2563 := v2547 + v2562
		v2568 := v2551 + v2563
		b.A[v2174] = v2568
		v2575 := b.A[v2174]
		v2579 := b.A[v1925]
		v2580 := v2579 ^ v2575
		b.A[v1925] = v2580
		v2587 := b.A[v1925]
		v2589 := bits.RotateLeft64(v2587, 64-24)
		b.A[v1925] = v2589
		v2596 := b.A[v1925]
		v2600 := b.A[v1733]
		v2601 := uint32(v2600)
		v2602 := uint64(v2601)
		v2607 := uint32(v2596)
		v2608 := uint64(v2607)
		v2609 := v2602 * v2608
		v2611 := v2609 << 1
		v2612 := v2596 + v2611
		v2617 := v2600 + v2612
		b.A[v1733] = v2617
		v2624 := b.A[v1733]
		v2628 := b.A[v1573]
		v2629 := v2628 ^ v2624
		b.A[v1573] = v2629
		v2636 := b.A[v1573]
		v2638 := bits.RotateLeft64(v2636, 64-16)
		b.A[v1573] = v2638
		v2645 := b.A[v1573]
		v2649 := b.A[v2174]
		v2650 := uint32(v2649)
		v2651 := uint64(v2650)
		v2656 := uint32(v2645)
		v2657 := uint64(v2656)
		v2658 := v2651 * v2657
		v2660 := v2658 << 1
		v2661 := v2645 + v2660
		v2666 := v2649 + v2661
		b.A[v2174] = v2666
		v2673 := b.A[v2174]
		v2677 := b.A[v1925]
		v2678 := v2677 ^ v2673
		b.A[v1925] = v2678
		v2685 := b.A[v1925]
		v2687 := bits.RotateLeft64(v2685, 64-63)
		b.A[v1925] = v2687
		v2694 := b.A[v2121]
		v2698 := b.A[v1929]
		v2699 := uint32(v2698)
		v2700 := uint64(v2699)
		v2705 := uint32(v2694)
		v2706 := uint64(v2705)
		v2707 := v2700 * v2706
		v2709 := v2707 << 1
		v2710 := v2694 + v2709
		v2715 := v2698 + v2710
		b.A[v1929] = v2715
		v2722 := b.A[v1929]
		v2726 := b.A[v1761]
		v2727 := v2726 ^ v2722
		b.A[v1761] = v2727
		v2734 := b.A[v1761]
		v2736 := bits.RotateLeft64(v2734, 64-32)
		b.A[v1761] = v2736
		v2743 := b.A[v1761]
		v2747 := b.A[v1594]
		v2748 := uint32(v2747)
		v2749 := uint64(v2748)
		v2754 := uint32(v2743)
		v2755 := uint64(v2754)
		v2756 := v2749 * v2755
		v2758 := v2756 << 1
		v2759 := v2743 + v2758
		v2764 := v2747 + v2759
		b.A[v1594] = v2764
		v2771 := b.A[v1594]
		v2775 := b.A[v2121]
		v2776 := v2775 ^ v2771
		b.A[v2121] = v2776
		v2783 := b.A[v2121]
		v2785 := bits.RotateLeft64(v2783, 64-24)
		b.A[v2121] = v2785
		v2792 := b.A[v2121]
		v2796 := b.A[v1929]
		v2797 := uint32(v2796)
		v2798 := uint64(v2797)
		v2803 := uint32(v2792)
		v2804 := uint64(v2803)
		v2805 := v2798 * v2804
		v2807 := v2805 << 1
		v2808 := v2792 + v2807
		v2813 := v2796 + v2808
		b.A[v1929] = v2813
		v2820 := b.A[v1929]
		v2824 := b.A[v1761]
		v2825 := v2824 ^ v2820
		b.A[v1761] = v2825
		v2832 := b.A[v1761]
		v2834 := bits.RotateLeft64(v2832, 64-16)
		b.A[v1761] = v2834
		v2841 := b.A[v1761]
		v2845 := b.A[v1594]
		v2846 := uint32(v2845)
		v2847 := uint64(v2846)
		v2852 := uint32(v2841)
		v2853 := uint64(v2852)
		v2854 := v2847 * v2853
		v2856 := v2854 << 1
		v2857 := v2841 + v2856
		v2862 := v2845 + v2857
		b.A[v1594] = v2862
		v2869 := b.A[v1594]
		v2873 := b.A[v2121]
		v2874 := v2873 ^ v2869
		b.A[v2121] = v2874
		v2881 := b.A[v2121]
		v2883 := bits.RotateLeft64(v2881, 64-63)
		b.A[v2121] = v2883
		v2890 := b.A[v1549]
		v2894 := b.A[v2125]
		v2895 := uint32(v2894)
		v2896 := uint64(v2895)
		v2901 := uint32(v2890)
		v2902 := uint64(v2901)
		v2903 := v2896 * v2902
		v2905 := v2903 << 1
		v2906 := v2890 + v2905
		v2911 := v2894 + v2906
		b.A[v2125] = v2911
		v2918 := b.A[v2125]
		v2922 := b.A[v1957]
		v2923 := v2922 ^ v2918
		b.A[v1957] = v2923
		v2930 := b.A[v1957]
		v2932 := bits.RotateLeft64(v2930, 64-32)
		b.A[v1957] = v2932
		v2939 := b.A[v1957]
		v2943 := b.A[v1782]
		v2944 := uint32(v2943)
		v2945 := uint64(v2944)
		v2950 := uint32(v2939)
		v2951 := uint64(v2950)
		v2952 := v2945 * v2951
		v2954 := v2952 << 1
		v2955 := v2939 + v2954
		v2960 := v2943 + v2955
		b.A[v1782] = v2960
		v2967 := b.A[v1782]
		v2971 := b.A[v1549]
		v2972 := v2971 ^ v2967
		b.A[v1549] = v2972
		v2979 := b.A[v1549]
		v2981 := bits.RotateLeft64(v2979, 64-24)
		b.A[v1549] = v2981
		v2988 := b.A[v1549]
		v2992 := b.A[v2125]
		v2993 := uint32(v2992)
		v2994 := uint64(v2993)
		v2999 := uint32(v2988)
		v3000 := uint64(v2999)
		v3001 := v2994 * v3000
		v3003 := v3001 << 1
		v3004 := v2988 + v3003
		v3009 := v2992 + v3004
		b.A[v2125] = v3009
		v3016 := b.A[v2125]
		v3020 := b.A[v1957]
		v3021 := v3020 ^ v3016
		b.A[v1957] = v3021
		v3028 := b.A[v1957]
		v3030 := bits.RotateLeft64(v3028, 64-16)
		b.A[v1957] = v3030
		v3037 := b.A[v1957]
		v3041 := b.A[v1782]
		v3042 := uint32(v3041)
		v3043 := uint64(v3042)
		v3048 := uint32(v3037)
		v3049 := uint64(v3048)
		v3050 := v3043 * v3049
		v3052 := v3050 << 1
		v3053 := v3037 + v3052
		v3058 := v3041 + v3053
		b.A[v1782] = v3058
		v3065 := b.A[v1782]
		v3069 := b.A[v1549]
		v3070 := v3069 ^ v3065
		b.A[v1549] = v3070
		v3077 := b.A[v1549]
		v3079 := bits.RotateLeft64(v3077, 64-63)
		b.A[v1549] = v3079
		v1542 += 2
	}
}

func Fe_0(h []int) {
	var v1 uint64
	v1 = 0
	for v1 < 10 {
		h[v1] = 0
		v1++
	}
}

func Fe_1(h []int) {
	var v3 uint64
	h[0] = 1
	v3 = 0
	for v3 < 9 {
		h[int(uint64(1) + v3)] = 0
		v3++
	}
}

func Fe_copy(h []int, f []int) {
	var v2 uint64
	v2 = 0
	for v2 < 10 {
		h[v2] = f[v2]
		v2++
	}
}

func Fe_neg(h []int, f []int) {
	var v2 uint64
	v2 = 0
	for v2 < 10 {
		h[v2] = -int(f[v2])
		v2++
	}
}

func Fe_add(h []int, f []int, g []int) {
	var v3 uint64
	v3 = 0
	for v3 < 10 {
		h[v3] = f[v3] + g[v3]
		v3++
	}
}

func Fe_sub(h []int, f []int, g []int) {
	var v3 uint64
	v3 = 0
	for v3 < 10 {
		h[v3] = f[v3] - g[v3]
		v3++
	}
}

func Fe_cswap(f []int, g []int, b int) {
	var v6 uint64
	v6 = 0
	for v6 < 10 {
		v12 := f[v6]
		v13 := g[v6]
		v15 := (v12 ^ v13) & -b
		f[v6] = v12 ^ v15
		g[v6] = v13 ^ v15
		v6++
	}
}

func Fe_ccopy(f []int, g []int, b int) {
	var v6 uint64
	v6 = 0
	for v6 < 10 {
		f[v6] ^= ((f[v6] ^ g[v6]) & -b)
		v6++
	}
}

func Fe_frombytes_mask(h []int, s []byte, nb_mask uint32) {
	var v6 int64
	var v8 int64
	var v15 int64
	var v22 int64
	var v29 int64
	var v36 int64
	var v41 int64
	var v48 int64
	var v55 int64
	var v62 int64
	var v70 int64
	v6 = int64(Load32_le(s))
	v8 = int64(Load24_le(s[4:]) << 6)
	v15 = int64(Load24_le(s[7:]) << 5)
	v22 = int64(Load24_le(s[10:]) << 3)
	v29 = int64(Load24_le(s[13:]) << 2)
	v36 = int64(Load32_le(s[16:]))
	v41 = int64(Load24_le(s[20:]) << 7)
	v48 = int64(Load24_le(s[23:]) << 5)
	v55 = int64(Load24_le(s[26:]) << 4)
	v62 = int64((Load24_le(s[29:]) & (uint32(0xffffff) >> uint8(nb_mask))) << 2)
	v72 := int64(1)
	v74 := v72 << 25
	v70 = (v6 + v74) >> 26
	v81 := v72 << 26
	v6 -= (v70 * v81)
	v8 += v70
	v70 = (v29 + v74) >> 26
	v29 -= (v70 * v81)
	v36 += v70
	v102 := v72 << 24
	v70 = (v8 + v102) >> 25
	v8 -= (v70 * v74)
	v15 += v70
	v70 = (v36 + v102) >> 25
	v36 -= (v70 * v74)
	v41 += v70
	v70 = (v15 + v74) >> 26
	v15 -= (v70 * v81)
	v22 += v70
	v70 = (v41 + v74) >> 26
	v41 -= (v70 * v81)
	v48 += v70
	v70 = (v22 + v102) >> 25
	v22 -= (v70 * v74)
	v29 += v70
	v70 = (v48 + v102) >> 25
	v48 -= (v70 * v74)
	v55 += v70
	v70 = (v29 + v74) >> 26
	v29 -= (v70 * v81)
	v36 += v70
	v70 = (v55 + v74) >> 26
	v55 -= (v70 * v81)
	v62 += v70
	v70 = (v62 + v102) >> 25
	v62 -= (v70 * v74)
	v6 += (v70 * 19)
	v70 = (v6 + v74) >> 26
	v6 -= (v70 * v81)
	v8 += v70
	h[0] = int(v6)
	h[1] = int(v8)
	h[2] = int(v15)
	h[3] = int(v22)
	h[4] = int(v29)
	h[5] = int(v36)
	h[6] = int(v41)
	h[7] = int(v48)
	h[8] = int(v55)
	h[9] = int(v62)
}

func Fe_frombytes(h []int, s []byte) {
	Fe_frombytes_mask(h, s, uint32(1))
}

func Fe_tobytes(s []byte, h []int) {
	var v4 uint64
	var v10 int
	var v22 uint64
	var v43 uint64
	var _arr_v3 [10]int
	v3 := _arr_v3[:]
	v4 = 0
	for v4 < 10 {
		v3[v4] = h[v4]
		v4++
	}
	v10 = ((19 * v3[9]) + (1 << 24)) >> 25
	v22 = 0
	for v22 < 5 {
		v28 := 2 * int(v22)
		v10 += v3[v28]
		v10 >>= 26
		v10 = v10 + v3[int(v28 + 1)]
		v10 >>= 25
		v22++
	}
	v10 *= 19
	v43 = 0
	for v43 < 5 {
		v49 := v43 * 2
		v3[v49] += v10
		v56 := v3[v49]
		v10 = v56 >> 26
		v60 := 1
		v3[v49] = v56 - (v10 * (v60 << 26))
		v73 := v49 + uint64(1)
		v3[v73] += v10
		v84 := v3[v73]
		v10 = v84 >> 25
		v3[v73] = v84 - (v10 * (v60 << 25))
		v43++
	}
	v112 := uint32(v3[1])
	Store32_le(s, (uint32(v3[0]) | (v112 << 26)))
	v127 := uint32(v3[2])
	Store32_le(s[4:], ((v112 >> 6) | (v127 << 19)))
	v142 := uint32(v3[3])
	Store32_le(s[8:], ((v127 >> 13) | (v142 << 13)))
	Store32_le(s[12:], ((v142 >> 19) | (uint32(v3[4]) << 6)))
	v172 := uint32(v3[6])
	Store32_le(s[16:], (uint32(v3[5]) | (v172 << 25)))
	v187 := uint32(v3[7])
	Store32_le(s[20:], ((v172 >> 7) | (v187 << 19)))
	v202 := uint32(v3[8])
	Store32_le(s[24:], ((v187 >> 13) | (v202 << 12)))
	Store32_le(s[28:], ((v202 >> 20) | (uint32(v3[9]) << 6)))
	clear(v3)
}

func Fe_mul_small(h []int, f []int, g int) {
	var v3 int64
	var v8 int64
	var v13 int64
	var v18 int64
	var v23 int64
	var v28 int64
	var v33 int64
	var v38 int64
	var v43 int64
	var v48 int64
	var v53 int64
	v6 := int64(g)
	v3 = int64(f[0] * int(v6))
	v8 = int64(f[1] * int(v6))
	v13 = int64(f[2] * int(v6))
	v18 = int64(f[3] * int(v6))
	v23 = int64(f[4] * int(v6))
	v28 = int64(f[5] * int(v6))
	v33 = int64(f[6] * int(v6))
	v38 = int64(f[7] * int(v6))
	v43 = int64(f[8] * int(v6))
	v48 = int64(f[9] * int(v6))
	v55 := int64(1)
	v57 := v55 << 25
	v53 = (v3 + v57) >> 26
	v64 := v55 << 26
	v3 -= (v53 * v64)
	v8 += v53
	v53 = (v23 + v57) >> 26
	v23 -= (v53 * v64)
	v28 += v53
	v85 := v55 << 24
	v53 = (v8 + v85) >> 25
	v8 -= (v53 * v57)
	v13 += v53
	v53 = (v28 + v85) >> 25
	v28 -= (v53 * v57)
	v33 += v53
	v53 = (v13 + v57) >> 26
	v13 -= (v53 * v64)
	v18 += v53
	v53 = (v33 + v57) >> 26
	v33 -= (v53 * v64)
	v38 += v53
	v53 = (v18 + v85) >> 25
	v18 -= (v53 * v57)
	v23 += v53
	v53 = (v38 + v85) >> 25
	v38 -= (v53 * v57)
	v43 += v53
	v53 = (v23 + v57) >> 26
	v23 -= (v53 * v64)
	v28 += v53
	v53 = (v43 + v57) >> 26
	v43 -= (v53 * v64)
	v48 += v53
	v53 = (v48 + v85) >> 25
	v48 -= (v53 * v57)
	v3 += (v53 * 19)
	v53 = (v3 + v57) >> 26
	v3 -= (v53 * v64)
	v8 += v53
	h[0] = int(v3)
	h[1] = int(v8)
	h[2] = int(v13)
	h[3] = int(v18)
	h[4] = int(v23)
	h[5] = int(v28)
	h[6] = int(v33)
	h[7] = int(v38)
	h[8] = int(v43)
	h[9] = int(v48)
}

func Fe_mul(h []int, f []int, g []int) {
	var v105 int64
	var v135 int64
	var v165 int64
	var v195 int64
	var v225 int64
	var v255 int64
	var v285 int64
	var v315 int64
	var v345 int64
	var v375 int64
	var v405 int64
	v5 := f[0]
	v8 := f[1]
	v11 := f[2]
	v14 := f[3]
	v17 := f[4]
	v20 := f[5]
	v23 := f[6]
	v26 := f[7]
	v29 := f[8]
	v32 := f[9]
	v38 := g[1]
	v41 := g[2]
	v44 := g[3]
	v47 := g[4]
	v50 := g[5]
	v53 := g[6]
	v56 := g[7]
	v59 := g[8]
	v62 := g[9]
	v65 := v8 * 2
	v68 := v14 * 2
	v71 := v20 * 2
	v74 := v26 * 2
	v77 := v32 * 2
	v106 := int64(g[0])
	v108 := int64(v62 * 19)
	v111 := int64(v59 * 19)
	v114 := int64(v56 * 19)
	v117 := int64(v53 * 19)
	v120 := int64(v50 * 19)
	v123 := int64(v47 * 19)
	v126 := int64(v44 * 19)
	v129 := int64(v41 * 19)
	v105 = int64(((v5 * int(v106) + v65 * int(v108)) + ((v11 * int(v111)) + (v68 * int(v114) + v17 * int(v117)))) + ((v71 * int(v120) + v23 * int(v123)) + ((v74 * int(v126)) + (v29 * int(v129) + v77 * int(int64(v38 * 19))))))
	v136 := int64(v38)
	v135 = int64(((v5 * int(v136) + v8 * int(v106)) + ((v11 * int(v108)) + (v14 * int(v111) + v17 * int(v114)))) + ((v20 * int(v117) + v23 * int(v120)) + ((v26 * int(v123)) + (v29 * int(v126) + v32 * int(v129)))))
	v166 := int64(v41)
	v165 = int64(((v5 * int(v166) + v65 * int(v136)) + ((v11 * int(v106)) + (v68 * int(v108) + v17 * int(v111)))) + ((v71 * int(v114) + v23 * int(v117)) + ((v74 * int(v120)) + (v29 * int(v123) + v77 * int(v126)))))
	v196 := int64(v44)
	v195 = int64(((v5 * int(v196) + v8 * int(v166)) + ((v11 * int(v136)) + (v14 * int(v106) + v17 * int(v108)))) + ((v20 * int(v111) + v23 * int(v114)) + ((v26 * int(v117)) + (v29 * int(v120) + v32 * int(v123)))))
	v226 := int64(v47)
	v225 = int64(((v5 * int(v226) + v65 * int(v196)) + ((v11 * int(v166)) + (v68 * int(v136) + v17 * int(v106)))) + ((v71 * int(v108) + v23 * int(v111)) + ((v74 * int(v114)) + (v29 * int(v117) + v77 * int(v120)))))
	v256 := int64(v50)
	v255 = int64(((v5 * int(v256) + v8 * int(v226)) + ((v11 * int(v196)) + (v14 * int(v166) + v17 * int(v136)))) + ((v20 * int(v106) + v23 * int(v108)) + ((v26 * int(v111)) + (v29 * int(v114) + v32 * int(v117)))))
	v286 := int64(v53)
	v285 = int64(((v5 * int(v286) + v65 * int(v256)) + ((v11 * int(v226)) + (v68 * int(v196) + v17 * int(v166)))) + ((v71 * int(v136) + v23 * int(v106)) + ((v74 * int(v108)) + (v29 * int(v111) + v77 * int(v114)))))
	v316 := int64(v56)
	v315 = int64(((v5 * int(v316) + v8 * int(v286)) + ((v11 * int(v256)) + (v14 * int(v226) + v17 * int(v196)))) + ((v20 * int(v166) + v23 * int(v136)) + ((v26 * int(v106)) + (v29 * int(v108) + v32 * int(v111)))))
	v346 := int64(v59)
	v345 = int64(((v5 * int(v346) + v65 * int(v316)) + ((v11 * int(v286)) + (v68 * int(v256) + v17 * int(v226)))) + ((v71 * int(v196) + v23 * int(v166)) + ((v74 * int(v136)) + (v29 * int(v106) + v77 * int(v108)))))
	v375 = int64(((v5 * int(int64(v62)) + v8 * int(v346)) + ((v11 * int(v316)) + (v14 * int(v286) + v17 * int(v256)))) + ((v20 * int(v226) + v23 * int(v196)) + ((v26 * int(v166)) + (v29 * int(v136) + v32 * int(v106)))))
	v407 := int64(1)
	v409 := v407 << 25
	v405 = (v105 + v409) >> 26
	v416 := v407 << 26
	v105 -= (v405 * v416)
	v135 += v405
	v405 = (v225 + v409) >> 26
	v225 -= (v405 * v416)
	v255 += v405
	v437 := v407 << 24
	v405 = (v135 + v437) >> 25
	v135 -= (v405 * v409)
	v165 += v405
	v405 = (v255 + v437) >> 25
	v255 -= (v405 * v409)
	v285 += v405
	v405 = (v165 + v409) >> 26
	v165 -= (v405 * v416)
	v195 += v405
	v405 = (v285 + v409) >> 26
	v285 -= (v405 * v416)
	v315 += v405
	v405 = (v195 + v437) >> 25
	v195 -= (v405 * v409)
	v225 += v405
	v405 = (v315 + v437) >> 25
	v315 -= (v405 * v409)
	v345 += v405
	v405 = (v225 + v409) >> 26
	v225 -= (v405 * v416)
	v255 += v405
	v405 = (v345 + v409) >> 26
	v345 -= (v405 * v416)
	v375 += v405
	v405 = (v375 + v437) >> 25
	v375 -= (v405 * v409)
	v105 += (v405 * 19)
	v405 = (v105 + v409) >> 26
	v105 -= (v405 * v416)
	v135 += v405
	h[0] = int(v105)
	h[1] = int(v135)
	h[2] = int(v165)
	h[3] = int(v195)
	h[4] = int(v225)
	h[5] = int(v255)
	h[6] = int(v285)
	h[7] = int(v315)
	h[8] = int(v345)
	h[9] = int(v375)
}

func Fe_sq(h []int, f []int) {
	var v71 int64
	var v89 int64
	var v104 int64
	var v122 int64
	var v137 int64
	var v155 int64
	var v170 int64
	var v188 int64
	var v203 int64
	var v221 int64
	var v236 int64
	v4 := f[0]
	v7 := f[1]
	v10 := f[2]
	v13 := f[3]
	v16 := f[4]
	v19 := f[5]
	v22 := f[6]
	v25 := f[7]
	v28 := f[8]
	v31 := f[9]
	v34 := v4 * 2
	v37 := v7 * 2
	v40 := v10 * 2
	v43 := v13 * 2
	v46 := v16 * 2
	v49 := v19 * 2
	v55 := v25 * 2
	v74 := int64(v31 * 38)
	v77 := int64(v28 * 19)
	v80 := int64(v25 * 38)
	v83 := int64(v22 * 19)
	v71 = int64(((v4 * int(int64(v4))) + (v37 * int(v74) + v40 * int(v77))) + ((v43 * int(v80)) + (v46 * int(v83) + v19 * int(int64(v19 * 38)))))
	v90 := int64(v7)
	v89 = int64((v34 * int(v90) + v10 * int(v74)) + ((v43 * int(v77)) + (v16 * int(v80) + v49 * int(v83))))
	v105 := int64(v10)
	v104 = int64(((v34 * int(v105)) + (v37 * int(v90) + v43 * int(v74))) + ((v46 * int(v77)) + (v49 * int(v80) + v22 * int(v83))))
	v123 := int64(v13)
	v122 = int64((v34 * int(v123) + v37 * int(v105)) + ((v16 * int(v74)) + (v49 * int(v77) + v22 * int(v80))))
	v138 := int64(v16)
	v137 = int64(((v34 * int(v138)) + (v37 * int(int64(v43)) + v10 * int(v105))) + ((v49 * int(v74)) + ((v22 * 2) * int(v77) + v25 * int(v80))))
	v156 := int64(v19)
	v155 = int64((v34 * int(v156) + v37 * int(v138)) + ((v40 * int(v123)) + (v22 * int(v74) + v55 * int(v77))))
	v171 := int64(v22)
	v173 := int64(v49)
	v170 = int64(((v34 * int(v171)) + (v37 * int(v173) + v40 * int(v138))) + ((v43 * int(v123)) + (v55 * int(v74) + v28 * int(v77))))
	v189 := int64(v25)
	v188 = int64((v34 * int(v189) + v37 * int(v171)) + ((v40 * int(v156)) + (v43 * int(v138) + v28 * int(v74))))
	v204 := int64(v28)
	v203 = int64(((v34 * int(v204)) + (v37 * int(int64(v55)) + v40 * int(v171))) + ((v43 * int(v173)) + (v16 * int(v138) + v31 * int(v74))))
	v221 = int64((v34 * int(int64(v31)) + v37 * int(v204)) + ((v40 * int(v189)) + (v43 * int(v171) + v16 * int(v173))))
	v238 := int64(1)
	v240 := v238 << 25
	v236 = (v71 + v240) >> 26
	v247 := v238 << 26
	v71 -= (v236 * v247)
	v89 += v236
	v236 = (v137 + v240) >> 26
	v137 -= (v236 * v247)
	v155 += v236
	v268 := v238 << 24
	v236 = (v89 + v268) >> 25
	v89 -= (v236 * v240)
	v104 += v236
	v236 = (v155 + v268) >> 25
	v155 -= (v236 * v240)
	v170 += v236
	v236 = (v104 + v240) >> 26
	v104 -= (v236 * v247)
	v122 += v236
	v236 = (v170 + v240) >> 26
	v170 -= (v236 * v247)
	v188 += v236
	v236 = (v122 + v268) >> 25
	v122 -= (v236 * v240)
	v137 += v236
	v236 = (v188 + v268) >> 25
	v188 -= (v236 * v240)
	v203 += v236
	v236 = (v137 + v240) >> 26
	v137 -= (v236 * v247)
	v155 += v236
	v236 = (v203 + v240) >> 26
	v203 -= (v236 * v247)
	v221 += v236
	v236 = (v221 + v268) >> 25
	v221 -= (v236 * v240)
	v71 += (v236 * 19)
	v236 = (v71 + v240) >> 26
	v71 -= (v236 * v247)
	v89 += v236
	h[0] = int(v71)
	h[1] = int(v89)
	h[2] = int(v104)
	h[3] = int(v122)
	h[4] = int(v137)
	h[5] = int(v155)
	h[6] = int(v170)
	h[7] = int(v188)
	h[8] = int(v203)
	h[9] = int(v221)
}

func Fe_isodd(f []int) int {
	var _arr_v2 [32]uint8
	v2 := _arr_v2[:]
	Fe_tobytes(v2, f)
	v8 := v2[0] & uint8(1)
	clear(v2)
	return int(v8)
}

func Fe_isequal(f []int, g []int) int {
	var _arr_v2 [32]uint8
	v2 := _arr_v2[:]
	var _arr_v3 [32]uint8
	v3 := _arr_v3[:]
	Fe_tobytes(v2, f)
	Fe_tobytes(v3, g)
	v7 := Crypto_verify32(v2, v3)
	clear(v2)
	clear(v3)
	return (1 + v7)
}


func Fe_invert(out []int, x []int) {
	var _arr_v2 [10]int
	v2 := _arr_v2[:]
	Fe_sq(v2, x)
	Invsqrt(v2, v2)
	Fe_sq(v2, v2)
	Fe_mul(out, v2, x)
	clear(v2)
}

func Crypto_eddsa_trim_scalar(out []byte, in []byte) {
	var v2 uint64
	v2 = 0
	for v2 < 32 {
		out[v2] = in[v2]
		v2++
	}
	out[0] &= uint8(0xf8)
	out[31] &= uint8(0x7f)
	out[31] |= uint8(64)
}

func Scalar_bit(s []byte, i int) int {
	if i < 0 {
		return 0
	}
	return int((uint32(s[int(i >> 3)]) >> uint8(i & 7)) & uint32(1))
}

func Scalarmult(q []byte, scalar []byte, p []byte, nb_bits int) {
	var v16 int
	var v18 int
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_frombytes(v4, p)
	var _arr_v6 [10]int
	v6 := _arr_v6[:]
	var _arr_v7 [10]int
	v7 := _arr_v7[:]
	var _arr_v8 [10]int
	v8 := _arr_v8[:]
	var _arr_v9 [10]int
	v9 := _arr_v9[:]
	var _arr_v10 [10]int
	v10 := _arr_v10[:]
	var _arr_v11 [10]int
	v11 := _arr_v11[:]
	Fe_1(v6)
	Fe_0(v7)
	Fe_copy(v8, v4)
	Fe_1(v9)
	v16 = 0
	v18 = nb_bits - 1
	for v18 >= 0 {
		v25 := Scalar_bit(scalar, v18)
		v16 ^= v25
		Fe_cswap(v6, v8, v16)
		Fe_cswap(v7, v9, v16)
		v16 = v25
		Fe_sub(v10, v8, v9)
		Fe_sub(v11, v6, v7)
		Fe_add(v6, v6, v7)
		Fe_add(v7, v8, v9)
		Fe_mul(v9, v10, v6)
		Fe_mul(v7, v7, v11)
		Fe_sq(v10, v11)
		Fe_sq(v11, v6)
		Fe_add(v8, v9, v7)
		Fe_sub(v7, v9, v7)
		Fe_mul(v6, v11, v10)
		Fe_sub(v11, v11, v10)
		Fe_sq(v7, v7)
		Fe_mul_small(v9, v11, 0x1db42)
		Fe_sq(v8, v8)
		Fe_add(v10, v10, v9)
		Fe_mul(v9, v4, v7)
		Fe_mul(v7, v11, v10)
		v18--
	}
	Fe_cswap(v6, v8, v16)
	Fe_cswap(v7, v9, v16)
	Fe_invert(v7, v7)
	Fe_mul(v6, v6, v7)
	Fe_tobytes(q, v6)
	clear(v4)
	clear(v6)
	clear(v7)
	clear(v10)
	clear(v8)
	clear(v9)
	clear(v11)
}

func Crypto_x25519(raw_shared_secret []byte, your_secret_key []byte, their_public_key []byte) {
	var _arr_v3 [32]uint8
	v3 := _arr_v3[:]
	Crypto_eddsa_trim_scalar(v3, your_secret_key)
	Scalarmult(raw_shared_secret, v3, their_public_key, 255)
	clear(v3)
}

func Crypto_x25519_public_key(public_key []byte, secret_key []byte) {
	Crypto_x25519(public_key, secret_key, crypto_x25519_public_key_base_point)
}

func Multiply(p []uint32, a []uint32, b []uint32) {
	var v3 uint64
	var v8 uint64
	var v10 uint64
	v3 = 0
	for v3 < 8 {
		v8 = 0
		v10 = 0
		for v10 < 8 {
			v15 := v3 + v10
			v8 += (uint64(p[v15]) + (uint64(a[v3]) * uint64(b[v10])))
			p[v15] = uint32(v8)
			v8 >>= 32
			v10++
		}
		p[int(v3 + 8)] = uint32(v8)
		v3++
	}
}

func Is_above_l(x []uint32) int {
	var v2 uint64
	var v4 uint64
	v2 = 1
	v4 = 0
	for v4 < 8 {
		v2 += (uint64(x[v4]) + uint64(^L[v4] & uint32(0xffffffff)))
		v2 >>= 32
		v4++
	}
	return int(v2)
}



func Crypto_eddsa_reduce(reduced []byte, expanded []byte) {
	var _arr_v2 [16]uint32
	v2 := _arr_v2[:]
	Load32_le_buf(v2, expanded, uint64(16))
	Mod_l(reduced, v2)
	clear(v2)
}

func Crypto_eddsa_mul_add(r []byte, a []byte, b []byte, c []byte) {
	var v14 uint64
	var _arr_v5 [8]uint32
	v5 := _arr_v5[:]
	Load32_le_buf(v5, a, uint64(8))
	var _arr_v8 [8]uint32
	v8 := _arr_v8[:]
	Load32_le_buf(v8, b, uint64(8))
	var _arr_v11 [16]uint32
	v11 := _arr_v11[:]
	Load32_le_buf(v11, c, uint64(8))
	v14 = 0
	for v14 < 8 {
		v11[int(uint64(8) + v14)] = uint32(0)
		v14++
	}
	Multiply(v11, v5, v8)
	Mod_l(r, v11)
	clear(v11)
	clear(v5)
	clear(v8)
}

func Ge_zero(p *Ge) {
	Fe_0(p.X[:])
	Fe_1(p.Y[:])
	Fe_1(p.Z[:])
	Fe_0(p.T[:])
}

func Ge_tobytes(s []byte, h *Ge) {
	var _arr_v2 [10]int
	v2 := _arr_v2[:]
	var _arr_v3 [10]int
	v3 := _arr_v3[:]
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_invert(v2, h.Z[:])
	Fe_mul(v3, h.X[:], v2)
	Fe_mul(v4, h.Y[:], v2)
	Fe_tobytes(s, v4)
	s[31] ^= uint8(Fe_isodd(v3) << 7)
	clear(v2)
	clear(v3)
	clear(v4)
}

func Ge_frombytes_neg_vartime(h *Ge, s []byte) int {
	Fe_frombytes(h.Y[:], s)
	Fe_1(h.Z[:])
	Fe_sq(h.T[:], h.Y[:])
	Fe_mul(h.X[:], h.T[:], d)
	Fe_sub(h.T[:], h.T[:], h.Z[:])
	Fe_add(h.X[:], h.X[:], h.Z[:])
	Fe_mul(h.X[:], h.T[:], h.X[:])
	if !(Invsqrt(h.X[:], h.X[:]) != 0) {
		return -1
	}
	Fe_mul(h.X[:], h.T[:], h.X[:])
	if uint32(Fe_isodd(h.X[:])) == (uint32(s[31]) >> 7) {
		Fe_neg(h.X[:], h.X[:])
	}
	Fe_mul(h.T[:], h.X[:], h.Y[:])
	return 0
}

func Ge_cache(c *Ge_cached, p *Ge) {
	Fe_add(c.Yp[:], p.Y[:], p.X[:])
	Fe_sub(c.Ym[:], p.Y[:], p.X[:])
	Fe_copy(c.Z[:], p.Z[:])
	Fe_mul(c.T2[:], p.T[:], D2)
}

func Ge_add(s *Ge, p *Ge, q *Ge_cached) {
	var _arr_v3 [10]int
	v3 := _arr_v3[:]
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_add(v3, p.Y[:], p.X[:])
	Fe_sub(v4, p.Y[:], p.X[:])
	Fe_mul(v3, v3, q.Yp[:])
	Fe_mul(v4, v4, q.Ym[:])
	Fe_add(s.Y[:], v3, v4)
	Fe_sub(s.X[:], v3, v4)
	Fe_add(s.Z[:], p.Z[:], p.Z[:])
	Fe_mul(s.Z[:], s.Z[:], q.Z[:])
	Fe_mul(s.T[:], p.T[:], q.T2[:])
	Fe_add(v3, s.Z[:], s.T[:])
	Fe_sub(v4, s.Z[:], s.T[:])
	Fe_mul(s.T[:], s.X[:], s.Y[:])
	Fe_mul(s.X[:], s.X[:], v4)
	Fe_mul(s.Y[:], s.Y[:], v3)
	Fe_mul(s.Z[:], v3, v4)
}

func Ge_sub(s *Ge, p *Ge, q *Ge_cached) {
	var v3 Ge_cached
	Fe_copy(v3.Ym[:], q.Yp[:])
	Fe_copy(v3.Yp[:], q.Ym[:])
	Fe_copy(v3.Z[:], q.Z[:])
	Fe_neg(v3.T2[:], q.T2[:])
	Ge_add(s, p, &v3)
}

func Ge_madd(s *Ge, p *Ge, q *Ge_precomp, a []int, b []int) {
	Fe_add(a, p.Y[:], p.X[:])
	Fe_sub(b, p.Y[:], p.X[:])
	Fe_mul(a, a, q.Yp[:])
	Fe_mul(b, b, q.Ym[:])
	Fe_add(s.Y[:], a, b)
	Fe_sub(s.X[:], a, b)
	Fe_add(s.Z[:], p.Z[:], p.Z[:])
	Fe_mul(s.T[:], p.T[:], q.T2[:])
	Fe_add(a, s.Z[:], s.T[:])
	Fe_sub(b, s.Z[:], s.T[:])
	Fe_mul(s.T[:], s.X[:], s.Y[:])
	Fe_mul(s.X[:], s.X[:], b)
	Fe_mul(s.Y[:], s.Y[:], a)
	Fe_mul(s.Z[:], a, b)
}

func Ge_msub(s *Ge, p *Ge, q *Ge_precomp, a []int, b []int) {
	var v5 Ge_precomp
	Fe_copy(v5.Ym[:], q.Yp[:])
	Fe_copy(v5.Yp[:], q.Ym[:])
	Fe_neg(v5.T2[:], q.T2[:])
	Ge_madd(s, p, &v5, a, b)
}

func Ge_double(s *Ge, p *Ge, q *Ge) {
	Fe_sq(q.X[:], p.X[:])
	Fe_sq(q.Y[:], p.Y[:])
	Fe_sq(q.Z[:], p.Z[:])
	Fe_mul_small(q.Z[:], q.Z[:], 2)
	Fe_add(q.T[:], p.X[:], p.Y[:])
	Fe_sq(s.T[:], q.T[:])
	Fe_add(q.T[:], q.Y[:], q.X[:])
	Fe_sub(q.Y[:], q.Y[:], q.X[:])
	Fe_sub(q.X[:], s.T[:], q.T[:])
	Fe_sub(q.Z[:], q.Z[:], q.Y[:])
	Fe_mul(s.X[:], q.X[:], q.Z[:])
	Fe_mul(s.Y[:], q.T[:], q.Y[:])
	Fe_mul(s.Z[:], q.Y[:], q.Z[:])
	Fe_mul(s.T[:], q.X[:], q.T[:])
}




func Crypto_eddsa_scalarbase(point []byte, scalar []byte) {
	var v2 Ge
	Ge_scalarmult_base(&v2, scalar)
	Ge_tobytes(point, &v2)
}

func Crypto_eddsa_key_pair(secret_key []byte, public_key []byte, seed []byte) {
	var v4 uint64
	var v12 uint64
	var v26 uint64
	var _arr_v3 [64]uint8
	v3 := _arr_v3[:]
	v4 = 0
	for v4 < 32 {
		v3[v4] = seed[v4]
		v4++
	}
	clear(seed)
	v12 = 0
	for v12 < 32 {
		secret_key[v12] = v3[v12]
		v12++
	}
	Crypto_blake2b(v3, uint64(64), v3, uint64(32))
	Crypto_eddsa_trim_scalar(v3, v3)
	Crypto_eddsa_scalarbase(secret_key[32:], v3)
	v26 = 0
	for v26 < 32 {
		public_key[v26] = secret_key[int(uint64(32) + v26)]
		v26++
	}
	clear(v3)
}

func Hash_reduce(h []byte, a []byte, a_size uint64, b []byte, b_size uint64, c []byte, c_size uint64) {
	var _arr_v7 [64]uint8
	v7 := _arr_v7[:]
	var v8 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v8, uint64(64))
	Crypto_blake2b_update(&v8, a, a_size)
	Crypto_blake2b_update(&v8, b, b_size)
	Crypto_blake2b_update(&v8, c, c_size)
	Crypto_blake2b_final(&v8, v7)
	Crypto_eddsa_reduce(h, v7)
}

func Crypto_eddsa_sign(signature []byte, secret_key []byte, message []byte, message_size uint64) {
	var v27 uint64
	var _arr_v5 [64]uint8
	v5 := _arr_v5[:]
	var _arr_v6 [32]uint8
	v6 := _arr_v6[:]
	var _arr_v7 [32]uint8
	v7 := _arr_v7[:]
	var _arr_v8 [32]uint8
	v8 := _arr_v8[:]
	Crypto_blake2b(v5, uint64(64), secret_key, uint64(32))
	Crypto_eddsa_trim_scalar(v5, v5)
	Hash_reduce(v6, v5[32:], uint64(32), message, message_size, nil, uint64(0))
	Crypto_eddsa_scalarbase(v8, v6)
	Hash_reduce(v7, v8, uint64(32), secret_key[32:], uint64(32), message, message_size)
	v27 = 0
	for v27 < 32 {
		signature[v27] = v8[v27]
		v27++
	}
	Crypto_eddsa_mul_add(signature[32:], v7, v5, v6)
	clear(v5)
	clear(v6)
}

func Crypto_eddsa_check(signature []byte, public_key []byte, message []byte, message_size uint64) int {
	var _arr_v4 [32]uint8
	v4 := _arr_v4[:]
	Hash_reduce(v4, signature, uint64(32), public_key, uint64(32), message, message_size)
	return Crypto_eddsa_check_equation(signature, public_key, v4)
}

func Crypto_eddsa_to_x25519(x25519 []byte, eddsa []byte) {
	var _arr_v3 [10]int
	v3 := _arr_v3[:]
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_frombytes(v4, eddsa)
	Fe_add(v3, fe_one, v4)
	Fe_sub(v4, fe_one, v4)
	Fe_invert(v4, v4)
	Fe_mul(v3, v3, v4)
	Fe_tobytes(x25519, v3)
	clear(v3)
	clear(v4)
}

func Crypto_x25519_to_eddsa(eddsa []byte, x25519 []byte) {
	var _arr_v3 [10]int
	v3 := _arr_v3[:]
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_frombytes(v4, x25519)
	Fe_sub(v3, v4, fe_one)
	Fe_add(v4, v4, fe_one)
	Fe_invert(v4, v4)
	Fe_mul(v3, v3, v4)
	Fe_tobytes(eddsa, v3)
	clear(v3)
	clear(v4)
}

func Add_xl(s []byte, x uint8) {
	var v6 uint64
	var v8 uint64
	v6 = 0
	v8 = 0
	for v8 < 8 {
		v16 := s[int(4 * int(v8)):]
		v6 = (v6 + uint64(Load32_le(v16))) + uint64(L[v8] * uint32(uint64(x & 7)))
		Store32_le(v16, uint32(v6))
		v6 >>= 32
		v8++
	}
}


func Select_lop(out []int, x []int, k []int, cofactor uint8) {
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	Fe_0(out)
	Fe_ccopy(out, k, int((uint32(cofactor) >> 1) & uint32(1)))
	Fe_ccopy(out, x, int(cofactor & 1))
	Fe_neg(v4, out)
	Fe_ccopy(out, v4, int((uint32(cofactor) >> 2) & uint32(1)))
	clear(v4)
}

func Crypto_x25519_dirty_fast(public_key []byte, secret_key []byte) {
	var _arr_v7 [32]uint8
	v7 := _arr_v7[:]
	var v8 Ge
	Crypto_eddsa_trim_scalar(v7, secret_key)
	Ge_scalarmult_base(&v8, v7)
	var _arr_v12 [10]int
	v12 := _arr_v12[:]
	var _arr_v13 [10]int
	v13 := _arr_v13[:]
	v15 := secret_key[0]
	Select_lop(v12, lop_x, sqrtm1, v15)
	Select_lop(v13, lop_y, fe_one, (v15 + uint8(2)))
	var v22 Ge_precomp
	Fe_add(v22.Yp[:], v13, v12)
	Fe_sub(v22.Ym[:], v13, v12)
	Fe_mul(v22.T2[:], v13, v12)
	Fe_mul(v22.T2[:], v22.T2[:], D2)
	Ge_madd(&v8, &v8, &v22, v12, v13)
	Fe_add(v12, v8.Z[:], v8.Y[:])
	Fe_sub(v13, v8.Z[:], v8.Y[:])
	Fe_invert(v13, v13)
	Fe_mul(v12, v12, v13)
	Fe_tobytes(public_key, v12)
	clear(v12)
clear(v13)
clear(v7)
}

func Crypto_elligator_map(curve []byte, hidden []byte) {
	var _arr_v7 [10]int
	v7 := _arr_v7[:]
	var _arr_v8 [10]int
	v8 := _arr_v8[:]
	var _arr_v9 [10]int
	v9 := _arr_v9[:]
	var _arr_v10 [10]int
	v10 := _arr_v10[:]
	var _arr_v11 [10]int
	v11 := _arr_v11[:]
	Fe_frombytes_mask(v7, hidden, uint32(2))
	Fe_sq(v7, v7)
	Fe_add(v9, v7, v7)
	Fe_add(v8, v9, fe_one)
	Fe_sq(v10, v8)
	Fe_mul(v11, A2, v9)
	Fe_sub(v11, v11, v10)
	Fe_mul(v11, v11, A)
	Fe_mul(v9, v10, v8)
	Fe_mul(v9, v11, v9)
	Fe_mul(v8, v7, ufactor)
	Fe_ccopy(v8, fe_one, Invsqrt(v9, v9))
	Fe_sq(v9, v9)
	Fe_mul(v8, v8, A)
	Fe_mul(v8, v8, v11)
	Fe_mul(v8, v8, v10)
	Fe_mul(v8, v8, v9)
	Fe_neg(v8, v8)
	Fe_tobytes(curve, v8)
	clear(v9)
	clear(v7)
	clear(v10)
	clear(v8)
	clear(v11)
}

func Crypto_elligator_rev(hidden []byte, public_key []byte, tweak uint8) int {
	var _arr_v4 [10]int
	v4 := _arr_v4[:]
	var _arr_v5 [10]int
	v5 := _arr_v5[:]
	var _arr_v6 [10]int
	v6 := _arr_v6[:]
	Fe_frombytes(v4, public_key)
	Fe_add(v5, v4, A)
	Fe_mul(v6, v4, v5)
	Fe_mul_small(v6, v6, -2)
	v15 := Invsqrt(v6, v6)
	if v15 != 0 {
		Fe_ccopy(v4, v5, int(tweak & 1))
		Fe_mul(v6, v4, v6)
		Fe_mul_small(v4, v6, 2)
		Fe_neg(v5, v6)
		Fe_ccopy(v6, v5, Fe_isodd(v4))
		Fe_tobytes(hidden, v6)
		hidden[31] |= (tweak & 0xc0)
	}
	clear(v4)
	clear(v5)
	clear(v6)
	return (v15 - 1)
}

func Redc(u []uint32, x []uint32) {
	var v8 uint64
	var v13 uint64
	var v15 uint64
	var v35 uint64
	var v37 uint64
	var v6 [8]uint32
	var _arr_v7 [8]uint32
	v7 := _arr_v7[:]
	v8 = 0
	for v8 < 8 {
		v13 = 0
		v15 = 0
		for v15 < (uint64(8) - v8) {
			v21 := v8 + v15
			v13 += (uint64(v7[v21]) + (uint64(x[v8]) * uint64(v6[v15])))
			v7[v21] = uint32(v13)
			v13 >>= 32
			v15++
		}
		v8++
	}
	var _arr_v33 [16]uint32
	v33 := _arr_v33[:]
	Multiply(v33, v7, L)
	v35 = 0
	v37 = 0
	for v37 < 16 {
		v35 += (uint64(v33[v37]) + uint64(x[v37]))
		v33[v37] = uint32(v35)
		v35 >>= 32
		v37++
	}
	Remove_l(u, v33[8:])
	clear(v7)
	clear(v33)
}

func Crypto_x25519_inverse(blind_salt []byte, private_key []byte, curve_point []byte) {
	var v11 uint64
	var v28 int
	var v33 uint64
	var v42 uint64
	var v50 uint64
	var v56 uint64
	var _arr_v6 [8]uint32
	v6 := _arr_v6[:]
	var _arr_v7 [32]uint8
	v7 := _arr_v7[:]
	Crypto_eddsa_trim_scalar(v7, private_key)
	var _arr_v9 [8]uint32
	v9 := _arr_v9[:]
	var _arr_v10 [16]uint32
	v10 := _arr_v10[:]
	v11 = 0
	for v11 < 8 {
		v10[v11] = uint32(0)
		v11++
	}
	Load32_le_buf(v10[8:], v7, uint64(8))
	Mod_l(v7, v10)
	Load32_le_buf(v9, v7, uint64(8))
	clear(v10)
	var _arr_v27 [16]uint32
	v27 := _arr_v27[:]
	v28 = 252
	for v28 >= 0 {
		v33 = 0
		for v33 < 16 {
			v27[v33] = uint32(0)
			v33++
		}
		Multiply(v27, v6, v6)
		Redc(v6, v27)
		if Scalar_bit(crypto_x25519_inverse_Lm2, v28) != 0 {
			v42 = 0
			for v42 < 16 {
				v27[v42] = uint32(0)
				v42++
			}
			Multiply(v27, v6, v9)
			Redc(v6, v27)
		}
		v28--
	}
	v50 = 0
	for v50 < 8 {
		v27[v50] = v6[v50]
		v50++
	}
	v56 = 0
	for v56 < 8 {
		v27[int(uint64(8) + v56)] = uint32(0)
		v56++
	}
	Redc(v6, v27)
	Store32_le_buf(v7, v6, uint64(8))
	Add_xl(v7, (v7[0] * uint8(3)))
	Scalarmult(blind_salt, v7, curve_point, 0x100)
	clear(v7)
	clear(v9)
	clear(v27)
	clear(v6)
}

func Lock_auth(mac []byte, auth_key []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) {
	var _arr_v7 [16]uint8
	v7 := _arr_v7[:]
	Store64_le(v7, ad_size)
	Store64_le(v7[8:], text_size)
	var v16 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v16, auth_key)
	Crypto_poly1305_update(&v16, ad, ad_size)
	Crypto_poly1305_update(&v16, zero, Gap(ad_size, uint64(16)))
	Crypto_poly1305_update(&v16, cipher_text, text_size)
	Crypto_poly1305_update(&v16, zero, Gap(text_size, uint64(16)))
	Crypto_poly1305_update(&v16, v7, uint64(16))
	Crypto_poly1305_final(&v16, mac)
}

func Crypto_aead_init_x(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v5 uint64
	Crypto_chacha20_h(ctx.Key[:], key, nonce)
	v5 = 0
	for v5 < 8 {
		ctx.Nonce[v5] = nonce[int(uint64(16) + v5)]
		v5++
	}
	ctx.Counter = uint64(0)
}

func Crypto_aead_init_djb(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v3 uint64
	var v10 uint64
	v3 = 0
	for v3 < 32 {
		ctx.Key[v3] = key[v3]
		v3++
	}
	v10 = 0
	for v10 < 8 {
		ctx.Nonce[v10] = nonce[v10]
		v10++
	}
	ctx.Counter = uint64(0)
}

func Crypto_aead_init_ietf(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	var v3 uint64
	var v10 uint64
	v3 = 0
	for v3 < 32 {
		ctx.Key[v3] = key[v3]
		v3++
	}
	v10 = 0
	for v10 < 8 {
		ctx.Nonce[v10] = nonce[int(uint64(4) + v10)]
		v10++
	}
	ctx.Counter = uint64(Load32_le(nonce)) << 32
}


func Crypto_aead_read(ctx *Crypto_aead_ctx, plain_text []byte, mac []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v24 uint64
	var _arr_v7 [64]uint8
	v7 := _arr_v7[:]
	var _arr_v8 [16]uint8
	v8 := _arr_v8[:]
	Crypto_chacha20_djb(v7, nil, uint64(64), ctx.Key[:], ctx.Nonce[:], ctx.Counter)
	Lock_auth(v8, v7, ad, ad_size, cipher_text, text_size)
	v17 := Crypto_verify16(mac, v8)
	if !(v17 != 0) {
		Crypto_chacha20_djb(plain_text, cipher_text, text_size, ctx.Key[:], ctx.Nonce[:], (ctx.Counter + uint64(1)))
		v24 = 0
		for v24 < 32 {
			ctx.Key[v24] = v7[int(uint64(32) + v24)]
			v24++
		}
	}
	clear(v7)
	clear(v8)
	return v17
}

func Crypto_aead_lock(cipher_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, plain_text []byte, text_size uint64) {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
	Crypto_aead_write(&v8, cipher_text, mac, ad, ad_size, plain_text, text_size)
}

func Crypto_aead_unlock(plain_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
return Crypto_aead_read(&v8, plain_text, mac, ad, ad_size, cipher_text, text_size)
}





