// Code generated by formatgen. DO NOT EDIT.

package secretstream55

const (
	// HeaderSizeV1 est la taille de l'en-tête maison v1 (nonce seul) et
	// de l'en-tête libsodium.
	HeaderSizeV1 = 24
	// HeaderSize est la taille de l'en-tête maison v2 émis par NewEncryptor.
	HeaderSize = 36
	// HeaderSizeV2 est un alias de HeaderSize (en-tête v2).
	HeaderSizeV2             = HeaderSize
	TagSize                  = 16
	ChunkSize                = 65536
	TagMessage        byte   = 0x00
	TagPush           byte   = 0x01
	TagRekey          byte   = 0x02
	TagFinal          byte   = 0x03
	VersionV2         uint16 = 2
	FlagsV2           uint16 = 0
	MinFramePayloadV2        = 17
	MaxFramePayloadV2        = 65553
	adPrefixV2Len            = 21
)

var magicV2 = [8]byte{0x53, 0x53, 0x35, 0x35, 0x2d, 0x76, 0x32, 0x00}
