// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=8235d40247b22fc3a272856ac7cf9cb34b024bd7f188e4ae3f9fc5720f6696e8
package monocypher55

import (
	"runtime"
)

func lock_auth(mac []byte, auth_key []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) {
	var v7 [16]byte
	store64_le(v7[:], ad_size)
	store64_le(v7[8:], text_size)
	var v16 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v16, auth_key[:])
	Crypto_poly1305_update(&v16, ad[:], ad_size)
	Crypto_poly1305_update(&v16, Zero[:], gap(ad_size, uint64(16)))
	Crypto_poly1305_update(&v16, cipher_text[:], text_size)
	Crypto_poly1305_update(&v16, Zero[:], gap(text_size, uint64(16)))
	Crypto_poly1305_update(&v16, v7[:], uint64(16))
	Crypto_poly1305_final(&v16, mac[:])
}

func Crypto_aead_init_x(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	Crypto_chacha20_h(ctx.Key[:], key[:], nonce[:])
	copy(ctx.Nonce[:8], nonce[16:24])
	ctx.Counter = 0
}

func Crypto_aead_init_djb(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	copy(ctx.Key[:32], key[:32])
	copy(ctx.Nonce[:8], nonce[:8])
	ctx.Counter = 0
}

func Crypto_aead_init_ietf(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	_ = nonce[11]
	copy(ctx.Key[:32], key[:32])
	copy(ctx.Nonce[:8], nonce[4:12])
	ctx.Counter = uint64(uint64(((uint32(nonce[0])|uint32(uint32(nonce[1])<<8))|uint32(uint32(nonce[2])<<16))|uint32(uint32(nonce[3])<<24)) << 32)
}

func Crypto_aead_lock(cipher_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, plain_text []byte, text_size uint64) {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key[:], nonce[:])
	Crypto_aead_write(&v8, cipher_text[:], mac[:], ad[:], ad_size, plain_text[:], text_size)
	*&v8 = Crypto_aead_ctx{}
	runtime.KeepAlive(&v8)
}

func Crypto_aead_unlock(plain_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key[:], nonce[:])
	v13 := Crypto_aead_read(&v8, plain_text[:], mac[:], ad[:], ad_size, cipher_text[:], text_size)
	*&v8 = Crypto_aead_ctx{}
	runtime.KeepAlive(&v8)
	return v13
}
