// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

func Lock_auth(mac []byte, auth_key []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) {
	var v7 [16]uint8
	Store64_le(v7[:], ad_size)
	Store64_le(v7[8:], text_size)
	var v16 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v16, auth_key)
	Crypto_poly1305_update(&v16, ad, ad_size)
	Crypto_poly1305_update(&v16, zero, (-ad_size)&15)
	Crypto_poly1305_update(&v16, cipher_text, text_size)
	Crypto_poly1305_update(&v16, zero, (-text_size)&15)
	Crypto_poly1305_update(&v16, v7[:], uint64(16))
	Crypto_poly1305_final(&v16, mac)
}

func Crypto_aead_init_x(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	Crypto_chacha20_h(ctx.Key[:], key, nonce)
	copy(ctx.Nonce[:8], nonce[16:24])
	ctx.Counter = 0
}

func Crypto_aead_init_djb(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	copy(ctx.Key[:32], key[:32])
	copy(ctx.Nonce[:8], nonce[:8])
	ctx.Counter = 0
}

func Crypto_aead_init_ietf(ctx *Crypto_aead_ctx, key []byte, nonce []byte) {
	copy(ctx.Key[:32], key[:32])
	copy(ctx.Nonce[:8], nonce[4:12])
	ctx.Counter = uint64(Load32_le(nonce)) << 32
}

func Crypto_aead_lock(cipher_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, plain_text []byte, text_size uint64) {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
	Crypto_aead_write(&v8, cipher_text, mac, ad, ad_size, plain_text, text_size)
}

func Crypto_aead_unlock(plain_text []byte, mac []byte, key []byte, nonce []byte, ad []byte, ad_size uint64, cipher_text []byte, text_size uint64) int {
	var v8 Crypto_aead_ctx
	Crypto_aead_init_x(&v8, key, nonce)
	return Crypto_aead_read(&v8, plain_text, mac, ad, ad_size, cipher_text, text_size)
}
