// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

import (
	"math/bits"
)

func Blake2b_compress(ctx *Crypto_blake2b_ctx, is_last_block int) {
	var v16 uint64
	var v20 uint64
	var v24 uint64
	var v27 uint64
	var v31 uint64
	var v34 uint64
	var v38 uint64
	var v41 uint64
	var v45 uint64
	var v48 uint64
	var v52 uint64
	var v59 uint64
	var v63 uint64
	var v70 uint64
	var v74 uint64
	var v82 uint64
	var v86 uint64
	v7 := ctx.Input_idx
	ctx.Input_offset[0] += v7
	if ctx.Input_offset[0] < v7 {
		v16 = ctx.Input_offset[1]
		v18 := v16 + 1
		v16 = v18
		ctx.Input_offset[1] = v18
	}
	v20 = ctx.Hash[0]
	v24 = 0x6a09e667f3bcc908
	v27 = ctx.Hash[1]
	v31 = 0xbb67ae8584caa73b
	v34 = ctx.Hash[2]
	v38 = 0x3c6ef372fe94f82b
	v41 = ctx.Hash[3]
	v45 = 0xa54ff53a5f1d36f1
	v48 = ctx.Hash[4]
	v52 = 0x510e527fade682d1 ^ ctx.Input_offset[0]
	v59 = ctx.Hash[5]
	v63 = 0x9b05688c2b3e6c1f ^ ctx.Input_offset[1]
	v70 = ctx.Hash[6]
	v74 = 0x1f83d9abfb41bd6b ^ uint64(^(is_last_block - 1))
	v82 = ctx.Hash[7]
	v86 = 0x5be0cd19137e2179

	v20 += (v48 + ctx.Input[0])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[1])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[2])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[3])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[4])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[6])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[7])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[8])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[9])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[11])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[12])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[13])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[14])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[15])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[14])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[4])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[8])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[9])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[15])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[13])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[6])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[1])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[12])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[0])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[2])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[11])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[7])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[3])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[11])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[8])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[12])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[0])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[2])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[15])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[13])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[10])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[14])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[3])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[6])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[7])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[1])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[9])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[4])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[7])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[9])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[3])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[1])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[13])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[12])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[11])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[14])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[2])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[6])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[5])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[4])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[0])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[15])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[8])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[9])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[0])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[5])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[7])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[2])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[4])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[10])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[15])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[14])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[1])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[11])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[12])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[6])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[8])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[3])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[13])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[2])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[12])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[6])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[10])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[0])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[11])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[8])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[3])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[4])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[13])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[7])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[5])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[15])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[14])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[1])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[9])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[12])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[5])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[1])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[15])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[14])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[13])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[4])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[10])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[0])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[7])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[6])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[3])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[9])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[2])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[8])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[11])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[13])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[11])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[7])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[14])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[12])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[1])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[3])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[9])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[5])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[0])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[15])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[4])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[8])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[6])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[2])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[10])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[6])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[15])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[14])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[9])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[11])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[3])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[0])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[8])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[12])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[2])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[13])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[7])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[1])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[4])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[10])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[2])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[8])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[4])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[7])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[6])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[1])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[5])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[15])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[11])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[9])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[14])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[3])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[12])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[13])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[0])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[0])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[1])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[2])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[3])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[4])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[6])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[7])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[8])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[9])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[11])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[12])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[13])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[14])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[15])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	v20 += (v48 + ctx.Input[14])
	v52 = bits.RotateLeft64((v52 ^ v20), -32)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -24)
	v20 += (v48 + ctx.Input[10])
	v52 = bits.RotateLeft64((v52 ^ v20), -16)
	v24 += v52
	v48 = bits.RotateLeft64((v48 ^ v24), -63)
	v27 += (v59 + ctx.Input[4])
	v63 = bits.RotateLeft64((v63 ^ v27), -32)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -24)
	v27 += (v59 + ctx.Input[8])
	v63 = bits.RotateLeft64((v63 ^ v27), -16)
	v31 += v63
	v59 = bits.RotateLeft64((v59 ^ v31), -63)
	v34 += (v70 + ctx.Input[9])
	v74 = bits.RotateLeft64((v74 ^ v34), -32)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -24)
	v34 += (v70 + ctx.Input[15])
	v74 = bits.RotateLeft64((v74 ^ v34), -16)
	v38 += v74
	v70 = bits.RotateLeft64((v70 ^ v38), -63)
	v41 += (v82 + ctx.Input[13])
	v86 = bits.RotateLeft64((v86 ^ v41), -32)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -24)
	v41 += (v82 + ctx.Input[6])
	v86 = bits.RotateLeft64((v86 ^ v41), -16)
	v45 += v86
	v82 = bits.RotateLeft64((v82 ^ v45), -63)
	v20 += (v59 + ctx.Input[1])
	v86 = bits.RotateLeft64((v86 ^ v20), -32)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -24)
	v20 += (v59 + ctx.Input[12])
	v86 = bits.RotateLeft64((v86 ^ v20), -16)
	v38 += v86
	v59 = bits.RotateLeft64((v59 ^ v38), -63)
	v27 += (v70 + ctx.Input[0])
	v52 = bits.RotateLeft64((v52 ^ v27), -32)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -24)
	v27 += (v70 + ctx.Input[2])
	v52 = bits.RotateLeft64((v52 ^ v27), -16)
	v45 += v52
	v70 = bits.RotateLeft64((v70 ^ v45), -63)
	v34 += (v82 + ctx.Input[11])
	v63 = bits.RotateLeft64((v63 ^ v34), -32)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -24)
	v34 += (v82 + ctx.Input[7])
	v63 = bits.RotateLeft64((v63 ^ v34), -16)
	v24 += v63
	v82 = bits.RotateLeft64((v82 ^ v24), -63)
	v41 += (v48 + ctx.Input[5])
	v74 = bits.RotateLeft64((v74 ^ v41), -32)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -24)
	v41 += (v48 + ctx.Input[3])
	v74 = bits.RotateLeft64((v74 ^ v41), -16)
	v31 += v74
	v48 = bits.RotateLeft64((v48 ^ v31), -63)

	ctx.Hash[0] ^= (v20 ^ v24)
	ctx.Hash[1] ^= (v27 ^ v31)
	ctx.Hash[2] ^= (v34 ^ v38)
	ctx.Hash[3] ^= (v41 ^ v45)
	ctx.Hash[4] ^= (v48 ^ v52)
	ctx.Hash[5] ^= (v59 ^ v63)
	ctx.Hash[6] ^= (v70 ^ v74)
	ctx.Hash[7] ^= (v82 ^ v86)
}

func Crypto_blake2b_keyed_init(ctx *Crypto_blake2b_ctx, hash_size uint64, key []byte, key_size uint64) {
	copy(ctx.Hash[:8], iv[:8])
	ctx.Hash[0] ^= ((uint64(0x1010000) ^ (key_size << 8)) ^ hash_size)
	ctx.Input_offset[0] = 0
	ctx.Input_offset[1] = 0
	ctx.Hash_size = hash_size
	ctx.Input_idx = 0
	clear(ctx.Input[:16])
	if key_size > 0 {
		var v39 [128]uint8
		copy(v39[:key_size], key[:key_size])
		Load64_le_buf(ctx.Input[:], v39[:], uint64(16))
		ctx.Input_idx = 0x80
	}
}

func Crypto_blake2b_init(ctx *Crypto_blake2b_ctx, hash_size uint64) {
	Crypto_blake2b_keyed_init(ctx, hash_size, nil, uint64(0))
}

func Crypto_blake2b_update(ctx *Crypto_blake2b_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v27 uint64
	var v82 uint64
	var v130 uint64
	v3 = 0
	if message_size == 0 {
		return
	}
	if (ctx.Input_idx & 7) != 0 {
		v18 := min(Gap(ctx.Input_idx, uint64(8)), message_size)
		v27 = 0
		for v27 < v18 {
			ctx.Input[int(ctx.Input_idx>>3)] = ctx.Input[int(ctx.Input_idx>>3)] | (uint64(message[v3+v27]) << uint8(((ctx.Input_idx&7)+v27)<<3))
			v27++
		}
		ctx.Input_idx += v18
		v3 += v18
		message_size -= v18
	}
	if (ctx.Input_idx & 0x7f) != 0 {
		v60 := (min(Gap(ctx.Input_idx, uint64(0x80)), message_size)) >> 3
		Load64_le_buf(ctx.Input[int(ctx.Input_idx>>3):], message[v3:], v60)
		v70 := v60 << 3
		ctx.Input_idx += v70
		v3 += v70
		message_size -= v70
	}
	v81 := message_size >> 7
	v82 = 0
	for v82 < v81 {
		if ctx.Input_idx == 0x80 {
			Blake2b_compress(ctx, 0)
		}
		Load64_le_buf(ctx.Input[:], message[v3:], uint64(16))
		v3 += 0x80
		ctx.Input_idx = 0x80
		v82++
	}
	message_size &= 0x7f
	if message_size != 0 {
		if ctx.Input_idx == 0x80 {
			Blake2b_compress(ctx, 0)
			ctx.Input_idx = 0
		}
		if ctx.Input_idx == 0 {
			clear(ctx.Input[:16])
		}
		v116 := message_size >> 3
		Load64_le_buf(ctx.Input[:], message[v3:], v116)
		v121 := v116 << 3
		ctx.Input_idx += v121
		v3 += v121
		message_size -= v121
		v130 = 0
		for v130 < message_size {
			ctx.Input[int(ctx.Input_idx>>3)] = ctx.Input[int(ctx.Input_idx>>3)] | (uint64(message[v3+v130]) << uint8((ctx.Input_idx&7)<<3))
			v154 := ctx.Input_idx + 1
			ctx.Input_idx = v154
			v130++
		}
	}
}

func Crypto_blake2b_final(ctx *Crypto_blake2b_ctx, hash []byte) {
	var v16 uint64
	Blake2b_compress(ctx, 1)
	v10 := min(ctx.Hash_size, uint64(64))
	v13 := v10 >> 3
	Store64_le_buf(hash, ctx.Hash[:], v13)
	v16 = v13 << 3
	for v16 < v10 {
		hash[v16] = uint8((ctx.Hash[int(v16>>3)] >> uint8(uint64(8)*(v16&7))) & 0xff)
		v16++
	}
}

func Crypto_blake2b_keyed(hash []byte, hash_size uint64, key []byte, key_size uint64, message []byte, message_size uint64) {
	var v6 Crypto_blake2b_ctx
	Crypto_blake2b_keyed_init(&v6, hash_size, key, key_size)
	Crypto_blake2b_update(&v6, message, message_size)
	Crypto_blake2b_final(&v6, hash)
}

func Crypto_blake2b(hash []byte, hash_size uint64, msg []byte, msg_size uint64) {
	Crypto_blake2b_keyed(hash, hash_size, nil, uint64(0), msg, msg_size)
}

func Blake_update_32(ctx *Crypto_blake2b_ctx, input uint32) {
	var v2 [4]uint8
	Store32_le(v2[:], input)
	Crypto_blake2b_update(ctx, v2[:], uint64(4))
	clear(v2[:])
}

func Blake_update_32_buf(ctx *Crypto_blake2b_ctx, buf []byte, size uint32) {
	Blake_update_32(ctx, size)
	Crypto_blake2b_update(ctx, buf, uint64(size))
}

func Extended_hash(digest []byte, digest_size uint32, input []byte, input_size uint32) {
	var v28 uint32
	var v30 uint32
	var v32 uint32
	var v5 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v5, uint64(min(digest_size, uint32(64))))
	Blake_update_32(&v5, digest_size)
	Crypto_blake2b_update(&v5, input, uint64(input_size))
	Crypto_blake2b_final(&v5, digest)
	if digest_size > 64 {
		v27 := uint32((uint64(digest_size)+31)>>5) - 2
		v28 = 1
		v30 = 0
		v32 = 32
		for v28 < v27 {
			Crypto_blake2b(digest[v32:], uint64(64), digest[v30:], uint64(64))
			v28++
			v30 += 32
			v32 += 32
		}
		Crypto_blake2b(digest[v32:], uint64(digest_size-(uint32(32)*v27)), digest[v30:], uint64(64))
	}
}
