// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=f153188750419d4fdd312560813483797344c1ce5bf582e043685c3bc2c3dbfd
package monocypher55

import (
	"runtime"
)

func blake2b_compress(ctx *Crypto_blake2b_ctx, is_last_block int) {
	var v6 uint64
	var v15 uint64
	var v17 uint64
	var v19 uint64
	var v23 uint64
	var v26 uint64
	var v30 uint64
	var v33 uint64
	var v37 uint64
	var v40 uint64
	var v44 uint64
	var v47 uint64
	var v51 uint64
	var v58 uint64
	var v62 uint64
	var v69 uint64
	var v73 uint64
	var v81 uint64
	var v85 uint64
	var v90 uint64
	var v98 uint64
	v6 = ctx.Input_idx
	ctx.Input_offset[0] += v6
	if ctx.Input_offset[0] < v6 {
		v15 = ctx.Input_offset[1]
		v17 = v15 + 1
		v15 = v17
		ctx.Input_offset[1] = v17
	}
	v19 = ctx.Hash[0]
	v23 = 0x6a09e667f3bcc908
	v26 = ctx.Hash[1]
	v30 = 0xbb67ae8584caa73b
	v33 = ctx.Hash[2]
	v37 = 0x3c6ef372fe94f82b
	v40 = ctx.Hash[3]
	v44 = 0xa54ff53a5f1d36f1
	v47 = ctx.Hash[4]
	v51 = 0x510e527fade682d1 ^ ctx.Input_offset[0]
	v58 = ctx.Hash[5]
	v62 = 0x9b05688c2b3e6c1f ^ ctx.Input_offset[1]
	v69 = ctx.Hash[6]
	v73 = 0x1f83d9abfb41bd6b ^ uint64(^(is_last_block - 1))
	v81 = ctx.Hash[7]
	v85 = 0x5be0cd19137e2179
	for v90 = 0; v90 < 12; v90++ {
		v98 = v90 * 16
		v19 += (v47 + ctx.Input[int(Sigma[v98])])
		v51 = rotr64((v51 ^ v19), 32)
		v23 += v51
		v47 = rotr64((v47 ^ v23), 24)
		v19 += (v47 + ctx.Input[int(Sigma[v98+1])])
		v51 = rotr64((v51 ^ v19), 16)
		v23 += v51
		v47 = rotr64((v47 ^ v23), 63)
		v26 += (v58 + ctx.Input[int(Sigma[v98+2])])
		v62 = rotr64((v62 ^ v26), 32)
		v30 += v62
		v58 = rotr64((v58 ^ v30), 24)
		v26 += (v58 + ctx.Input[int(Sigma[v98+3])])
		v62 = rotr64((v62 ^ v26), 16)
		v30 += v62
		v58 = rotr64((v58 ^ v30), 63)
		v33 += (v69 + ctx.Input[int(Sigma[v98+4])])
		v73 = rotr64((v73 ^ v33), 32)
		v37 += v73
		v69 = rotr64((v69 ^ v37), 24)
		v33 += (v69 + ctx.Input[int(Sigma[v98+5])])
		v73 = rotr64((v73 ^ v33), 16)
		v37 += v73
		v69 = rotr64((v69 ^ v37), 63)
		v40 += (v81 + ctx.Input[int(Sigma[v98+6])])
		v85 = rotr64((v85 ^ v40), 32)
		v44 += v85
		v81 = rotr64((v81 ^ v44), 24)
		v40 += (v81 + ctx.Input[int(Sigma[v98+7])])
		v85 = rotr64((v85 ^ v40), 16)
		v44 += v85
		v81 = rotr64((v81 ^ v44), 63)
		v19 += (v58 + ctx.Input[int(Sigma[v98+8])])
		v85 = rotr64((v85 ^ v19), 32)
		v37 += v85
		v58 = rotr64((v58 ^ v37), 24)
		v19 += (v58 + ctx.Input[int(Sigma[v98+9])])
		v85 = rotr64((v85 ^ v19), 16)
		v37 += v85
		v58 = rotr64((v58 ^ v37), 63)
		v26 += (v69 + ctx.Input[int(Sigma[v98+10])])
		v51 = rotr64((v51 ^ v26), 32)
		v44 += v51
		v69 = rotr64((v69 ^ v44), 24)
		v26 += (v69 + ctx.Input[int(Sigma[v98+11])])
		v51 = rotr64((v51 ^ v26), 16)
		v44 += v51
		v69 = rotr64((v69 ^ v44), 63)
		v33 += (v81 + ctx.Input[int(Sigma[v98+12])])
		v62 = rotr64((v62 ^ v33), 32)
		v23 += v62
		v81 = rotr64((v81 ^ v23), 24)
		v33 += (v81 + ctx.Input[int(Sigma[v98+13])])
		v62 = rotr64((v62 ^ v33), 16)
		v23 += v62
		v81 = rotr64((v81 ^ v23), 63)
		v40 += (v47 + ctx.Input[int(Sigma[v98+14])])
		v73 = rotr64((v73 ^ v40), 32)
		v30 += v73
		v47 = rotr64((v47 ^ v30), 24)
		v40 += (v47 + ctx.Input[int(Sigma[v98+15])])
		v73 = rotr64((v73 ^ v40), 16)
		v30 += v73
		v47 = rotr64((v47 ^ v30), 63)
	}
	ctx.Hash[0] ^= (v19 ^ v23)
	ctx.Hash[1] ^= (v26 ^ v30)
	ctx.Hash[2] ^= (v33 ^ v37)
	ctx.Hash[3] ^= (v40 ^ v44)
	ctx.Hash[4] ^= (v47 ^ v51)
	ctx.Hash[5] ^= (v58 ^ v62)
	ctx.Hash[6] ^= (v69 ^ v73)
	ctx.Hash[7] ^= (v81 ^ v85)
}

func Crypto_blake2b_keyed_init(ctx *Crypto_blake2b_ctx, hash_size uint64, key []byte, key_size uint64) {
	ctx.Hash[0] = uint64(Iv[0])
	ctx.Hash[1] = uint64(Iv[1])
	ctx.Hash[2] = uint64(Iv[2])
	ctx.Hash[3] = uint64(Iv[3])
	ctx.Hash[4] = uint64(Iv[4])
	ctx.Hash[5] = uint64(Iv[5])
	ctx.Hash[6] = uint64(Iv[6])
	ctx.Hash[7] = uint64(Iv[7])
	ctx.Hash[0] ^= ((uint64(0x1010000) ^ uint64(key_size<<8)) ^ hash_size)
	ctx.Input_offset[0] = 0
	ctx.Input_offset[1] = 0
	ctx.Hash_size = hash_size
	ctx.Input_idx = 0
	clear(ctx.Input[:16])
	if key_size > 0 {
		var v38 [128]byte
		copy(v38[:key_size], key[:key_size])
		load64_le_buf(ctx.Input[:], v38[:], uint64(16))
		ctx.Input_idx = 0x80
	}
}

func Crypto_blake2b_init(ctx *Crypto_blake2b_ctx, hash_size uint64) {
	Crypto_blake2b_keyed_init(ctx, hash_size, nil, uint64(0))
}

func Crypto_blake2b_update(ctx *Crypto_blake2b_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v18 uint64
	var v26 uint64
	var v27 uint64
	var v58 uint64
	var v60 uint64
	var v70 uint64
	var v82 uint64
	var v118 uint64
	var v123 uint64
	var v132 uint64
	var v143 uint64
	var v156 uint64
	v3 = 0
	_ = v3
	if message_size == 0 {
		return
	}
	v8 := ctx.Input_idx & 7
	if v8 != 0 {
		v18 = min(gap(ctx.Input_idx, 8), message_size)
		v26 = ctx.Input_idx & 7
		for v27 = 0; v27 < v18; v27++ {
			ctx.Input[int(uint64(ctx.Input_idx>>3))] = ctx.Input[int(uint64(ctx.Input_idx>>3))] | uint64(uint64(message[v3+v27])<<byte(uint64((v26+v27)<<3)))
		}
		ctx.Input_idx += v18
		v3 += v18
		message_size -= v18
	}
	v48 := ctx.Input_idx & 0x7f
	if v48 != 0 {
		v58 = min(gap(ctx.Input_idx, 0x80), message_size)
		v60 = uint64(v58 >> 3)
		load64_le_buf(ctx.Input[int(uint64(ctx.Input_idx>>3)):], message[v3:], v60)
		v70 = uint64(v60 << 3)
		ctx.Input_idx += v70
		v3 += v70
		message_size -= v70
	}
	v81 := uint64(message_size >> 7)
	for v82 = 0; v82 < v81; v82++ {
		if ctx.Input_idx == 0x80 {
			blake2b_compress(ctx, 0)
		}
		load64_le_buf(ctx.Input[:], message[v3:], uint64(16))
		v3 += 0x80
		ctx.Input_idx = 0x80
	}
	v100 := message_size & 0x7f
	message_size = v100
	if message_size != 0 {
		if ctx.Input_idx == 0x80 {
			blake2b_compress(ctx, 0)
			ctx.Input_idx = 0
		}
		if ctx.Input_idx == 0 {
			clear(ctx.Input[:16])
		}
		v118 = uint64(message_size >> 3)
		load64_le_buf(ctx.Input[:], message[v3:], v118)
		v123 = uint64(v118 << 3)
		ctx.Input_idx += v123
		v3 += v123
		message_size -= v123
		for v132 = 0; v132 < message_size; v132++ {
			v143 = ctx.Input_idx & 7
			ctx.Input[int(uint64(ctx.Input_idx>>3))] = ctx.Input[int(uint64(ctx.Input_idx>>3))] | uint64(uint64(message[v3+v132])<<byte(uint64(v143<<3)))
			v156 = ctx.Input_idx + 1
			ctx.Input_idx = v156
		}
	}
}

func Crypto_blake2b_final(ctx *Crypto_blake2b_ctx, hash []byte) {
	var v10 uint64
	var v16 uint64
	var v27 uint64
	var v31 uint64
	blake2b_compress(ctx, 1)
	v10 = min(ctx.Hash_size, 64)
	v13 := uint64(v10 >> 3)
	store64_le_buf(hash[:], ctx.Hash[:], v13)
	for v16 = uint64(v13 << 3); v16 < v10; v16++ {
		v27 = v16 & 7
		v31 = uint64(ctx.Hash[int(uint64(v16>>3))]>>byte(8*v27)) & 0xff
		hash[v16] = byte(v31)
	}
	*ctx = Crypto_blake2b_ctx{}
	runtime.KeepAlive(ctx)
}

func Crypto_blake2b_keyed(hash []byte, hash_size uint64, key []byte, key_size uint64, message []byte, message_size uint64) {
	var v6 Crypto_blake2b_ctx
	Crypto_blake2b_keyed_init(&v6, hash_size, key[:], key_size)
	Crypto_blake2b_update(&v6, message[:], message_size)
	Crypto_blake2b_final(&v6, hash[:])
}

func Crypto_blake2b(hash []byte, hash_size uint64, msg []byte, msg_size uint64) {
	Crypto_blake2b_keyed(hash[:], hash_size, nil, uint64(0), msg[:], msg_size)
}

func blake_update_32(ctx *Crypto_blake2b_ctx, input uint32) {
	var v2 [4]byte
	v9 := input & 0xff
	v2[0] = byte(v9)
	v14 := uint32(input>>8) & 0xff
	v2[1] = byte(v14)
	v19 := uint32(input>>16) & 0xff
	v2[2] = byte(v19)
	v24 := uint32(input>>24) & 0xff
	v2[3] = byte(v24)
	Crypto_blake2b_update(ctx, v2[:], uint64(4))
	clear(v2[:])
}

func blake_update_32_buf(ctx *Crypto_blake2b_ctx, buf []byte, size uint32) {
	if uint32(len(buf)) < size {
		size = uint32(len(buf))
	}
	blake_update_32(ctx, size)
	Crypto_blake2b_update(ctx, buf[:], uint64(size))
}

func extended_hash(digest []byte, digest_size uint32, input []byte, input_size uint32) {
	var v9 uint32
	var v26 uint32
	var v27 uint32
	var v29 uint32
	var v31 uint32
	var v4 Crypto_blake2b_ctx
	v9 = min(digest_size, 64)
	Crypto_blake2b_init(&v4, uint64(v9))
	blake_update_32(&v4, digest_size)
	Crypto_blake2b_update(&v4, input[:], uint64(input_size))
	Crypto_blake2b_final(&v4, digest[:])
	if digest_size > 64 {
		v26 = uint32(uint64((uint64(digest_size)+31)>>5)) - 2
		v27 = 1
		v29 = 0
		v31 = 32
		for v27 < v26 {
			Crypto_blake2b(digest[v31:], uint64(64), digest[v29:], uint64(64))
			v27++
			v29 += 32
			v31 += 32
		}
		Crypto_blake2b(digest[v31:], uint64(digest_size-(uint32(32)*v26)), digest[v29:], uint64(64))
	}
}
