// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=bbc32fa81cbb1be7df623d16f1a1e6c89697e4cbc7a2fdbe5f0a40ed6a768f4e
package monocypher55

func chacha20_rounds(out []uint32, in []uint32) {
	_ = in[15]
	_ = out[15]
	var v2 uint32
	var v5 uint32
	var v8 uint32
	var v11 uint32
	var v14 uint32
	var v17 uint32
	var v20 uint32
	var v23 uint32
	var v26 uint32
	var v29 uint32
	var v32 uint32
	var v35 uint32
	var v38 uint32
	var v41 uint32
	var v44 uint32
	var v47 uint32
	var v50 uint64
	v2 = in[0]
	v5 = in[1]
	v8 = in[2]
	v11 = in[3]
	v14 = in[4]
	v17 = in[5]
	v20 = in[6]
	v23 = in[7]
	v26 = in[8]
	v29 = in[9]
	v32 = in[10]
	v35 = in[11]
	v38 = in[12]
	v41 = in[13]
	v44 = in[14]
	v47 = in[15]
	for v50 = 0; v50 < 10; v50++ {
		v2 += v14
		v38 = rotl32((v38 ^ v2), 16)
		v26 += v38
		v14 = rotl32((v14 ^ v26), 12)
		v2 += v14
		v38 = rotl32((v38 ^ v2), 8)
		v26 += v38
		v14 = rotl32((v14 ^ v26), 7)
		v5 += v17
		v41 = rotl32((v41 ^ v5), 16)
		v29 += v41
		v17 = rotl32((v17 ^ v29), 12)
		v5 += v17
		v41 = rotl32((v41 ^ v5), 8)
		v29 += v41
		v17 = rotl32((v17 ^ v29), 7)
		v8 += v20
		v44 = rotl32((v44 ^ v8), 16)
		v32 += v44
		v20 = rotl32((v20 ^ v32), 12)
		v8 += v20
		v44 = rotl32((v44 ^ v8), 8)
		v32 += v44
		v20 = rotl32((v20 ^ v32), 7)
		v11 += v23
		v47 = rotl32((v47 ^ v11), 16)
		v35 += v47
		v23 = rotl32((v23 ^ v35), 12)
		v11 += v23
		v47 = rotl32((v47 ^ v11), 8)
		v35 += v47
		v23 = rotl32((v23 ^ v35), 7)
		v2 += v17
		v47 = rotl32((v47 ^ v2), 16)
		v32 += v47
		v17 = rotl32((v17 ^ v32), 12)
		v2 += v17
		v47 = rotl32((v47 ^ v2), 8)
		v32 += v47
		v17 = rotl32((v17 ^ v32), 7)
		v5 += v20
		v38 = rotl32((v38 ^ v5), 16)
		v35 += v38
		v20 = rotl32((v20 ^ v35), 12)
		v5 += v20
		v38 = rotl32((v38 ^ v5), 8)
		v35 += v38
		v20 = rotl32((v20 ^ v35), 7)
		v8 += v23
		v41 = rotl32((v41 ^ v8), 16)
		v26 += v41
		v23 = rotl32((v23 ^ v26), 12)
		v8 += v23
		v41 = rotl32((v41 ^ v8), 8)
		v26 += v41
		v23 = rotl32((v23 ^ v26), 7)
		v11 += v14
		v44 = rotl32((v44 ^ v11), 16)
		v29 += v44
		v14 = rotl32((v14 ^ v29), 12)
		v11 += v14
		v44 = rotl32((v44 ^ v11), 8)
		v29 += v44
		v14 = rotl32((v14 ^ v29), 7)
	}
	out[0] = v2
	out[1] = v5
	out[2] = v8
	out[3] = v11
	out[4] = v14
	out[5] = v17
	out[6] = v20
	out[7] = v23
	out[8] = v26
	out[9] = v29
	out[10] = v32
	out[11] = v35
	out[12] = v38
	out[13] = v41
	out[14] = v44
	out[15] = v47
}

func Crypto_chacha20_ietf(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint32) uint32 {
	_ = nonce[3]
	return uint32(Crypto_chacha20_djb(cipher_text[:], plain_text[:], text_size, key[:], nonce[4:], (uint64(ctr) + uint64(uint64(((uint32(nonce[0])|uint32(uint32(nonce[1])<<8))|uint32(uint32(nonce[2])<<16))|uint32(uint32(nonce[3])<<24))<<32))))
}

func Crypto_chacha20_x(cipher_text []byte, plain_text []byte, text_size uint64, key []byte, nonce []byte, ctr uint64) uint64 {
	var v6 [32]byte
	Crypto_chacha20_h(v6[:], key[:], nonce[:])
	ctr = Crypto_chacha20_djb(cipher_text[:], plain_text[:], text_size, v6[:], nonce[16:], ctr)
	clear(v6[:])
	return ctr
}
