// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=7d797c5f4f2b92ebbbdd0ce618b2ba92bdd561cb431ef2ad805f5a62228a590b
package monocypher55

import (
	"encoding/binary"
	"runtime"
)

func scalar_bit(s []byte, i int) int {
	if i < 0 {
		return 0
	}
	v8 := i & 7
	v11 := (uint32(s[int(i>>3)]) >> byte(v8)) & 1
	return int(v11)
}

func Crypto_x25519(raw_shared_secret []byte, your_secret_key []byte, their_public_key []byte) {
	var v3 [32]byte
	Crypto_eddsa_trim_scalar(v3[:], your_secret_key[:])
	Scalarmult(raw_shared_secret[:], v3[:], their_public_key[:], 255)
	clear(v3[:])
}

func Crypto_x25519_public_key(public_key []byte, secret_key []byte) {
	Crypto_x25519(public_key[:], secret_key[:], Base_point[:])
}

func multiply(p []uint32, a []uint32, b []uint32) {
	_ = a[7]
	var v8 uint64
	var v10 uint64
	var v15 uint64
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 0 + v10
		v8 += (uint64(p[v15]) + (uint64(a[0]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[0+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 1 + v10
		v8 += (uint64(p[v15]) + (uint64(a[1]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[1+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 2 + v10
		v8 += (uint64(p[v15]) + (uint64(a[2]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[2+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 3 + v10
		v8 += (uint64(p[v15]) + (uint64(a[3]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[3+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 4 + v10
		v8 += (uint64(p[v15]) + (uint64(a[4]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[4+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 5 + v10
		v8 += (uint64(p[v15]) + (uint64(a[5]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[5+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 6 + v10
		v8 += (uint64(p[v15]) + (uint64(a[6]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[6+8] = uint32(v8)
	v8 = 0
	for v10 = 0; v10 < 8; v10++ {
		v15 = 7 + v10
		v8 += (uint64(p[v15]) + (uint64(a[7]) * uint64(b[v10])))
		p[v15] = uint32(v8)
		v8 = uint64(v8 >> 32)
	}
	p[7+8] = uint32(v8)
}

func Crypto_x25519_to_eddsa(eddsa []byte, x25519 []byte) {
	var v3 [10]int32
	var v4 [10]int32
	fe_frombytes(&v4, x25519[:])
	fe_sub(&v3, &v4, &Fe_one)
	fe_add(&v4, &v4, &Fe_one)
	fe_invert(&v4, &v4)
	fe_mul(&v3, &v3, &v4)
	fe_tobytes(eddsa[:], &v3)
	clear(v3[:])
	clear(v4[:])
}

func add_xl(s []byte, x byte) {
	var v6 uint64
	var v8 uint64
	var v16 []byte
	var v26 uint32
	var v54 uint32
	var v59 uint32
	var v64 uint32
	var v69 uint32
	v5 := x & 7
	v6 = 0
	for v8 = 0; v8 < 8; v8++ {
		v16 = s[int(uint64(4)*v8):]
		v6 = (v6 + uint64(binary.LittleEndian.Uint32(v16))) + (uint64(uint32(L[v8])) * uint64(v5))
		v26 = uint32(v6)
		v54 = v26 & 0xff
		v16[0] = byte(v54)
		v59 = (v26 >> 8) & 0xff
		v16[1] = byte(v59)
		v64 = (v26 >> 16) & 0xff
		v16[2] = byte(v64)
		v69 = (v26 >> 24) & 0xff
		v16[3] = byte(v69)
		v6 = uint64(v6 >> 32)
	}
}

func Crypto_x25519_dirty_fast(public_key []byte, secret_key []byte) {
	var v7 [32]byte
	var v8 Ge
	Crypto_eddsa_trim_scalar(v7[:], secret_key[:])
	Ge_scalarmult_base(&v8, v7[:])
	var v12 [10]int32
	var v13 [10]int32
	v15 := secret_key[0]
	select_lop(&v12, &Lop_x, &Sqrtm1, v15)
	select_lop(&v13, &Lop_y, &Fe_one, (v15 + 2))
	var v22 Ge_precomp
	fe_add(&v22.Yp, &v13, &v12)
	fe_sub(&v22.Ym, &v13, &v12)
	fe_mul(&v22.T2, &v13, &v12)
	fe_mul(&v22.T2, &v22.T2, &D2)
	ge_madd(&v8, &v8, &v22, &v12, &v13)
	fe_add(&v12, &v8.Z, &v8.Y)
	fe_sub(&v13, &v8.Z, &v8.Y)
	fe_invert(&v13, &v13)
	fe_mul(&v12, &v12, &v13)
	fe_tobytes(public_key[:], &v12)
	clear(v12[:])
	*&v8 = Ge{}
	runtime.KeepAlive(&v8)
	clear(v13[:])
	*&v22 = Ge_precomp{}
	runtime.KeepAlive(&v22)
	clear(v7[:])
}

func Crypto_elligator_map(curve []byte, hidden []byte) {
	var v7 [10]int32
	var v8 [10]int32
	var v9 [10]int32
	var v10 [10]int32
	var v11 [10]int32
	fe_frombytes_mask(&v7, hidden[:], uint32(2))
	fe_sq(&v7, &v7)
	fe_add(&v9, &v7, &v7)
	fe_add(&v8, &v9, &Fe_one)
	fe_sq(&v10, &v8)
	fe_mul(&v11, &A2, &v9)
	fe_sub(&v11, &v11, &v10)
	fe_mul(&v11, &v11, &A)
	fe_mul(&v9, &v10, &v8)
	fe_mul(&v9, &v11, &v9)
	v24 := Invsqrt(&v9, &v9)
	fe_mul(&v8, &v7, &Ufactor)
	fe_ccopy(&v8, &Fe_one, v24)
	fe_sq(&v9, &v9)
	fe_mul(&v8, &v8, &A)
	fe_mul(&v8, &v8, &v11)
	fe_mul(&v8, &v8, &v10)
	fe_mul(&v8, &v8, &v9)
	fe_neg(&v8, &v8)
	fe_tobytes(curve[:], &v8)
	clear(v9[:])
	clear(v7[:])
	clear(v10[:])
	clear(v8[:])
	clear(v11[:])
}

func Crypto_elligator_rev(hidden []byte, public_key []byte, tweak byte) int {
	var v17 byte
	var v23 int
	var v27 byte
	var v4 [10]int32
	var v5 [10]int32
	var v6 [10]int32
	fe_frombytes(&v4, public_key[:])
	fe_add(&v5, &v4, &A)
	fe_mul(&v6, &v4, &v5)
	fe_mul_small(&v6, &v6, -2)
	v15 := Invsqrt(&v6, &v6)
	if v15 != 0 {
		v17 = tweak & 1
		fe_ccopy(&v4, &v5, int(v17))
		fe_mul(&v6, &v4, &v6)
		fe_mul_small(&v4, &v6, 2)
		fe_neg(&v5, &v6)
		v23 = fe_isodd(&v4)
		fe_ccopy(&v6, &v5, v23)
		fe_tobytes(hidden[:], &v6)
		v27 = tweak & 0xc0
		hidden[31] |= v27
	}
	clear(v4[:])
	clear(v5[:])
	clear(v6[:])
	return (v15 - 1)
}

func redc(u []uint32, x []uint32) {
	_ = x[7]
	var v10 uint64
	var v12 uint64
	var v18 uint64
	var v32 uint64
	var v34 uint64
	var v4 [8]uint32
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 0); v12++ {
		v18 = 0 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[0]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 1); v12++ {
		v18 = 1 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[1]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 2); v12++ {
		v18 = 2 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[2]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 3); v12++ {
		v18 = 3 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[3]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 4); v12++ {
		v18 = 4 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[4]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 5); v12++ {
		v18 = 5 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[5]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 6); v12++ {
		v18 = 6 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[6]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	v10 = 0
	for v12 = 0; v12 < (uint64(8) - 7); v12++ {
		v18 = 7 + v12
		v10 += (uint64(v4[v18]) + (uint64(x[7]) * uint64(uint32(K[v12]))))
		v4[v18] = uint32(v10)
		v10 = uint64(v10 >> 32)
	}
	var v30 [16]uint32
	multiply(v30[:], v4[:], L[:])
	v32 = 0
	for v34 = 0; v34 < 16; v34++ {
		v32 += (uint64(v30[v34]) + uint64(x[v34]))
		v30[v34] = uint32(v32)
		v32 = uint64(v32 >> 32)
	}
	Remove_l(u[:], v30[8:])
	clear(v4[:])
	clear(v30[:])
}

func Crypto_x25519_inverse(blind_salt []byte, private_key []byte, curve_point []byte) {
	M_inv := [8]uint32{0x8d98951d, 0xd6ec3174, 0x737dcf70, 0xc6ef5bf4, 0xfffffffe, 0xffffffff, 0xffffffff, 0x0fffffff}

	var v26 int
	var v5 [32]byte
	Crypto_eddsa_trim_scalar(v5[:], private_key[:])
	var v7 [8]uint32
	var v8 [16]uint32
	clear(v8[:8])
	load32_le_buf(v8[8:], v5[:], uint64(8))
	Mod_l(v5[:], v8[:])
	load32_le_buf(v7[:], v5[:], uint64(8))
	clear(v8[:])
	var v25 [16]uint32
	v26 = 252
	for v26 >= 0 {
		clear(v25[:16])
		multiply(v25[:], M_inv[:], M_inv[:])
		redc(M_inv[:], v25[:])
		if scalar_bit(Lm2[:], v26) != 0 {
			clear(v25[:16])
			multiply(v25[:], M_inv[:], v7[:])
			redc(M_inv[:], v25[:])
		}
		v26--
	}
	v25[0] = uint32(M_inv[0])
	v25[1] = uint32(M_inv[1])
	v25[2] = uint32(M_inv[2])
	v25[3] = uint32(M_inv[3])
	v25[4] = uint32(M_inv[4])
	v25[5] = uint32(M_inv[5])
	v25[6] = uint32(M_inv[6])
	v25[7] = uint32(M_inv[7])
	clear(v25[8:16])
	redc(M_inv[:], v25[:])
	store32_le_buf(v5[:], M_inv[:], uint64(8))
	add_xl(v5[:], (v5[0] * 3))
	Scalarmult(blind_salt[:], v5[:], curve_point[:], 0x100)
	clear(v5[:])
	clear(v7[:])
	clear(v25[:])
	clear(M_inv[:])
}
