// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

func Scalar_bit(s []byte, i int) int {
	if i < 0 {
		return 0
	}
	return int((uint32(s[int(i>>3)]) >> uint8(i&7)) & 1)
}

func Crypto_x25519(raw_shared_secret []byte, your_secret_key []byte, their_public_key []byte) {
	var v3 [32]uint8
	Crypto_eddsa_trim_scalar(v3[:], your_secret_key)
	Scalarmult(raw_shared_secret, v3[:], their_public_key, 255)
	clear(v3[:])
}

func Crypto_x25519_public_key(public_key []byte, secret_key []byte) {
	Crypto_x25519(public_key, secret_key, crypto_x25519_public_key_base_point)
}

func Multiply(p []uint32, a []uint32, b []uint32) {
	var v3 uint64
	var v8 uint64
	var v10 uint64
	v3 = 0
	for v3 < 8 {
		v8 = 0
		v10 = 0
		for v10 < 8 {
			v15 := v3 + v10
			v8 += (uint64(p[v15]) + (uint64(a[v3]) * uint64(b[v10])))
			p[v15] = uint32(v8)
			v8 >>= 32
			v10++
		}
		p[v3+8] = uint32(v8)
		v3++
	}
}

func Crypto_x25519_to_eddsa(eddsa []byte, x25519 []byte) {
	var v3 [10]int32
	var v4 [10]int32
	Fe_frombytes(&v4, x25519)
	Fe_sub(&v3, &v4, &fe_one)
	Fe_add(&v4, &v4, &fe_one)
	Fe_invert(&v4, &v4)
	Fe_mul(&v3, &v3, &v4)
	Fe_tobytes(eddsa, &v3)
	clear(v3[:])
	clear(v4[:])
}

func Add_xl(s []byte, x uint8) {
	var v6 uint64
	var v8 uint64
	v6 = 0
	v8 = 0
	for v8 < 8 {
		v16 := s[int(uint64(4)*v8):]
		v6 = (v6 + uint64(Load32_le(v16))) + (uint64(L[v8]) * uint64(x&7))
		Store32_le(v16, uint32(v6))
		v6 >>= 32
		v8++
	}
}

func Crypto_x25519_dirty_fast(public_key []byte, secret_key []byte) {
	var v7 [32]uint8
	var v8 Ge
	Crypto_eddsa_trim_scalar(v7[:], secret_key)
	Ge_scalarmult_base(&v8, v7[:])
	var v12 [10]int32
	var v13 [10]int32
	v15 := secret_key[0]
	Select_lop(&v12, &lop_x, &sqrtm1, v15)
	Select_lop(&v13, &lop_y, &fe_one, (v15 + 2))
	var v22 Ge_precomp
	Fe_add(&v22.Yp, &v13, &v12)
	Fe_sub(&v22.Ym, &v13, &v12)
	Fe_mul(&v22.T2, &v13, &v12)
	Fe_mul(&v22.T2, &v22.T2, &D2)
	Ge_madd(&v8, &v8, &v22, &v12, &v13)
	Fe_add(&v12, &v8.Z, &v8.Y)
	Fe_sub(&v13, &v8.Z, &v8.Y)
	Fe_invert(&v13, &v13)
	Fe_mul(&v12, &v12, &v13)
	Fe_tobytes(public_key, &v12)
	clear(v12[:])
	clear(v13[:])
	clear(v7[:])
}

func Redc(u []uint32, x []uint32) {
	var v8 uint64
	var v13 uint64
	var v15 uint64
	var v35 uint64
	var v37 uint64
	var k = [8]uint32{0x12547e1b, 0xd2b51da3, 0xfdba84ff, 0xb1a206f2, 0xffa36bea, 0x14e75438, 0x6fe91836, 0x9db6c6f2}
	var v7 [8]uint32
	v8 = 0
	for v8 < 8 {
		v13 = 0
		v15 = 0
		for v15 < (uint64(8) - v8) {
			v21 := v8 + v15
			v13 += (uint64(v7[v21]) + (uint64(x[v8]) * uint64(k[v15])))
			v7[v21] = uint32(v13)
			v13 >>= 32
			v15++
		}
		v8++
	}
	var v33 [16]uint32
	Multiply(v33[:], v7[:], L)
	v35 = 0
	v37 = 0
	for v37 < 16 {
		v35 += (uint64(v33[v37]) + uint64(x[v37]))
		v33[v37] = uint32(v35)
		v35 >>= 32
		v37++
	}
	Remove_l(u, v33[8:])
	clear(v7[:])
	clear(v33[:])
}

func Crypto_x25519_inverse(blind_salt []byte, private_key []byte, curve_point []byte) {
	var m_inv = [8]uint32{0x8d98951d, 0xd6ec3174, 0x737dcf70, 0xc6ef5bf4, 0xfffffffe, 0xffffffff, 0xffffffff, 0xfffffff}
	var v7 [32]uint8
	Crypto_eddsa_trim_scalar(v7[:], private_key)
	var v9 [8]uint32
	var v10 [16]uint32
	clear(v10[:8])
	Load32_le_buf(v10[8:], v7[:], uint64(8))
	Mod_l(v7[:], v10[:])
	Load32_le_buf(v9[:], v7[:], uint64(8))
	clear(v10[:])
	var v27 [16]uint32
	// L-2 (ordre du groupe Ed25519 moins 2) est une constante publique.
	// Le test de bit sur cette table ne fuit aucune donnée secrète :
	// Montgomery ladder sur exposant public — le if est admissible.
	var lm2Bytes = [32]byte{
		0xeb, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
		0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
	}
	for bit := 252; bit >= 0; bit-- {
		clear(v27[:])
		Multiply(v27[:], m_inv[:], m_inv[:])
		Redc(m_inv[:], v27[:])
		if (lm2Bytes[bit/8]>>(bit%8))&1 != 0 {
			clear(v27[:])
			Multiply(v27[:], m_inv[:], v9[:])
			Redc(m_inv[:], v27[:])
		}
	}

	copy(v27[:8], m_inv[:8])
	clear(v27[8:16])
	Redc(m_inv[:], v27[:])
	Store32_le_buf(v7[:], m_inv[:], uint64(8))
	Add_xl(v7[:], (v7[0] * 3))
	Scalarmult(blind_salt, v7[:], curve_point, 0x100)
	clear(v7[:])
	clear(v9[:])
	clear(v27[:])
}
