// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ba09dfa37d5d7612e3dd9e745951e9a8083602b28c1fed3b2a3001893e767073
package monocypher55

import (
	"runtime"
)

func Crypto_eddsa_trim_scalar(out []byte, in []byte) {
	copy(out[:32], in[:32])
	v11 := out[0] & 0xf8
	out[0] = v11
	v16 := out[31] & 0x7f
	out[31] = v16
	out[31] |= 64
}

func Crypto_eddsa_reduce(reduced []byte, expanded []byte) {
	var v2 [16]uint32
	load32_le_buf(v2[:], expanded[:], uint64(16))
	Mod_l(reduced[:], v2[:])
	clear(v2[:])
}

func Crypto_eddsa_mul_add(r []byte, a []byte, b []byte, c []byte) {
	var v5 [8]uint32
	load32_le_buf(v5[:], a[:], uint64(8))
	var v8 [8]uint32
	load32_le_buf(v8[:], b[:], uint64(8))
	var v11 [16]uint32
	load32_le_buf(v11[:], c[:], uint64(8))
	clear(v11[8:16])
	multiply(v11[:], v5[:], v8[:])
	Mod_l(r[:], v11[:])
	clear(v11[:])
	clear(v5[:])
	clear(v8[:])
}

func Crypto_eddsa_scalarbase(point []byte, scalar []byte) {
	var v2 Ge
	Ge_scalarmult_base(&v2, scalar[:])
	ge_tobytes(point[:], &v2)
	*&v2 = Ge{}
	runtime.KeepAlive(&v2)
}

func Crypto_eddsa_key_pair(secret_key []byte, public_key []byte, seed []byte) {
	var v3 [64]byte
	copy(v3[:32], seed[:32])
	clear(seed[:])
	copy(secret_key[:32], v3[:32])
	Crypto_blake2b(v3[:], uint64(64), v3[:], uint64(32))
	Crypto_eddsa_trim_scalar(v3[:], v3[:])
	Crypto_eddsa_scalarbase(secret_key[32:], v3[:])
	copy(public_key[:32], secret_key[32:64])
	clear(v3[:])
}

func Crypto_eddsa_sign(signature []byte, secret_key []byte, message []byte, message_size uint64) {
	var v5 [64]byte
	var v6 [32]byte
	var v7 [32]byte
	var v8 [32]byte
	Crypto_blake2b(v5[:], uint64(64), secret_key[:], uint64(32))
	Crypto_eddsa_trim_scalar(v5[:], v5[:])
	hash_reduce(v6[:], v5[32:], uint64(32), message[:], message_size, nil, uint64(0))
	Crypto_eddsa_scalarbase(v8[:], v6[:])
	hash_reduce(v7[:], v8[:], uint64(32), secret_key[32:], uint64(32), message[:], message_size)
	copy(signature[:32], v8[:32])
	Crypto_eddsa_mul_add(signature[32:], v7[:], v5[:], v6[:])
	clear(v5[:])
	clear(v6[:])
}

func Crypto_eddsa_check(signature []byte, public_key []byte, message []byte, message_size uint64) int {
	var v4 [32]byte
	hash_reduce(v4[:], signature[:], uint64(32), public_key[:], uint64(32), message[:], message_size)
	return Crypto_eddsa_check_equation(signature, public_key[:], v4[:])
}

func Crypto_eddsa_to_x25519(x25519 []byte, eddsa []byte) {
	var v3 [10]int32
	var v4 [10]int32
	fe_frombytes(&v4, eddsa[:])
	fe_add(&v3, &Fe_one, &v4)
	fe_sub(&v4, &Fe_one, &v4)
	fe_invert(&v4, &v4)
	fe_mul(&v3, &v3, &v4)
	fe_tobytes(x25519[:], &v3)
	clear(v3[:])
	clear(v4[:])
}

func select_lop(out *[10]int32, x *[10]int32, k *[10]int32, cofactor byte) {
	var v4 [10]int32
	fe_0(out)
	v9 := (uint32(cofactor) >> 1) & 1
	fe_ccopy(out, k, int(v9))
	v14 := cofactor & 1
	fe_ccopy(out, x, int(v14))
	fe_neg(&v4, out)
	v20 := (uint32(cofactor) >> 2) & 1
	fe_ccopy(out, &v4, int(v20))
	clear(v4[:])
}
