// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

func Fe_0(h *[10]int32) {
	clear(h[:10])
}

func Fe_1(h *[10]int32) {
	h[0] = 1
	clear(h[1:10])
}

func Fe_copy(h *[10]int32, f *[10]int32) {
	copy(h[:10], f[:10])
}

func Fe_neg(h *[10]int32, f *[10]int32) {
	h[0] = int32(-int(f[0]))
	h[1] = int32(-int(f[1]))
	h[2] = int32(-int(f[2]))
	h[3] = int32(-int(f[3]))
	h[4] = int32(-int(f[4]))
	h[5] = int32(-int(f[5]))
	h[6] = int32(-int(f[6]))
	h[7] = int32(-int(f[7]))
	h[8] = int32(-int(f[8]))
	h[9] = int32(-int(f[9]))
}

func Fe_add(h *[10]int32, f *[10]int32, g *[10]int32) {
	h[0] = f[0] + g[0]
	h[1] = f[1] + g[1]
	h[2] = f[2] + g[2]
	h[3] = f[3] + g[3]
	h[4] = f[4] + g[4]
	h[5] = f[5] + g[5]
	h[6] = f[6] + g[6]
	h[7] = f[7] + g[7]
	h[8] = f[8] + g[8]
	h[9] = f[9] + g[9]
}

func Fe_sub(h *[10]int32, f *[10]int32, g *[10]int32) {
	h[0] = f[0] - g[0]
	h[1] = f[1] - g[1]
	h[2] = f[2] - g[2]
	h[3] = f[3] - g[3]
	h[4] = f[4] - g[4]
	h[5] = f[5] - g[5]
	h[6] = f[6] - g[6]
	h[7] = f[7] - g[7]
	h[8] = f[8] - g[8]
	h[9] = f[9] - g[9]
}

func Fe_cswap(f *[10]int32, g *[10]int32, b int) {
	var v6 uint64
	v6 = 0
	for v6 < 10 {
		v12 := f[v6]
		v13 := g[v6]
		v11 := int((v12 ^ v13) & int32(-b))
		f[v6] = v12 ^ int32(v11)
		g[v6] = v13 ^ int32(v11)
		v6++
	}
}

func Fe_ccopy(f *[10]int32, g *[10]int32, b int) {
	f[0] ^= int32(int((f[0] ^ g[0]) & int32(-b)))
	f[1] ^= int32(int((f[1] ^ g[1]) & int32(-b)))
	f[2] ^= int32(int((f[2] ^ g[2]) & int32(-b)))
	f[3] ^= int32(int((f[3] ^ g[3]) & int32(-b)))
	f[4] ^= int32(int((f[4] ^ g[4]) & int32(-b)))
	f[5] ^= int32(int((f[5] ^ g[5]) & int32(-b)))
	f[6] ^= int32(int((f[6] ^ g[6]) & int32(-b)))
	f[7] ^= int32(int((f[7] ^ g[7]) & int32(-b)))
	f[8] ^= int32(int((f[8] ^ g[8]) & int32(-b)))
	f[9] ^= int32(int((f[9] ^ g[9]) & int32(-b)))
}

func Fe_frombytes_mask(h *[10]int32, s []byte, nb_mask uint32) {
	var v6 int64
	var v8 int64
	var v15 int64
	var v22 int64
	var v29 int64
	var v36 int64
	var v41 int64
	var v48 int64
	var v55 int64
	var v62 int64
	var v70 int64
	v6 = int64(Load32_le(s))
	v8 = int64(Load24_le(s[4:]) << 6)
	v15 = int64(Load24_le(s[7:]) << 5)
	v22 = int64(Load24_le(s[10:]) << 3)
	v29 = int64(Load24_le(s[13:]) << 2)
	v36 = int64(Load32_le(s[16:]))
	v41 = int64(Load24_le(s[20:]) << 7)
	v48 = int64(Load24_le(s[23:]) << 5)
	v55 = int64(Load24_le(s[26:]) << 4)
	v62 = int64((Load24_le(s[29:]) & (0xffffff >> uint8(nb_mask))) << 2)
	v72 := int64(1)
	v74 := v72 << 25
	v70 = (v6 + v74) >> 26
	v81 := v72 << 26
	v6 -= (v70 * v81)
	v8 += v70
	v70 = (v29 + v74) >> 26
	v29 -= (v70 * v81)
	v36 += v70
	v102 := v72 << 24
	v70 = (v8 + v102) >> 25
	v8 -= (v70 * v74)
	v15 += v70
	v70 = (v36 + v102) >> 25
	v36 -= (v70 * v74)
	v41 += v70
	v70 = (v15 + v74) >> 26
	v15 -= (v70 * v81)
	v22 += v70
	v70 = (v41 + v74) >> 26
	v41 -= (v70 * v81)
	v48 += v70
	v70 = (v22 + v102) >> 25
	v22 -= (v70 * v74)
	v29 += v70
	v70 = (v48 + v102) >> 25
	v48 -= (v70 * v74)
	v55 += v70
	v70 = (v29 + v74) >> 26
	v29 -= (v70 * v81)
	v36 += v70
	v70 = (v55 + v74) >> 26
	v55 -= (v70 * v81)
	v62 += v70
	v70 = (v62 + v102) >> 25
	v62 -= (v70 * v74)
	v6 += (v70 * 19)
	v70 = (v6 + v74) >> 26
	v6 -= (v70 * v81)
	v8 += v70
	h[0] = int32(int(v6))
	h[1] = int32(int(v8))
	h[2] = int32(int(v15))
	h[3] = int32(int(v22))
	h[4] = int32(int(v29))
	h[5] = int32(int(v36))
	h[6] = int32(int(v41))
	h[7] = int32(int(v48))
	h[8] = int32(int(v55))
	h[9] = int32(int(v62))
}

func Fe_frombytes(h *[10]int32, s []byte) {
	Fe_frombytes_mask(h, s, uint32(1))
}

func Fe_tobytes(s []byte, h *[10]int32) {
	var v10 int
	var v22 uint64
	var v43 uint64
	var v3 [10]int
	v3[0] = int(h[0])
	v3[1] = int(h[1])
	v3[2] = int(h[2])
	v3[3] = int(h[3])
	v3[4] = int(h[4])
	v3[5] = int(h[5])
	v3[6] = int(h[6])
	v3[7] = int(h[7])
	v3[8] = int(h[8])
	v3[9] = int(h[9])
	v10 = ((19 * v3[9]) + (1 << 24)) >> 25
	v22 = 0
	for v22 < 5 {
		v28 := uint64(2) * v22
		v10 += v3[v28]
		v10 >>= 26
		v10 = v10 + v3[v28+1]
		v10 >>= 25
		v22++
	}
	v10 *= 19
	v43 = 0
	for v43 < 5 {
		v49 := v43 * 2
		v3[v49] += v10
		v56 := v3[v49]
		v10 = v56 >> 26
		v60 := 1
		v3[v49] = v56 - (v10 * (v60 << 26))
		v73 := v49 + 1
		v3[v73] += v10
		v84 := v3[v73]
		v10 = v84 >> 25
		v3[v73] = v84 - (v10 * (v60 << 25))
		v43++
	}
	v112 := uint32(v3[1])
	Store32_le(s, (uint32(v3[0]) | (v112 << 26)))
	v127 := uint32(v3[2])
	Store32_le(s[4:], ((v112 >> 6) | (v127 << 19)))
	v142 := uint32(v3[3])
	Store32_le(s[8:], ((v127 >> 13) | (v142 << 13)))
	Store32_le(s[12:], ((v142 >> 19) | (uint32(v3[4]) << 6)))
	v172 := uint32(v3[6])
	Store32_le(s[16:], (uint32(v3[5]) | (v172 << 25)))
	v187 := uint32(v3[7])
	Store32_le(s[20:], ((v172 >> 7) | (v187 << 19)))
	v202 := uint32(v3[8])
	Store32_le(s[24:], ((v187 >> 13) | (v202 << 12)))
	Store32_le(s[28:], ((v202 >> 20) | (uint32(v3[9]) << 6)))
	clear(v3[:])
}

func Fe_mul_small(h *[10]int32, f *[10]int32, g int) {
	var v3 int64
	var v8 int64
	var v13 int64
	var v18 int64
	var v23 int64
	var v28 int64
	var v33 int64
	var v38 int64
	var v43 int64
	var v48 int64
	var v53 int64
	v6 := int64(g)
	v3 = int64(f[0]) * v6
	v8 = int64(f[1]) * v6
	v13 = int64(f[2]) * v6
	v18 = int64(f[3]) * v6
	v23 = int64(f[4]) * v6
	v28 = int64(f[5]) * v6
	v33 = int64(f[6]) * v6
	v38 = int64(f[7]) * v6
	v43 = int64(f[8]) * v6
	v48 = int64(f[9]) * v6
	v55 := int64(1)
	v57 := v55 << 25
	v53 = (v3 + v57) >> 26
	v64 := v55 << 26
	v3 -= (v53 * v64)
	v8 += v53
	v53 = (v23 + v57) >> 26
	v23 -= (v53 * v64)
	v28 += v53
	v85 := v55 << 24
	v53 = (v8 + v85) >> 25
	v8 -= (v53 * v57)
	v13 += v53
	v53 = (v28 + v85) >> 25
	v28 -= (v53 * v57)
	v33 += v53
	v53 = (v13 + v57) >> 26
	v13 -= (v53 * v64)
	v18 += v53
	v53 = (v33 + v57) >> 26
	v33 -= (v53 * v64)
	v38 += v53
	v53 = (v18 + v85) >> 25
	v18 -= (v53 * v57)
	v23 += v53
	v53 = (v38 + v85) >> 25
	v38 -= (v53 * v57)
	v43 += v53
	v53 = (v23 + v57) >> 26
	v23 -= (v53 * v64)
	v28 += v53
	v53 = (v43 + v57) >> 26
	v43 -= (v53 * v64)
	v48 += v53
	v53 = (v48 + v85) >> 25
	v48 -= (v53 * v57)
	v3 += (v53 * 19)
	v53 = (v3 + v57) >> 26
	v3 -= (v53 * v64)
	v8 += v53
	h[0] = int32(int(v3))
	h[1] = int32(int(v8))
	h[2] = int32(int(v13))
	h[3] = int32(int(v18))
	h[4] = int32(int(v23))
	h[5] = int32(int(v28))
	h[6] = int32(int(v33))
	h[7] = int32(int(v38))
	h[8] = int32(int(v43))
	h[9] = int32(int(v48))
}

func Fe_mul(h *[10]int32, f *[10]int32, g *[10]int32) {
	var v105 int64
	var v135 int64
	var v165 int64
	var v195 int64
	var v225 int64
	var v255 int64
	var v285 int64
	var v315 int64
	var v345 int64
	var v375 int64
	var v405 int64
	v3 := int(f[0])
	v6 := int(f[1])
	v9 := int(f[2])
	v12 := int(f[3])
	v15 := int(f[4])
	v18 := int(f[5])
	v21 := int(f[6])
	v24 := int(f[7])
	v27 := int(f[8])
	v30 := int(f[9])
	v36 := int(g[1])
	v39 := int(g[2])
	v42 := int(g[3])
	v45 := int(g[4])
	v48 := int(g[5])
	v51 := int(g[6])
	v54 := int(g[7])
	v57 := int(g[8])
	v60 := int(g[9])
	v65 := v6 * 2
	v68 := v12 * 2
	v71 := v18 * 2
	v74 := v24 * 2
	v77 := v30 * 2
	v106 := int64(int(g[0]))
	v108 := int64(v60 * 19)
	v111 := int64(v57 * 19)
	v114 := int64(v54 * 19)
	v117 := int64(v51 * 19)
	v120 := int64(v48 * 19)
	v123 := int64(v45 * 19)
	v126 := int64(v42 * 19)
	v129 := int64(v39 * 19)
	v105 = ((int64(v3)*v106 + int64(v65)*v108) + ((int64(v9) * v111) + (int64(v68)*v114 + int64(v15)*v117))) + ((int64(v71)*v120 + int64(v21)*v123) + ((int64(v74) * v126) + (int64(v27)*v129 + int64(v77)*int64(v36*19))))
	v136 := int64(v36)
	v135 = ((int64(v3)*v136 + int64(v6)*v106) + ((int64(v9) * v108) + (int64(v12)*v111 + int64(v15)*v114))) + ((int64(v18)*v117 + int64(v21)*v120) + ((int64(v24) * v123) + (int64(v27)*v126 + int64(v30)*v129)))
	v166 := int64(v39)
	v165 = ((int64(v3)*v166 + int64(v65)*v136) + ((int64(v9) * v106) + (int64(v68)*v108 + int64(v15)*v111))) + ((int64(v71)*v114 + int64(v21)*v117) + ((int64(v74) * v120) + (int64(v27)*v123 + int64(v77)*v126)))
	v196 := int64(v42)
	v195 = ((int64(v3)*v196 + int64(v6)*v166) + ((int64(v9) * v136) + (int64(v12)*v106 + int64(v15)*v108))) + ((int64(v18)*v111 + int64(v21)*v114) + ((int64(v24) * v117) + (int64(v27)*v120 + int64(v30)*v123)))
	v226 := int64(v45)
	v225 = ((int64(v3)*v226 + int64(v65)*v196) + ((int64(v9) * v166) + (int64(v68)*v136 + int64(v15)*v106))) + ((int64(v71)*v108 + int64(v21)*v111) + ((int64(v74) * v114) + (int64(v27)*v117 + int64(v77)*v120)))
	v256 := int64(v48)
	v255 = ((int64(v3)*v256 + int64(v6)*v226) + ((int64(v9) * v196) + (int64(v12)*v166 + int64(v15)*v136))) + ((int64(v18)*v106 + int64(v21)*v108) + ((int64(v24) * v111) + (int64(v27)*v114 + int64(v30)*v117)))
	v286 := int64(v51)
	v285 = ((int64(v3)*v286 + int64(v65)*v256) + ((int64(v9) * v226) + (int64(v68)*v196 + int64(v15)*v166))) + ((int64(v71)*v136 + int64(v21)*v106) + ((int64(v74) * v108) + (int64(v27)*v111 + int64(v77)*v114)))
	v316 := int64(v54)
	v315 = ((int64(v3)*v316 + int64(v6)*v286) + ((int64(v9) * v256) + (int64(v12)*v226 + int64(v15)*v196))) + ((int64(v18)*v166 + int64(v21)*v136) + ((int64(v24) * v106) + (int64(v27)*v108 + int64(v30)*v111)))
	v346 := int64(v57)
	v345 = ((int64(v3)*v346 + int64(v65)*v316) + ((int64(v9) * v286) + (int64(v68)*v256 + int64(v15)*v226))) + ((int64(v71)*v196 + int64(v21)*v166) + ((int64(v74) * v136) + (int64(v27)*v106 + int64(v77)*v108)))
	v375 = ((int64(v3)*int64(v60) + int64(v6)*v346) + ((int64(v9) * v316) + (int64(v12)*v286 + int64(v15)*v256))) + ((int64(v18)*v226 + int64(v21)*v196) + ((int64(v24) * v166) + (int64(v27)*v136 + int64(v30)*v106)))
	v407 := int64(1)
	v409 := v407 << 25
	v405 = (v105 + v409) >> 26
	v416 := v407 << 26
	v105 -= (v405 * v416)
	v135 += v405
	v405 = (v225 + v409) >> 26
	v225 -= (v405 * v416)
	v255 += v405
	v437 := v407 << 24
	v405 = (v135 + v437) >> 25
	v135 -= (v405 * v409)
	v165 += v405
	v405 = (v255 + v437) >> 25
	v255 -= (v405 * v409)
	v285 += v405
	v405 = (v165 + v409) >> 26
	v165 -= (v405 * v416)
	v195 += v405
	v405 = (v285 + v409) >> 26
	v285 -= (v405 * v416)
	v315 += v405
	v405 = (v195 + v437) >> 25
	v195 -= (v405 * v409)
	v225 += v405
	v405 = (v315 + v437) >> 25
	v315 -= (v405 * v409)
	v345 += v405
	v405 = (v225 + v409) >> 26
	v225 -= (v405 * v416)
	v255 += v405
	v405 = (v345 + v409) >> 26
	v345 -= (v405 * v416)
	v375 += v405
	v405 = (v375 + v437) >> 25
	v375 -= (v405 * v409)
	v105 += (v405 * 19)
	v405 = (v105 + v409) >> 26
	v105 -= (v405 * v416)
	v135 += v405
	h[0] = int32(int(v105))
	h[1] = int32(int(v135))
	h[2] = int32(int(v165))
	h[3] = int32(int(v195))
	h[4] = int32(int(v225))
	h[5] = int32(int(v255))
	h[6] = int32(int(v285))
	h[7] = int32(int(v315))
	h[8] = int32(int(v345))
	h[9] = int32(int(v375))
}

func Fe_sq(h *[10]int32, f *[10]int32) {
	var v71 int64
	var v89 int64
	var v104 int64
	var v122 int64
	var v137 int64
	var v155 int64
	var v170 int64
	var v188 int64
	var v203 int64
	var v221 int64
	var v236 int64
	v2 := int(f[0])
	v5 := int(f[1])
	v8 := int(f[2])
	v11 := int(f[3])
	v14 := int(f[4])
	v17 := int(f[5])
	v20 := int(f[6])
	v23 := int(f[7])
	v26 := int(f[8])
	v29 := int(f[9])
	v34 := v2 * 2
	v37 := v5 * 2
	v40 := v8 * 2
	v43 := v11 * 2
	v46 := v14 * 2
	v49 := v17 * 2
	v55 := v23 * 2
	v74 := int64(v29 * 38)
	v77 := int64(v26 * 19)
	v80 := int64(v23 * 38)
	v83 := int64(v20 * 19)
	v71 = ((int64(v2) * int64(v2)) + (int64(v37)*v74 + int64(v40)*v77)) + ((int64(v43) * v80) + (int64(v46)*v83 + int64(v17)*int64(v17*38)))
	v90 := int64(v5)
	v89 = (int64(v34)*v90 + int64(v8)*v74) + ((int64(v43) * v77) + (int64(v14)*v80 + int64(v49)*v83))
	v105 := int64(v8)
	v104 = ((int64(v34) * v105) + (int64(v37)*v90 + int64(v43)*v74)) + ((int64(v46) * v77) + (int64(v49)*v80 + int64(v20)*v83))
	v123 := int64(v11)
	v122 = (int64(v34)*v123 + int64(v37)*v105) + ((int64(v14) * v74) + (int64(v49)*v77 + int64(v20)*v80))
	v138 := int64(v14)
	v137 = ((int64(v34) * v138) + (int64(v37)*int64(v43) + int64(v8)*v105)) + ((int64(v49) * v74) + (int64(v20*2)*v77 + int64(v23)*v80))
	v156 := int64(v17)
	v155 = (int64(v34)*v156 + int64(v37)*v138) + ((int64(v40) * v123) + (int64(v20)*v74 + int64(v55)*v77))
	v171 := int64(v20)
	v173 := int64(v49)
	v170 = ((int64(v34) * v171) + (int64(v37)*v173 + int64(v40)*v138)) + ((int64(v43) * v123) + (int64(v55)*v74 + int64(v26)*v77))
	v189 := int64(v23)
	v188 = (int64(v34)*v189 + int64(v37)*v171) + ((int64(v40) * v156) + (int64(v43)*v138 + int64(v26)*v74))
	v204 := int64(v26)
	v203 = ((int64(v34) * v204) + (int64(v37)*int64(v55) + int64(v40)*v171)) + ((int64(v43) * v173) + (int64(v14)*v138 + int64(v29)*v74))
	v221 = (int64(v34)*int64(v29) + int64(v37)*v204) + ((int64(v40) * v189) + (int64(v43)*v171 + int64(v14)*v173))
	v238 := int64(1)
	v240 := v238 << 25
	v236 = (v71 + v240) >> 26
	v247 := v238 << 26
	v71 -= (v236 * v247)
	v89 += v236
	v236 = (v137 + v240) >> 26
	v137 -= (v236 * v247)
	v155 += v236
	v268 := v238 << 24
	v236 = (v89 + v268) >> 25
	v89 -= (v236 * v240)
	v104 += v236
	v236 = (v155 + v268) >> 25
	v155 -= (v236 * v240)
	v170 += v236
	v236 = (v104 + v240) >> 26
	v104 -= (v236 * v247)
	v122 += v236
	v236 = (v170 + v240) >> 26
	v170 -= (v236 * v247)
	v188 += v236
	v236 = (v122 + v268) >> 25
	v122 -= (v236 * v240)
	v137 += v236
	v236 = (v188 + v268) >> 25
	v188 -= (v236 * v240)
	v203 += v236
	v236 = (v137 + v240) >> 26
	v137 -= (v236 * v247)
	v155 += v236
	v236 = (v203 + v240) >> 26
	v203 -= (v236 * v247)
	v221 += v236
	v236 = (v221 + v268) >> 25
	v221 -= (v236 * v240)
	v71 += (v236 * 19)
	v236 = (v71 + v240) >> 26
	v71 -= (v236 * v247)
	v89 += v236
	h[0] = int32(int(v71))
	h[1] = int32(int(v89))
	h[2] = int32(int(v104))
	h[3] = int32(int(v122))
	h[4] = int32(int(v137))
	h[5] = int32(int(v155))
	h[6] = int32(int(v170))
	h[7] = int32(int(v188))
	h[8] = int32(int(v203))
	h[9] = int32(int(v221))
}

func Fe_isodd(f *[10]int32) int {
	var v2 [32]uint8
	Fe_tobytes(v2[:], f)
	v8 := v2[0] & 1
	clear(v2[:])
	return int(v8)
}

func Fe_isequal(f *[10]int32, g *[10]int32) int {
	var v2 [32]uint8
	var v3 [32]uint8
	Fe_tobytes(v2[:], f)
	Fe_tobytes(v3[:], g)
	v7 := Crypto_verify32(v2[:], v3[:])
	clear(v2[:])
	clear(v3[:])
	return (1 + v7)
}

func Fe_invert(out *[10]int32, x *[10]int32) {
	var v2 [10]int32
	Fe_sq(&v2, x)
	Invsqrt(&v2, &v2)
	Fe_sq(&v2, &v2)
	Fe_mul(out, &v2, x)
	clear(v2[:])
}
