// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

func Ge_zero(p *Ge) {
	Fe_0(&p.X)
	Fe_1(&p.Y)
	Fe_1(&p.Z)
	Fe_0(&p.T)
}

func Ge_tobytes(s []byte, h *Ge) {
	var v2 [10]int32
	var v3 [10]int32
	var v4 [10]int32
	Fe_invert(&v2, &h.Z)
	Fe_mul(&v3, &h.X, &v2)
	Fe_mul(&v4, &h.Y, &v2)
	Fe_tobytes(s, &v4)
	s[31] ^= uint8(Fe_isodd(&v3) << 7)
	clear(v2[:])
	clear(v3[:])
	clear(v4[:])
}

func Ge_frombytes_neg_vartime(h *Ge, s []byte) int {
	Fe_frombytes(&h.Y, s)
	Fe_1(&h.Z)
	Fe_sq(&h.T, &h.Y)
	Fe_mul(&h.X, &h.T, &d)
	Fe_sub(&h.T, &h.T, &h.Z)
	Fe_add(&h.X, &h.X, &h.Z)
	Fe_mul(&h.X, &h.T, &h.X)
	if Invsqrt(&h.X, &h.X) == 0 {
		return -1
	}
	Fe_mul(&h.X, &h.T, &h.X)
	if uint32(Fe_isodd(&h.X)) == (uint32(s[31]) >> 7) {
		Fe_neg(&h.X, &h.X)
	}
	Fe_mul(&h.T, &h.X, &h.Y)
	return 0
}

func Ge_cache(c *Ge_cached, p *Ge) {
	Fe_add(&c.Yp, &p.Y, &p.X)
	Fe_sub(&c.Ym, &p.Y, &p.X)
	Fe_copy(&c.Z, &p.Z)
	Fe_mul(&c.T2, &p.T, &D2)
}

func Ge_add(s *Ge, p *Ge, q *Ge_cached) {
	var v3 [10]int32
	var v4 [10]int32
	Fe_add(&v3, &p.Y, &p.X)
	Fe_sub(&v4, &p.Y, &p.X)
	Fe_mul(&v3, &v3, &q.Yp)
	Fe_mul(&v4, &v4, &q.Ym)
	Fe_add(&s.Y, &v3, &v4)
	Fe_sub(&s.X, &v3, &v4)
	Fe_add(&s.Z, &p.Z, &p.Z)
	Fe_mul(&s.Z, &s.Z, &q.Z)
	Fe_mul(&s.T, &p.T, &q.T2)
	Fe_add(&v3, &s.Z, &s.T)
	Fe_sub(&v4, &s.Z, &s.T)
	Fe_mul(&s.T, &s.X, &s.Y)
	Fe_mul(&s.X, &s.X, &v4)
	Fe_mul(&s.Y, &s.Y, &v3)
	Fe_mul(&s.Z, &v3, &v4)
}

func Ge_sub(s *Ge, p *Ge, q *Ge_cached) {
	var v3 Ge_cached
	Fe_copy(&v3.Ym, &q.Yp)
	Fe_copy(&v3.Yp, &q.Ym)
	Fe_copy(&v3.Z, &q.Z)
	Fe_neg(&v3.T2, &q.T2)
	Ge_add(s, p, &v3)
}

func Ge_madd(s *Ge, p *Ge, q *Ge_precomp, a *[10]int32, b *[10]int32) {
	Fe_add(a, &p.Y, &p.X)
	Fe_sub(b, &p.Y, &p.X)
	Fe_mul(a, a, &q.Yp)
	Fe_mul(b, b, &q.Ym)
	Fe_add(&s.Y, a, b)
	Fe_sub(&s.X, a, b)
	Fe_add(&s.Z, &p.Z, &p.Z)
	Fe_mul(&s.T, &p.T, &q.T2)
	Fe_add(a, &s.Z, &s.T)
	Fe_sub(b, &s.Z, &s.T)
	Fe_mul(&s.T, &s.X, &s.Y)
	Fe_mul(&s.X, &s.X, b)
	Fe_mul(&s.Y, &s.Y, a)
	Fe_mul(&s.Z, a, b)
}

func Ge_msub(s *Ge, p *Ge, q *Ge_precomp, a *[10]int32, b *[10]int32) {
	var v5 Ge_precomp
	Fe_copy(&v5.Ym, &q.Yp)
	Fe_copy(&v5.Yp, &q.Ym)
	Fe_neg(&v5.T2, &q.T2)
	Ge_madd(s, p, &v5, a, b)
}

func Ge_double(s *Ge, p *Ge, q *Ge) {
	Fe_sq(&q.X, &p.X)
	Fe_sq(&q.Y, &p.Y)
	Fe_sq(&q.Z, &p.Z)
	Fe_mul_small(&q.Z, &q.Z, 2)
	Fe_add(&q.T, &p.X, &p.Y)
	Fe_sq(&s.T, &q.T)
	Fe_add(&q.T, &q.Y, &q.X)
	Fe_sub(&q.Y, &q.Y, &q.X)
	Fe_sub(&q.X, &s.T, &q.T)
	Fe_sub(&q.Z, &q.Z, &q.Y)
	Fe_mul(&s.X, &q.X, &q.Z)
	Fe_mul(&s.Y, &q.T, &q.Y)
	Fe_mul(&s.Z, &q.Y, &q.Z)
	Fe_mul(&s.T, &q.X, &q.T)
}
