// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=c9b32960cbf97ea18de19c5c8c6667b26cfc01b4f430b8722a63b0181ede4a21
package monocypher55

func ge_zero(p *Ge) {
	fe_0(&p.X)
	fe_1(&p.Y)
	fe_1(&p.Z)
	fe_0(&p.T)
}

func ge_tobytes(s []byte, h *Ge) {
	var v2 [10]int32
	var v3 [10]int32
	var v4 [10]int32
	fe_invert(&v2, &h.Z)
	fe_mul(&v3, &h.X, &v2)
	fe_mul(&v4, &h.Y, &v2)
	fe_tobytes(s[:], &v4)
	v12 := fe_isodd(&v3)
	s[31] ^= byte(v12 << 7)
	clear(v2[:])
	clear(v3[:])
	clear(v4[:])
}

func ge_frombytes_neg_vartime(h *Ge, s []byte) int {
	fe_frombytes(&h.Y, s[:])
	fe_1(&h.Z)
	fe_sq(&h.T, &h.Y)
	fe_mul(&h.X, &h.T, &D)
	fe_sub(&h.T, &h.T, &h.Z)
	fe_add(&h.X, &h.X, &h.Z)
	fe_mul(&h.X, &h.T, &h.X)
	v28 := Invsqrt(&h.X, &h.X)
	if v28 == 0 {
		return -1
	}
	fe_mul(&h.X, &h.T, &h.X)
	v39 := fe_isodd(&h.X)
	if uint32(v39) == (uint32(s[31]) >> 7) {
		fe_neg(&h.X, &h.X)
	}
	fe_mul(&h.T, &h.X, &h.Y)
	return 0
}

func ge_cache(c *Ge_cached, p *Ge) {
	fe_add(&c.Yp, &p.Y, &p.X)
	fe_sub(&c.Ym, &p.Y, &p.X)
	fe_copy(&c.Z, &p.Z)
	fe_mul(&c.T2, &p.T, &D2)
}

func ge_add(s *Ge, p *Ge, q *Ge_cached) {
	var v3 [10]int32
	var v4 [10]int32
	fe_add(&v3, &p.Y, &p.X)
	fe_sub(&v4, &p.Y, &p.X)
	fe_mul(&v3, &v3, &q.Yp)
	fe_mul(&v4, &v4, &q.Ym)
	fe_add(&s.Y, &v3, &v4)
	fe_sub(&s.X, &v3, &v4)
	fe_add(&s.Z, &p.Z, &p.Z)
	fe_mul(&s.Z, &s.Z, &q.Z)
	fe_mul(&s.T, &p.T, &q.T2)
	fe_add(&v3, &s.Z, &s.T)
	fe_sub(&v4, &s.Z, &s.T)
	fe_mul(&s.T, &s.X, &s.Y)
	fe_mul(&s.X, &s.X, &v4)
	fe_mul(&s.Y, &s.Y, &v3)
	fe_mul(&s.Z, &v3, &v4)
}

func ge_sub(s *Ge, p *Ge, q *Ge_cached) {
	var v3 Ge_cached
	fe_copy(&v3.Ym, &q.Yp)
	fe_copy(&v3.Yp, &q.Ym)
	fe_copy(&v3.Z, &q.Z)
	fe_neg(&v3.T2, &q.T2)
	ge_add(s, p, &v3)
}

func ge_madd(s *Ge, p *Ge, q *Ge_precomp, a *[10]int32, b *[10]int32) {
	fe_add(a, &p.Y, &p.X)
	fe_sub(b, &p.Y, &p.X)
	fe_mul(a, a, &q.Yp)
	fe_mul(b, b, &q.Ym)
	fe_add(&s.Y, a, b)
	fe_sub(&s.X, a, b)
	fe_add(&s.Z, &p.Z, &p.Z)
	fe_mul(&s.T, &p.T, &q.T2)
	fe_add(a, &s.Z, &s.T)
	fe_sub(b, &s.Z, &s.T)
	fe_mul(&s.T, &s.X, &s.Y)
	fe_mul(&s.X, &s.X, b)
	fe_mul(&s.Y, &s.Y, a)
	fe_mul(&s.Z, a, b)
}

func ge_msub(s *Ge, p *Ge, q *Ge_precomp, a *[10]int32, b *[10]int32) {
	var v5 Ge_precomp
	fe_copy(&v5.Ym, &q.Yp)
	fe_copy(&v5.Yp, &q.Ym)
	fe_neg(&v5.T2, &q.T2)
	ge_madd(s, p, &v5, a, b)
}

func ge_double(s *Ge, p *Ge, q *Ge) {
	fe_sq(&q.X, &p.X)
	fe_sq(&q.Y, &p.Y)
	fe_sq(&q.Z, &p.Z)
	fe_mul_small(&q.Z, &q.Z, 2)
	fe_add(&q.T, &p.X, &p.Y)
	fe_sq(&s.T, &q.T)
	fe_add(&q.T, &q.Y, &q.X)
	fe_sub(&q.Y, &q.Y, &q.X)
	fe_sub(&q.X, &s.T, &q.T)
	fe_sub(&q.Z, &q.Z, &q.Y)
	fe_mul(&s.X, &q.X, &q.Z)
	fe_mul(&s.Y, &q.T, &q.Y)
	fe_mul(&s.Z, &q.Y, &q.Z)
	fe_mul(&s.T, &q.X, &q.T)
}
