// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

import (
	"encoding/binary"
	"math/bits"
)

func Gap(x uint64, pow_2 uint64) uint64 {
	return uint64((^x + 1) & (pow_2 - 1))
}

func Load24_le(s []byte) uint32 {
	return uint32((uint32(s[0]) | (uint32(s[1]) << 8)) | (uint32(s[2]) << 16))
}

func Load32_le(s []byte) uint32 {
	return binary.LittleEndian.Uint32(s)
}

func Load64_le(s []byte) uint64 {
	return binary.LittleEndian.Uint64(s)
}

func Store32_le(out []byte, in uint32) {
	binary.LittleEndian.PutUint32(out, in)
}

func Store64_le(out []byte, in uint64) {
	binary.LittleEndian.PutUint64(out, in)
}

func Load32_le_buf(dst []uint32, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[v3] = Load32_le(src[int(v3*4):])
		v3++
	}
}

func Load64_le_buf(dst []uint64, src []byte, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		dst[v3] = Load64_le(src[int(v3*8):])
		v3++
	}
}

func Store32_le_buf(dst []byte, src []uint32, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store32_le(dst[int(v3*4):], src[v3])
		v3++
	}
}

func Store64_le_buf(dst []byte, src []uint64, size uint64) {
	var v3 uint64
	v3 = 0
	for v3 < size {
		Store64_le(dst[int(v3*8):], src[v3])
		v3++
	}
}

func Rotl32(x uint32, n uint32) uint32 {
	return uint32(bits.RotateLeft32(x, int(n)))
}

func Neq0(diff uint64) int {
	return int((uint64(1) & ((((diff >> 32) | uint64(uint32(diff))) - 1) >> 32)) - 1)
}

func X16(a []byte, b []byte) uint64 {
	return uint64((Load64_le(a) ^ Load64_le(b)) | (Load64_le(a[8:]) ^ Load64_le(b[8:])))
}

func X32(a []byte, b []byte) uint64 {
	return uint64(X16(a, b) | X16(a[16:], b[16:]))
}

func X64(a []byte, b []byte) uint64 {
	return uint64(X32(a, b) | X32(a[32:], b[32:]))
}

func Crypto_verify16(a []byte, b []byte) int {
	return Neq0(X16(a, b))
}

func Crypto_verify32(a []byte, b []byte) int {
	return Neq0(X32(a, b))
}

func Crypto_verify64(a []byte, b []byte) int {
	return Neq0(X64(a, b))
}

func Crypto_wipe(secret []byte, size uint64) {
	clear(secret[:size])
}

func Copy_block(o *Blk, in *Blk) {
	copy(o.A[:0x80], in.A[:0x80])
}

func Xor_block(o *Blk, in *Blk) {
	var v2 uint64
	v2 = 0
	for v2 < 0x80 {
		o.A[v2] ^= in.A[v2]
		v2++
	}
}

func G_rounds(b *Blk) {
	var v1 int
	var v1542 int
	v1 = 0
	for v1 < 128 {
		v8 := v1 + 4
		b.A[v1] += (b.A[v8] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8]))) << 1))
		v32 := v1 + 12
		b.A[v32] ^= b.A[v1]
		b.A[v32] = bits.RotateLeft64(b.A[v32], -32)
		v53 := v1 + 8
		b.A[v53] += (b.A[v32] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = bits.RotateLeft64(b.A[v8], -24)
		b.A[v1] += (b.A[v8] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v32] ^= b.A[v1]
		b.A[v32] = bits.RotateLeft64(b.A[v32], -16)
		b.A[v53] += (b.A[v32] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = bits.RotateLeft64(b.A[v8], -63)
		v188 := v1 + 5
		v192 := v1 + 1
		b.A[v192] += (b.A[v188] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188]))) << 1))
		v220 := v1 + 13
		b.A[v220] ^= b.A[v192]
		b.A[v220] = bits.RotateLeft64(b.A[v220], -32)
		v241 := v1 + 9
		b.A[v241] += (b.A[v220] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = bits.RotateLeft64(b.A[v188], -24)
		b.A[v192] += (b.A[v188] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v220] ^= b.A[v192]
		b.A[v220] = bits.RotateLeft64(b.A[v220], -16)
		b.A[v241] += (b.A[v220] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = bits.RotateLeft64(b.A[v188], -63)
		v384 := v1 + 6
		v388 := v1 + 2
		b.A[v388] += (b.A[v384] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384]))) << 1))
		v416 := v1 + 14
		b.A[v416] ^= b.A[v388]
		b.A[v416] = bits.RotateLeft64(b.A[v416], -32)
		v437 := v1 + 10
		b.A[v437] += (b.A[v416] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = bits.RotateLeft64(b.A[v384], -24)
		b.A[v388] += (b.A[v384] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v416] ^= b.A[v388]
		b.A[v416] = bits.RotateLeft64(b.A[v416], -16)
		b.A[v437] += (b.A[v416] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = bits.RotateLeft64(b.A[v384], -63)
		v580 := v1 + 7
		v584 := v1 + 3
		b.A[v584] += (b.A[v580] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580]))) << 1))
		v612 := v1 + 15
		b.A[v612] ^= b.A[v584]
		b.A[v612] = bits.RotateLeft64(b.A[v612], -32)
		v633 := v1 + 11
		b.A[v633] += (b.A[v612] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = bits.RotateLeft64(b.A[v580], -24)
		b.A[v584] += (b.A[v580] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v612] ^= b.A[v584]
		b.A[v612] = bits.RotateLeft64(b.A[v612], -16)
		b.A[v633] += (b.A[v612] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = bits.RotateLeft64(b.A[v580], -63)
		b.A[v1] += (b.A[v188] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = bits.RotateLeft64(b.A[v612], -32)
		b.A[v437] += (b.A[v612] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = bits.RotateLeft64(b.A[v188], -24)
		b.A[v1] += (b.A[v188] + ((uint64(uint32(b.A[v1])) * uint64(uint32(b.A[v188]))) << 1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = bits.RotateLeft64(b.A[v612], -16)
		b.A[v437] += (b.A[v612] + ((uint64(uint32(b.A[v437])) * uint64(uint32(b.A[v612]))) << 1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = bits.RotateLeft64(b.A[v188], -63)
		b.A[v192] += (b.A[v384] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = bits.RotateLeft64(b.A[v32], -32)
		b.A[v633] += (b.A[v32] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = bits.RotateLeft64(b.A[v384], -24)
		b.A[v192] += (b.A[v384] + ((uint64(uint32(b.A[v192])) * uint64(uint32(b.A[v384]))) << 1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = bits.RotateLeft64(b.A[v32], -16)
		b.A[v633] += (b.A[v32] + ((uint64(uint32(b.A[v633])) * uint64(uint32(b.A[v32]))) << 1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = bits.RotateLeft64(b.A[v384], -63)
		b.A[v388] += (b.A[v580] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = bits.RotateLeft64(b.A[v220], -32)
		b.A[v53] += (b.A[v220] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = bits.RotateLeft64(b.A[v580], -24)
		b.A[v388] += (b.A[v580] + ((uint64(uint32(b.A[v388])) * uint64(uint32(b.A[v580]))) << 1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = bits.RotateLeft64(b.A[v220], -16)
		b.A[v53] += (b.A[v220] + ((uint64(uint32(b.A[v53])) * uint64(uint32(b.A[v220]))) << 1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = bits.RotateLeft64(b.A[v580], -63)
		b.A[v584] += (b.A[v8] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = bits.RotateLeft64(b.A[v416], -32)
		b.A[v241] += (b.A[v416] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = bits.RotateLeft64(b.A[v8], -24)
		b.A[v584] += (b.A[v8] + ((uint64(uint32(b.A[v584])) * uint64(uint32(b.A[v8]))) << 1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = bits.RotateLeft64(b.A[v416], -16)
		b.A[v241] += (b.A[v416] + ((uint64(uint32(b.A[v241])) * uint64(uint32(b.A[v416]))) << 1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = bits.RotateLeft64(b.A[v8], -63)
		v1 += 16
	}
	v1542 = 0
	for v1542 < 16 {
		v1549 := v1542 + 32
		b.A[v1542] += (b.A[v1549] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549]))) << 1))
		v1573 := v1542 + 96
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], -32)
		v1594 := v1542 + 64
		b.A[v1594] += (b.A[v1573] + ((uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573]))) << 1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = bits.RotateLeft64(b.A[v1549], -24)
		b.A[v1542] += (b.A[v1549] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1549]))) << 1))
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], -16)
		b.A[v1594] += (b.A[v1573] + ((uint64(uint32(b.A[v1594])) * uint64(uint32(b.A[v1573]))) << 1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = bits.RotateLeft64(b.A[v1549], -63)
		v1729 := v1542 + 33
		v1733 := v1542 + 1
		b.A[v1733] += (b.A[v1729] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729]))) << 1))
		v1761 := v1542 + 97
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = bits.RotateLeft64(b.A[v1761], -32)
		v1782 := v1542 + 65
		b.A[v1782] += (b.A[v1761] + ((uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761]))) << 1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], -24)
		b.A[v1733] += (b.A[v1729] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = bits.RotateLeft64(b.A[v1761], -16)
		b.A[v1782] += (b.A[v1761] + ((uint64(uint32(b.A[v1782])) * uint64(uint32(b.A[v1761]))) << 1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], -63)
		v1925 := v1542 + 48
		v1929 := v1542 + 16
		b.A[v1929] += (b.A[v1925] + ((uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925]))) << 1))
		v1957 := v1542 + 112
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = bits.RotateLeft64(b.A[v1957], -32)
		v1978 := v1542 + 80
		b.A[v1978] += (b.A[v1957] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957]))) << 1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = bits.RotateLeft64(b.A[v1925], -24)
		b.A[v1929] += (b.A[v1925] + ((uint64(uint32(b.A[v1929])) * uint64(uint32(b.A[v1925]))) << 1))
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = bits.RotateLeft64(b.A[v1957], -16)
		b.A[v1978] += (b.A[v1957] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v1957]))) << 1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = bits.RotateLeft64(b.A[v1925], -63)
		v2121 := v1542 + 49
		v2125 := v1542 + 17
		b.A[v2125] += (b.A[v2121] + ((uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121]))) << 1))
		v2153 := v1542 + 113
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], -32)
		v2174 := v1542 + 81
		b.A[v2174] += (b.A[v2153] + ((uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = bits.RotateLeft64(b.A[v2121], -24)
		b.A[v2125] += (b.A[v2121] + ((uint64(uint32(b.A[v2125])) * uint64(uint32(b.A[v2121]))) << 1))
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], -16)
		b.A[v2174] += (b.A[v2153] + ((uint64(uint32(b.A[v2174])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = bits.RotateLeft64(b.A[v2121], -63)
		b.A[v1542] += (b.A[v1729] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], -32)
		b.A[v1978] += (b.A[v2153] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], -24)
		b.A[v1542] += (b.A[v1729] + ((uint64(uint32(b.A[v1542])) * uint64(uint32(b.A[v1729]))) << 1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = bits.RotateLeft64(b.A[v2153], -16)
		b.A[v1978] += (b.A[v2153] + ((uint64(uint32(b.A[v1978])) * uint64(uint32(b.A[v2153]))) << 1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = bits.RotateLeft64(b.A[v1729], -63)
		b.A[v1733] += (b.A[v1925] + ((uint64(uint32(b.A[v1733])) * uint64(uint32(b.A[v1925]))) << 1))
		b.A[v1573] ^= b.A[v1733]
		b.A[v1573] = bits.RotateLeft64(b.A[v1573], -32)
		v2547 := b.A[v1573]
		v2551 := b.A[v2174]
		v2562 := (uint64(uint32(v2551)) * uint64(uint32(v2547))) << 1
		v2563 := v2547 + v2562
		v2568 := v2551 + v2563
		b.A[v2174] = v2568
		v2575 := v2568
		v2579 := b.A[v1925]
		v2580 := v2579 ^ v2575
		b.A[v1925] = v2580
		v2587 := v2580
		v2589 := bits.RotateLeft64(v2587, -24)
		b.A[v1925] = v2589
		v2596 := v2589
		v2600 := b.A[v1733]
		v2601 := uint32(v2600)
		v2602 := uint64(v2601)
		v2607 := uint32(v2596)
		v2608 := uint64(v2607)
		v2609 := v2602 * v2608
		v2611 := v2609 << 1
		v2612 := v2596 + v2611
		v2617 := v2600 + v2612
		b.A[v1733] = v2617
		v2624 := v2617
		v2628 := b.A[v1573]
		v2629 := v2628 ^ v2624
		b.A[v1573] = v2629
		v2636 := v2629
		v2638 := bits.RotateLeft64(v2636, -16)
		b.A[v1573] = v2638
		v2645 := v2638
		v2649 := b.A[v2174]
		v2650 := uint32(v2649)
		v2651 := uint64(v2650)
		v2656 := uint32(v2645)
		v2657 := uint64(v2656)
		v2658 := v2651 * v2657
		v2660 := v2658 << 1
		v2661 := v2645 + v2660
		v2666 := v2649 + v2661
		b.A[v2174] = v2666
		v2673 := v2666
		v2677 := b.A[v1925]
		v2678 := v2677 ^ v2673
		b.A[v1925] = v2678
		v2685 := v2678
		v2687 := bits.RotateLeft64(v2685, -63)
		b.A[v1925] = v2687
		v2694 := b.A[v2121]
		v2698 := b.A[v1929]
		v2699 := uint32(v2698)
		v2700 := uint64(v2699)
		v2705 := uint32(v2694)
		v2706 := uint64(v2705)
		v2707 := v2700 * v2706
		v2709 := v2707 << 1
		v2710 := v2694 + v2709
		v2715 := v2698 + v2710
		b.A[v1929] = v2715
		v2722 := v2715
		v2726 := b.A[v1761]
		v2727 := v2726 ^ v2722
		b.A[v1761] = v2727
		v2734 := v2727
		v2736 := bits.RotateLeft64(v2734, -32)
		b.A[v1761] = v2736
		v2743 := v2736
		v2747 := b.A[v1594]
		v2748 := uint32(v2747)
		v2749 := uint64(v2748)
		v2754 := uint32(v2743)
		v2755 := uint64(v2754)
		v2756 := v2749 * v2755
		v2758 := v2756 << 1
		v2759 := v2743 + v2758
		v2764 := v2747 + v2759
		b.A[v1594] = v2764
		v2771 := v2764
		v2775 := b.A[v2121]
		v2776 := v2775 ^ v2771
		b.A[v2121] = v2776
		v2783 := v2776
		v2785 := bits.RotateLeft64(v2783, -24)
		b.A[v2121] = v2785
		v2792 := v2785
		v2796 := b.A[v1929]
		v2797 := uint32(v2796)
		v2798 := uint64(v2797)
		v2803 := uint32(v2792)
		v2804 := uint64(v2803)
		v2805 := v2798 * v2804
		v2807 := v2805 << 1
		v2808 := v2792 + v2807
		v2813 := v2796 + v2808
		b.A[v1929] = v2813
		v2820 := v2813
		v2824 := b.A[v1761]
		v2825 := v2824 ^ v2820
		b.A[v1761] = v2825
		v2832 := v2825
		v2834 := bits.RotateLeft64(v2832, -16)
		b.A[v1761] = v2834
		v2841 := v2834
		v2845 := b.A[v1594]
		v2846 := uint32(v2845)
		v2847 := uint64(v2846)
		v2852 := uint32(v2841)
		v2853 := uint64(v2852)
		v2854 := v2847 * v2853
		v2856 := v2854 << 1
		v2857 := v2841 + v2856
		v2862 := v2845 + v2857
		b.A[v1594] = v2862
		v2869 := v2862
		v2873 := b.A[v2121]
		v2874 := v2873 ^ v2869
		b.A[v2121] = v2874
		v2881 := v2874
		v2883 := bits.RotateLeft64(v2881, -63)
		b.A[v2121] = v2883
		v2890 := b.A[v1549]
		v2894 := b.A[v2125]
		v2895 := uint32(v2894)
		v2896 := uint64(v2895)
		v2901 := uint32(v2890)
		v2902 := uint64(v2901)
		v2903 := v2896 * v2902
		v2905 := v2903 << 1
		v2906 := v2890 + v2905
		v2911 := v2894 + v2906
		b.A[v2125] = v2911
		v2918 := v2911
		v2922 := b.A[v1957]
		v2923 := v2922 ^ v2918
		b.A[v1957] = v2923
		v2930 := v2923
		v2932 := bits.RotateLeft64(v2930, -32)
		b.A[v1957] = v2932
		v2939 := v2932
		v2943 := b.A[v1782]
		v2944 := uint32(v2943)
		v2945 := uint64(v2944)
		v2950 := uint32(v2939)
		v2951 := uint64(v2950)
		v2952 := v2945 * v2951
		v2954 := v2952 << 1
		v2955 := v2939 + v2954
		v2960 := v2943 + v2955
		b.A[v1782] = v2960
		v2967 := v2960
		v2971 := b.A[v1549]
		v2972 := v2971 ^ v2967
		b.A[v1549] = v2972
		v2979 := v2972
		v2981 := bits.RotateLeft64(v2979, -24)
		b.A[v1549] = v2981
		v2988 := v2981
		v2992 := b.A[v2125]
		v2993 := uint32(v2992)
		v2994 := uint64(v2993)
		v2999 := uint32(v2988)
		v3000 := uint64(v2999)
		v3001 := v2994 * v3000
		v3003 := v3001 << 1
		v3004 := v2988 + v3003
		v3009 := v2992 + v3004
		b.A[v2125] = v3009
		v3016 := v3009
		v3020 := b.A[v1957]
		v3021 := v3020 ^ v3016
		b.A[v1957] = v3021
		v3028 := v3021
		v3030 := bits.RotateLeft64(v3028, -16)
		b.A[v1957] = v3030
		v3037 := v3030
		v3041 := b.A[v1782]
		v3042 := uint32(v3041)
		v3043 := uint64(v3042)
		v3048 := uint32(v3037)
		v3049 := uint64(v3048)
		v3050 := v3043 * v3049
		v3052 := v3050 << 1
		v3053 := v3037 + v3052
		v3058 := v3041 + v3053
		b.A[v1782] = v3058
		v3065 := v3058
		v3069 := b.A[v1549]
		v3070 := v3069 ^ v3065
		b.A[v1549] = v3070
		v3077 := v3070
		v3079 := bits.RotateLeft64(v3077, -63)
		b.A[v1549] = v3079
		v1542 += 2
	}
}

func Is_above_l(x []uint32) int {
	_ = x[7]
	var v2 uint64
	v2 = 1
	v2 += (uint64(x[0]) + uint64(^L[0]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[1]) + uint64(^L[1]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[2]) + uint64(^L[2]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[3]) + uint64(^L[3]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[4]) + uint64(^L[4]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[5]) + uint64(^L[5]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[6]) + uint64(^L[6]&0xffffffff))
	v2 >>= 32
	v2 += (uint64(x[7]) + uint64(^L[7]&0xffffffff))
	v2 >>= 32
	return int(v2)
}

func Hash_reduce(h []byte, a []byte, a_size uint64, b []byte, b_size uint64, c []byte, c_size uint64) {
	var v7 [64]uint8
	var v8 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v8, uint64(64))
	Crypto_blake2b_update(&v8, a, a_size)
	Crypto_blake2b_update(&v8, b, b_size)
	Crypto_blake2b_update(&v8, c, c_size)
	Crypto_blake2b_final(&v8, v7[:])
	Crypto_eddsa_reduce(h, v7[:])
}

func Select_lop(out *[10]int32, x *[10]int32, k *[10]int32, cofactor uint8) {
	var v4 [10]int32
	Fe_0(out)
	Fe_ccopy(out, k, int((uint32(cofactor)>>1)&1))
	Fe_ccopy(out, x, int(cofactor&1))
	Fe_neg(&v4, out)
	Fe_ccopy(out, &v4, int((uint32(cofactor)>>2)&1))
	clear(v4[:])
}

func Crypto_elligator_map(curve []byte, hidden []byte) {
	var v7 [10]int32
	var v8 [10]int32
	var v9 [10]int32
	var v10 [10]int32
	var v11 [10]int32
	Fe_frombytes_mask(&v7, hidden, uint32(2))
	Fe_sq(&v7, &v7)
	Fe_add(&v9, &v7, &v7)
	Fe_add(&v8, &v9, &fe_one)
	Fe_sq(&v10, &v8)
	Fe_mul(&v11, &A2, &v9)
	Fe_sub(&v11, &v11, &v10)
	Fe_mul(&v11, &v11, &A)
	Fe_mul(&v9, &v10, &v8)
	Fe_mul(&v9, &v11, &v9)
	Fe_mul(&v8, &v7, &ufactor)
	Fe_ccopy(&v8, &fe_one, Invsqrt(&v9, &v9))
	Fe_sq(&v9, &v9)
	Fe_mul(&v8, &v8, &A)
	Fe_mul(&v8, &v8, &v11)
	Fe_mul(&v8, &v8, &v10)
	Fe_mul(&v8, &v8, &v9)
	Fe_neg(&v8, &v8)
	Fe_tobytes(curve, &v8)
	clear(v9[:])
	clear(v7[:])
	clear(v10[:])
	clear(v8[:])
	clear(v11[:])
}

func Crypto_elligator_rev(hidden []byte, public_key []byte, tweak uint8) int {
	var v4 [10]int32
	var v5 [10]int32
	var v6 [10]int32
	Fe_frombytes(&v4, public_key)
	Fe_add(&v5, &v4, &A)
	Fe_mul(&v6, &v4, &v5)
	Fe_mul_small(&v6, &v6, -2)
	v15 := Invsqrt(&v6, &v6)
	if v15 != 0 {
		Fe_ccopy(&v4, &v5, int(tweak&1))
		Fe_mul(&v6, &v4, &v6)
		Fe_mul_small(&v4, &v6, 2)
		Fe_neg(&v5, &v6)
		Fe_ccopy(&v6, &v5, Fe_isodd(&v4))
		Fe_tobytes(hidden, &v6)
		hidden[31] |= (tweak & 0xc0)
	}
	clear(v4[:])
	clear(v5[:])
	clear(v6[:])
	return (v15 - 1)
}
