// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=6de4fa6d1bc3e5221890809e5c5ee349cca7b57dc776c91fc3183939de2e791d
package monocypher55

import (
	"math/bits"
)

func gap(x uint64, pow_2 uint64) uint64 {
	v7 := (^x + 1) & (pow_2 - 1)
	return uint64(v7)
}

func load24_le(s []byte) uint32 {
	_ = s[2]
	return uint32((uint32(s[0]) | uint32(uint32(s[1])<<8)) | uint32(uint32(s[2])<<16))
}

func load32_le(s []byte) uint32 {
	_ = s[3]
	return uint32(s[0]) | uint32(s[1])<<8 | uint32(s[2])<<16 | uint32(s[3])<<24
}

func load64_le(s []byte) uint64 {
	_ = s[7]
	return uint64(s[0]) | uint64(s[1])<<8 | uint64(s[2])<<16 | uint64(s[3])<<24 | uint64(s[4])<<32 | uint64(s[5])<<40 | uint64(s[6])<<48 | uint64(s[7])<<56
}

func store32_le(out []byte, in uint32) {
	_ = out[3]
	v3 := in & 0xff
	out[0] = byte(v3)
	v8 := uint32(in>>8) & 0xff
	out[1] = byte(v8)
	v13 := uint32(in>>16) & 0xff
	out[2] = byte(v13)
	v18 := uint32(in>>24) & 0xff
	out[3] = byte(v18)
}

func store64_le(out []byte, in uint64) {
	_ = out[3]
	var v2 uint32
	v2 = uint32(in)
	v11 := v2 & 0xff
	out[0] = byte(v11)
	v16 := uint64(uint64(v2)>>8) & 0xff
	out[1] = byte(v16)
	v21 := uint64(uint64(v2)>>16) & 0xff
	out[2] = byte(v21)
	v26 := uint64(uint64(v2)>>24) & 0xff
	out[3] = byte(v26)
	v6 := out[4:]
	v8 := uint64(in >> 32)
	v29 := v8 & 0xff
	v6[0] = byte(v29)
	v34 := uint64(v8>>8) & 0xff
	v6[1] = byte(v34)
	v39 := uint64(v8>>16) & 0xff
	v6[2] = byte(v39)
	v44 := uint64(v8>>24) & 0xff
	v6[3] = byte(v44)
}

func load32_le_buf(dst []uint32, src []byte, size uint64) {
	var v3 uint64
	for v3 = 0; v3 < size; v3++ {
		dst[v3] = ((uint32(src[int(v3*4):][0]) | (uint32(src[int(v3*4):][1]) << 8)) | (uint32(src[int(v3*4):][2]) << 16)) | (uint32(src[int(v3*4):][3]) << 24)
	}
}

func load64_le_buf(dst []uint64, src []byte, size uint64) {
	var v3 uint64
	for v3 = 0; v3 < size; v3++ {
		dst[v3] = (((uint64(uint32(src[int(v3*8):][0])) | uint64(uint64(uint32(src[int(v3*8):][1]))<<8)) | uint64(uint64(uint32(src[int(v3*8):][2]))<<16)) | uint64(uint64(uint32(src[int(v3*8):][3]))<<24)) | uint64((((uint64(uint32(src[int(v3*8):][4:][0]))|uint64(uint64(uint32(src[int(v3*8):][4:][1]))<<8))|uint64(uint64(uint32(src[int(v3*8):][4:][2]))<<16))|uint64(uint64(uint32(src[int(v3*8):][4:][3]))<<24))<<32)
	}
}

func store32_le_buf(dst []byte, src []uint32, size uint64) {
	var v3 uint64
	var v10 []byte
	var v11 uint32
	var v14 uint32
	var v19 uint32
	var v24 uint32
	var v29 uint32
	for v3 = 0; v3 < size; v3++ {
		v10 = dst[int(v3*4):]
		v11 = src[v3]
		v14 = v11 & 0xff
		v10[0] = byte(v14)
		v19 = (v11 >> 8) & 0xff
		v10[1] = byte(v19)
		v24 = (v11 >> 16) & 0xff
		v10[2] = byte(v24)
		v29 = (v11 >> 24) & 0xff
		v10[3] = byte(v29)
	}
}

func store64_le_buf(dst []byte, src []uint64, size uint64) {
	var v3 uint64
	for v3 = 0; v3 < size; v3++ {
		store64_le(dst[int(v3*8):], src[v3])
	}
}

func rotr64(x uint64, n uint64) uint64 {
	return bits.RotateLeft64(x, 64-int(n))
}

func rotl32(x uint32, n uint32) uint32 {
	return bits.RotateLeft32(x, int(n))
}

func neq0(diff uint64) int {
	v11 := uint64(1) & uint64(((uint64(diff>>32)|uint64(uint32(diff)))-1)>>32)
	return int(v11 - 1)
}

func x16(a []byte, b []byte) uint64 {
	_ = a[11]
	_ = b[11]
	return uint64((((((uint64(uint32(a[0])) | uint64(uint64(uint32(a[1]))<<8)) | uint64(uint64(uint32(a[2]))<<16)) | uint64(uint64(uint32(a[3]))<<24)) | uint64((((uint64(uint32(a[4]))|uint64(uint64(uint32(a[5]))<<8))|uint64(uint64(uint32(a[6]))<<16))|uint64(uint64(uint32(a[7]))<<24))<<32)) ^ ((((uint64(uint32(b[0])) | uint64(uint64(uint32(b[1]))<<8)) | uint64(uint64(uint32(b[2]))<<16)) | uint64(uint64(uint32(b[3]))<<24)) | uint64((((uint64(uint32(b[4]))|uint64(uint64(uint32(b[5]))<<8))|uint64(uint64(uint32(b[6]))<<16))|uint64(uint64(uint32(b[7]))<<24))<<32))) | (((((uint64(uint32(a[8])) | uint64(uint64(uint32(a[9]))<<8)) | uint64(uint64(uint32(a[10]))<<16)) | uint64(uint64(uint32(a[11]))<<24)) | uint64((((uint64(uint32(a[8:][4:][0]))|uint64(uint64(uint32(a[8:][4:][1]))<<8))|uint64(uint64(uint32(a[8:][4:][2]))<<16))|uint64(uint64(uint32(a[8:][4:][3]))<<24))<<32)) ^ ((((uint64(uint32(b[8])) | uint64(uint64(uint32(b[9]))<<8)) | uint64(uint64(uint32(b[10]))<<16)) | uint64(uint64(uint32(b[11]))<<24)) | uint64((((uint64(uint32(b[8:][4:][0]))|uint64(uint64(uint32(b[8:][4:][1]))<<8))|uint64(uint64(uint32(b[8:][4:][2]))<<16))|uint64(uint64(uint32(b[8:][4:][3]))<<24))<<32))))
}

func x32(a []byte, b []byte) uint64 {
	return uint64(x16(a[:], b[:]) | x16(a[16:], b[16:]))
}

func x64(a []byte, b []byte) uint64 {
	return uint64(x32(a[:], b[:]) | x32(a[32:], b[32:]))
}

func Crypto_verify16(a []byte, b []byte) int {
	return neq0(x16(a[:], b[:]))
}

func Crypto_verify32(a []byte, b []byte) int {
	return neq0(x32(a[:], b[:]))
}

func Crypto_verify64(a []byte, b []byte) int {
	return neq0(x64(a[:], b[:]))
}

func Crypto_wipe(secret []byte, size uint64) {
	if uint64(len(secret)) < size {
		size = uint64(len(secret))
	}
	clear(secret[:size])
}

func copy_block(o *Blk, in *Blk) {
	copy(o.A[:0x80], in.A[:0x80])
}

func xor_block(o *Blk, in *Blk) {
	var v2 uint64
	for v2 = 0; v2 < 0x80; v2++ {
		o.A[v2] ^= in.A[v2]
	}
}

func g_rounds(b *Blk) {
	var v1 int
	var v8 int
	var v32 int
	var v53 int
	var v188 int
	var v192 int
	var v220 int
	var v241 int
	var v384 int
	var v388 int
	var v416 int
	var v437 int
	var v580 int
	var v584 int
	var v612 int
	var v633 int
	var v1542 int
	var v1549 int
	var v1573 int
	var v1594 int
	var v1729 int
	var v1733 int
	var v1761 int
	var v1782 int
	var v1925 int
	var v1929 int
	var v1957 int
	var v1978 int
	var v2121 int
	var v2125 int
	var v2153 int
	var v2174 int
	var v2547 uint64
	var v2551 uint64
	var v2562 uint64
	var v2563 uint64
	var v2568 uint64
	var v2575 uint64
	var v2579 uint64
	var v2580 uint64
	var v2587 uint64
	var v2589 uint64
	var v2596 uint64
	var v2600 uint64
	var v2601 uint32
	var v2602 uint64
	var v2607 uint32
	var v2608 uint64
	var v2609 uint64
	var v2611 uint64
	var v2612 uint64
	var v2617 uint64
	var v2624 uint64
	var v2628 uint64
	var v2629 uint64
	var v2636 uint64
	var v2638 uint64
	var v2645 uint64
	var v2649 uint64
	var v2650 uint32
	var v2651 uint64
	var v2656 uint32
	var v2657 uint64
	var v2658 uint64
	var v2660 uint64
	var v2661 uint64
	var v2666 uint64
	var v2673 uint64
	var v2677 uint64
	var v2678 uint64
	var v2685 uint64
	var v2687 uint64
	var v2694 uint64
	var v2698 uint64
	var v2699 uint32
	var v2700 uint64
	var v2705 uint32
	var v2706 uint64
	var v2707 uint64
	var v2709 uint64
	var v2710 uint64
	var v2715 uint64
	var v2722 uint64
	var v2726 uint64
	var v2727 uint64
	var v2734 uint64
	var v2736 uint64
	var v2743 uint64
	var v2747 uint64
	var v2748 uint32
	var v2749 uint64
	var v2754 uint32
	var v2755 uint64
	var v2756 uint64
	var v2758 uint64
	var v2759 uint64
	var v2764 uint64
	var v2771 uint64
	var v2775 uint64
	var v2776 uint64
	var v2783 uint64
	var v2785 uint64
	var v2792 uint64
	var v2796 uint64
	var v2797 uint32
	var v2798 uint64
	var v2803 uint32
	var v2804 uint64
	var v2805 uint64
	var v2807 uint64
	var v2808 uint64
	var v2813 uint64
	var v2820 uint64
	var v2824 uint64
	var v2825 uint64
	var v2832 uint64
	var v2834 uint64
	var v2841 uint64
	var v2845 uint64
	var v2846 uint32
	var v2847 uint64
	var v2852 uint32
	var v2853 uint64
	var v2854 uint64
	var v2856 uint64
	var v2857 uint64
	var v2862 uint64
	var v2869 uint64
	var v2873 uint64
	var v2874 uint64
	var v2881 uint64
	var v2883 uint64
	var v2890 uint64
	var v2894 uint64
	var v2895 uint32
	var v2896 uint64
	var v2901 uint32
	var v2902 uint64
	var v2903 uint64
	var v2905 uint64
	var v2906 uint64
	var v2911 uint64
	var v2918 uint64
	var v2922 uint64
	var v2923 uint64
	var v2930 uint64
	var v2932 uint64
	var v2939 uint64
	var v2943 uint64
	var v2944 uint32
	var v2945 uint64
	var v2950 uint32
	var v2951 uint64
	var v2952 uint64
	var v2954 uint64
	var v2955 uint64
	var v2960 uint64
	var v2967 uint64
	var v2971 uint64
	var v2972 uint64
	var v2979 uint64
	var v2981 uint64
	var v2988 uint64
	var v2992 uint64
	var v2993 uint32
	var v2994 uint64
	var v2999 uint32
	var v3000 uint64
	var v3001 uint64
	var v3003 uint64
	var v3004 uint64
	var v3009 uint64
	var v3016 uint64
	var v3020 uint64
	var v3021 uint64
	var v3028 uint64
	var v3030 uint64
	var v3037 uint64
	var v3041 uint64
	var v3042 uint32
	var v3043 uint64
	var v3048 uint32
	var v3049 uint64
	var v3050 uint64
	var v3052 uint64
	var v3053 uint64
	var v3058 uint64
	var v3065 uint64
	var v3069 uint64
	var v3070 uint64
	var v3077 uint64
	var v3079 uint64
	for v1 = 0; v1 < 128; v1 += 16 {
		v8 = v1 + 4
		b.A[v1] += (b.A[v8] + uint64((uint64(uint32(b.A[v1]))*uint64(uint32(b.A[v8])))<<1))
		v32 = v1 + 12
		b.A[v32] ^= b.A[v1]
		b.A[v32] = rotr64(b.A[v32], uint64(32))
		v53 = v1 + 8
		b.A[v53] += (b.A[v32] + uint64((uint64(uint32(b.A[v53]))*uint64(uint32(b.A[v32])))<<1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = rotr64(b.A[v8], uint64(24))
		b.A[v1] += (b.A[v8] + uint64((uint64(uint32(b.A[v1]))*uint64(uint32(b.A[v8])))<<1))
		b.A[v32] ^= b.A[v1]
		b.A[v32] = rotr64(b.A[v32], uint64(16))
		b.A[v53] += (b.A[v32] + uint64((uint64(uint32(b.A[v53]))*uint64(uint32(b.A[v32])))<<1))
		b.A[v8] ^= b.A[v53]
		b.A[v8] = rotr64(b.A[v8], uint64(63))
		v188 = v1 + 5
		v192 = v1 + 1
		b.A[v192] += (b.A[v188] + uint64((uint64(uint32(b.A[v192]))*uint64(uint32(b.A[v188])))<<1))
		v220 = v1 + 13
		b.A[v220] ^= b.A[v192]
		b.A[v220] = rotr64(b.A[v220], uint64(32))
		v241 = v1 + 9
		b.A[v241] += (b.A[v220] + uint64((uint64(uint32(b.A[v241]))*uint64(uint32(b.A[v220])))<<1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = rotr64(b.A[v188], uint64(24))
		b.A[v192] += (b.A[v188] + uint64((uint64(uint32(b.A[v192]))*uint64(uint32(b.A[v188])))<<1))
		b.A[v220] ^= b.A[v192]
		b.A[v220] = rotr64(b.A[v220], uint64(16))
		b.A[v241] += (b.A[v220] + uint64((uint64(uint32(b.A[v241]))*uint64(uint32(b.A[v220])))<<1))
		b.A[v188] ^= b.A[v241]
		b.A[v188] = rotr64(b.A[v188], uint64(63))
		v384 = v1 + 6
		v388 = v1 + 2
		b.A[v388] += (b.A[v384] + uint64((uint64(uint32(b.A[v388]))*uint64(uint32(b.A[v384])))<<1))
		v416 = v1 + 14
		b.A[v416] ^= b.A[v388]
		b.A[v416] = rotr64(b.A[v416], uint64(32))
		v437 = v1 + 10
		b.A[v437] += (b.A[v416] + uint64((uint64(uint32(b.A[v437]))*uint64(uint32(b.A[v416])))<<1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = rotr64(b.A[v384], uint64(24))
		b.A[v388] += (b.A[v384] + uint64((uint64(uint32(b.A[v388]))*uint64(uint32(b.A[v384])))<<1))
		b.A[v416] ^= b.A[v388]
		b.A[v416] = rotr64(b.A[v416], uint64(16))
		b.A[v437] += (b.A[v416] + uint64((uint64(uint32(b.A[v437]))*uint64(uint32(b.A[v416])))<<1))
		b.A[v384] ^= b.A[v437]
		b.A[v384] = rotr64(b.A[v384], uint64(63))
		v580 = v1 + 7
		v584 = v1 + 3
		b.A[v584] += (b.A[v580] + uint64((uint64(uint32(b.A[v584]))*uint64(uint32(b.A[v580])))<<1))
		v612 = v1 + 15
		b.A[v612] ^= b.A[v584]
		b.A[v612] = rotr64(b.A[v612], uint64(32))
		v633 = v1 + 11
		b.A[v633] += (b.A[v612] + uint64((uint64(uint32(b.A[v633]))*uint64(uint32(b.A[v612])))<<1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = rotr64(b.A[v580], uint64(24))
		b.A[v584] += (b.A[v580] + uint64((uint64(uint32(b.A[v584]))*uint64(uint32(b.A[v580])))<<1))
		b.A[v612] ^= b.A[v584]
		b.A[v612] = rotr64(b.A[v612], uint64(16))
		b.A[v633] += (b.A[v612] + uint64((uint64(uint32(b.A[v633]))*uint64(uint32(b.A[v612])))<<1))
		b.A[v580] ^= b.A[v633]
		b.A[v580] = rotr64(b.A[v580], uint64(63))
		b.A[v1] += (b.A[v188] + uint64((uint64(uint32(b.A[v1]))*uint64(uint32(b.A[v188])))<<1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = rotr64(b.A[v612], uint64(32))
		b.A[v437] += (b.A[v612] + uint64((uint64(uint32(b.A[v437]))*uint64(uint32(b.A[v612])))<<1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = rotr64(b.A[v188], uint64(24))
		b.A[v1] += (b.A[v188] + uint64((uint64(uint32(b.A[v1]))*uint64(uint32(b.A[v188])))<<1))
		b.A[v612] ^= b.A[v1]
		b.A[v612] = rotr64(b.A[v612], uint64(16))
		b.A[v437] += (b.A[v612] + uint64((uint64(uint32(b.A[v437]))*uint64(uint32(b.A[v612])))<<1))
		b.A[v188] ^= b.A[v437]
		b.A[v188] = rotr64(b.A[v188], uint64(63))
		b.A[v192] += (b.A[v384] + uint64((uint64(uint32(b.A[v192]))*uint64(uint32(b.A[v384])))<<1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = rotr64(b.A[v32], uint64(32))
		b.A[v633] += (b.A[v32] + uint64((uint64(uint32(b.A[v633]))*uint64(uint32(b.A[v32])))<<1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = rotr64(b.A[v384], uint64(24))
		b.A[v192] += (b.A[v384] + uint64((uint64(uint32(b.A[v192]))*uint64(uint32(b.A[v384])))<<1))
		b.A[v32] ^= b.A[v192]
		b.A[v32] = rotr64(b.A[v32], uint64(16))
		b.A[v633] += (b.A[v32] + uint64((uint64(uint32(b.A[v633]))*uint64(uint32(b.A[v32])))<<1))
		b.A[v384] ^= b.A[v633]
		b.A[v384] = rotr64(b.A[v384], uint64(63))
		b.A[v388] += (b.A[v580] + uint64((uint64(uint32(b.A[v388]))*uint64(uint32(b.A[v580])))<<1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = rotr64(b.A[v220], uint64(32))
		b.A[v53] += (b.A[v220] + uint64((uint64(uint32(b.A[v53]))*uint64(uint32(b.A[v220])))<<1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = rotr64(b.A[v580], uint64(24))
		b.A[v388] += (b.A[v580] + uint64((uint64(uint32(b.A[v388]))*uint64(uint32(b.A[v580])))<<1))
		b.A[v220] ^= b.A[v388]
		b.A[v220] = rotr64(b.A[v220], uint64(16))
		b.A[v53] += (b.A[v220] + uint64((uint64(uint32(b.A[v53]))*uint64(uint32(b.A[v220])))<<1))
		b.A[v580] ^= b.A[v53]
		b.A[v580] = rotr64(b.A[v580], uint64(63))
		b.A[v584] += (b.A[v8] + uint64((uint64(uint32(b.A[v584]))*uint64(uint32(b.A[v8])))<<1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = rotr64(b.A[v416], uint64(32))
		b.A[v241] += (b.A[v416] + uint64((uint64(uint32(b.A[v241]))*uint64(uint32(b.A[v416])))<<1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = rotr64(b.A[v8], uint64(24))
		b.A[v584] += (b.A[v8] + uint64((uint64(uint32(b.A[v584]))*uint64(uint32(b.A[v8])))<<1))
		b.A[v416] ^= b.A[v584]
		b.A[v416] = rotr64(b.A[v416], uint64(16))
		b.A[v241] += (b.A[v416] + uint64((uint64(uint32(b.A[v241]))*uint64(uint32(b.A[v416])))<<1))
		b.A[v8] ^= b.A[v241]
		b.A[v8] = rotr64(b.A[v8], uint64(63))
	}
	for v1542 = 0; v1542 < 16; v1542 += 2 {
		v1549 = v1542 + 32
		b.A[v1542] += (b.A[v1549] + uint64((uint64(uint32(b.A[v1542]))*uint64(uint32(b.A[v1549])))<<1))
		v1573 = v1542 + 96
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = rotr64(b.A[v1573], uint64(32))
		v1594 = v1542 + 64
		b.A[v1594] += (b.A[v1573] + uint64((uint64(uint32(b.A[v1594]))*uint64(uint32(b.A[v1573])))<<1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = rotr64(b.A[v1549], uint64(24))
		b.A[v1542] += (b.A[v1549] + uint64((uint64(uint32(b.A[v1542]))*uint64(uint32(b.A[v1549])))<<1))
		b.A[v1573] ^= b.A[v1542]
		b.A[v1573] = rotr64(b.A[v1573], uint64(16))
		b.A[v1594] += (b.A[v1573] + uint64((uint64(uint32(b.A[v1594]))*uint64(uint32(b.A[v1573])))<<1))
		b.A[v1549] ^= b.A[v1594]
		b.A[v1549] = rotr64(b.A[v1549], uint64(63))
		v1729 = v1542 + 33
		v1733 = v1542 + 1
		b.A[v1733] += (b.A[v1729] + uint64((uint64(uint32(b.A[v1733]))*uint64(uint32(b.A[v1729])))<<1))
		v1761 = v1542 + 97
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = rotr64(b.A[v1761], uint64(32))
		v1782 = v1542 + 65
		b.A[v1782] += (b.A[v1761] + uint64((uint64(uint32(b.A[v1782]))*uint64(uint32(b.A[v1761])))<<1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = rotr64(b.A[v1729], uint64(24))
		b.A[v1733] += (b.A[v1729] + uint64((uint64(uint32(b.A[v1733]))*uint64(uint32(b.A[v1729])))<<1))
		b.A[v1761] ^= b.A[v1733]
		b.A[v1761] = rotr64(b.A[v1761], uint64(16))
		b.A[v1782] += (b.A[v1761] + uint64((uint64(uint32(b.A[v1782]))*uint64(uint32(b.A[v1761])))<<1))
		b.A[v1729] ^= b.A[v1782]
		b.A[v1729] = rotr64(b.A[v1729], uint64(63))
		v1925 = v1542 + 48
		v1929 = v1542 + 16
		b.A[v1929] += (b.A[v1925] + uint64((uint64(uint32(b.A[v1929]))*uint64(uint32(b.A[v1925])))<<1))
		v1957 = v1542 + 112
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = rotr64(b.A[v1957], uint64(32))
		v1978 = v1542 + 80
		b.A[v1978] += (b.A[v1957] + uint64((uint64(uint32(b.A[v1978]))*uint64(uint32(b.A[v1957])))<<1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = rotr64(b.A[v1925], uint64(24))
		b.A[v1929] += (b.A[v1925] + uint64((uint64(uint32(b.A[v1929]))*uint64(uint32(b.A[v1925])))<<1))
		b.A[v1957] ^= b.A[v1929]
		b.A[v1957] = rotr64(b.A[v1957], uint64(16))
		b.A[v1978] += (b.A[v1957] + uint64((uint64(uint32(b.A[v1978]))*uint64(uint32(b.A[v1957])))<<1))
		b.A[v1925] ^= b.A[v1978]
		b.A[v1925] = rotr64(b.A[v1925], uint64(63))
		v2121 = v1542 + 49
		v2125 = v1542 + 17
		b.A[v2125] += (b.A[v2121] + uint64((uint64(uint32(b.A[v2125]))*uint64(uint32(b.A[v2121])))<<1))
		v2153 = v1542 + 113
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = rotr64(b.A[v2153], uint64(32))
		v2174 = v1542 + 81
		b.A[v2174] += (b.A[v2153] + uint64((uint64(uint32(b.A[v2174]))*uint64(uint32(b.A[v2153])))<<1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = rotr64(b.A[v2121], uint64(24))
		b.A[v2125] += (b.A[v2121] + uint64((uint64(uint32(b.A[v2125]))*uint64(uint32(b.A[v2121])))<<1))
		b.A[v2153] ^= b.A[v2125]
		b.A[v2153] = rotr64(b.A[v2153], uint64(16))
		b.A[v2174] += (b.A[v2153] + uint64((uint64(uint32(b.A[v2174]))*uint64(uint32(b.A[v2153])))<<1))
		b.A[v2121] ^= b.A[v2174]
		b.A[v2121] = rotr64(b.A[v2121], uint64(63))
		b.A[v1542] += (b.A[v1729] + uint64((uint64(uint32(b.A[v1542]))*uint64(uint32(b.A[v1729])))<<1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = rotr64(b.A[v2153], uint64(32))
		b.A[v1978] += (b.A[v2153] + uint64((uint64(uint32(b.A[v1978]))*uint64(uint32(b.A[v2153])))<<1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = rotr64(b.A[v1729], uint64(24))
		b.A[v1542] += (b.A[v1729] + uint64((uint64(uint32(b.A[v1542]))*uint64(uint32(b.A[v1729])))<<1))
		b.A[v2153] ^= b.A[v1542]
		b.A[v2153] = rotr64(b.A[v2153], uint64(16))
		b.A[v1978] += (b.A[v2153] + uint64((uint64(uint32(b.A[v1978]))*uint64(uint32(b.A[v2153])))<<1))
		b.A[v1729] ^= b.A[v1978]
		b.A[v1729] = rotr64(b.A[v1729], uint64(63))
		b.A[v1733] += (b.A[v1925] + uint64((uint64(uint32(b.A[v1733]))*uint64(uint32(b.A[v1925])))<<1))
		b.A[v1573] ^= b.A[v1733]
		b.A[v1573] = rotr64(b.A[v1573], uint64(32))
		v2547 = b.A[v1573]
		v2551 = b.A[v2174]
		v2562 = uint64((uint64(uint32(v2551)) * uint64(uint32(v2547))) << 1)
		v2563 = v2547 + v2562
		v2568 = v2551 + v2563
		b.A[v2174] = v2568
		v2575 = v2568
		v2579 = b.A[v1925]
		v2580 = v2579 ^ v2575
		b.A[v1925] = v2580
		v2587 = v2580
		v2589 = rotr64(v2587, 24)
		b.A[v1925] = v2589
		v2596 = v2589
		v2600 = b.A[v1733]
		v2601 = uint32(v2600)
		v2602 = uint64(v2601)
		v2607 = uint32(v2596)
		v2608 = uint64(v2607)
		v2609 = v2602 * v2608
		v2611 = uint64(v2609 << 1)
		v2612 = v2596 + v2611
		v2617 = v2600 + v2612
		b.A[v1733] = v2617
		v2624 = v2617
		v2628 = b.A[v1573]
		v2629 = v2628 ^ v2624
		b.A[v1573] = v2629
		v2636 = v2629
		v2638 = rotr64(v2636, 16)
		b.A[v1573] = v2638
		v2645 = v2638
		v2649 = b.A[v2174]
		v2650 = uint32(v2649)
		v2651 = uint64(v2650)
		v2656 = uint32(v2645)
		v2657 = uint64(v2656)
		v2658 = v2651 * v2657
		v2660 = uint64(v2658 << 1)
		v2661 = v2645 + v2660
		v2666 = v2649 + v2661
		b.A[v2174] = v2666
		v2673 = v2666
		v2677 = b.A[v1925]
		v2678 = v2677 ^ v2673
		b.A[v1925] = v2678
		v2685 = v2678
		v2687 = rotr64(v2685, 63)
		b.A[v1925] = v2687
		v2694 = b.A[v2121]
		v2698 = b.A[v1929]
		v2699 = uint32(v2698)
		v2700 = uint64(v2699)
		v2705 = uint32(v2694)
		v2706 = uint64(v2705)
		v2707 = v2700 * v2706
		v2709 = uint64(v2707 << 1)
		v2710 = v2694 + v2709
		v2715 = v2698 + v2710
		b.A[v1929] = v2715
		v2722 = v2715
		v2726 = b.A[v1761]
		v2727 = v2726 ^ v2722
		b.A[v1761] = v2727
		v2734 = v2727
		v2736 = rotr64(v2734, 32)
		b.A[v1761] = v2736
		v2743 = v2736
		v2747 = b.A[v1594]
		v2748 = uint32(v2747)
		v2749 = uint64(v2748)
		v2754 = uint32(v2743)
		v2755 = uint64(v2754)
		v2756 = v2749 * v2755
		v2758 = uint64(v2756 << 1)
		v2759 = v2743 + v2758
		v2764 = v2747 + v2759
		b.A[v1594] = v2764
		v2771 = v2764
		v2775 = b.A[v2121]
		v2776 = v2775 ^ v2771
		b.A[v2121] = v2776
		v2783 = v2776
		v2785 = rotr64(v2783, 24)
		b.A[v2121] = v2785
		v2792 = v2785
		v2796 = b.A[v1929]
		v2797 = uint32(v2796)
		v2798 = uint64(v2797)
		v2803 = uint32(v2792)
		v2804 = uint64(v2803)
		v2805 = v2798 * v2804
		v2807 = uint64(v2805 << 1)
		v2808 = v2792 + v2807
		v2813 = v2796 + v2808
		b.A[v1929] = v2813
		v2820 = v2813
		v2824 = b.A[v1761]
		v2825 = v2824 ^ v2820
		b.A[v1761] = v2825
		v2832 = v2825
		v2834 = rotr64(v2832, 16)
		b.A[v1761] = v2834
		v2841 = v2834
		v2845 = b.A[v1594]
		v2846 = uint32(v2845)
		v2847 = uint64(v2846)
		v2852 = uint32(v2841)
		v2853 = uint64(v2852)
		v2854 = v2847 * v2853
		v2856 = uint64(v2854 << 1)
		v2857 = v2841 + v2856
		v2862 = v2845 + v2857
		b.A[v1594] = v2862
		v2869 = v2862
		v2873 = b.A[v2121]
		v2874 = v2873 ^ v2869
		b.A[v2121] = v2874
		v2881 = v2874
		v2883 = rotr64(v2881, 63)
		b.A[v2121] = v2883
		v2890 = b.A[v1549]
		v2894 = b.A[v2125]
		v2895 = uint32(v2894)
		v2896 = uint64(v2895)
		v2901 = uint32(v2890)
		v2902 = uint64(v2901)
		v2903 = v2896 * v2902
		v2905 = uint64(v2903 << 1)
		v2906 = v2890 + v2905
		v2911 = v2894 + v2906
		b.A[v2125] = v2911
		v2918 = v2911
		v2922 = b.A[v1957]
		v2923 = v2922 ^ v2918
		b.A[v1957] = v2923
		v2930 = v2923
		v2932 = rotr64(v2930, 32)
		b.A[v1957] = v2932
		v2939 = v2932
		v2943 = b.A[v1782]
		v2944 = uint32(v2943)
		v2945 = uint64(v2944)
		v2950 = uint32(v2939)
		v2951 = uint64(v2950)
		v2952 = v2945 * v2951
		v2954 = uint64(v2952 << 1)
		v2955 = v2939 + v2954
		v2960 = v2943 + v2955
		b.A[v1782] = v2960
		v2967 = v2960
		v2971 = b.A[v1549]
		v2972 = v2971 ^ v2967
		b.A[v1549] = v2972
		v2979 = v2972
		v2981 = rotr64(v2979, 24)
		b.A[v1549] = v2981
		v2988 = v2981
		v2992 = b.A[v2125]
		v2993 = uint32(v2992)
		v2994 = uint64(v2993)
		v2999 = uint32(v2988)
		v3000 = uint64(v2999)
		v3001 = v2994 * v3000
		v3003 = uint64(v3001 << 1)
		v3004 = v2988 + v3003
		v3009 = v2992 + v3004
		b.A[v2125] = v3009
		v3016 = v3009
		v3020 = b.A[v1957]
		v3021 = v3020 ^ v3016
		b.A[v1957] = v3021
		v3028 = v3021
		v3030 = rotr64(v3028, 16)
		b.A[v1957] = v3030
		v3037 = v3030
		v3041 = b.A[v1782]
		v3042 = uint32(v3041)
		v3043 = uint64(v3042)
		v3048 = uint32(v3037)
		v3049 = uint64(v3048)
		v3050 = v3043 * v3049
		v3052 = uint64(v3050 << 1)
		v3053 = v3037 + v3052
		v3058 = v3041 + v3053
		b.A[v1782] = v3058
		v3065 = v3058
		v3069 = b.A[v1549]
		v3070 = v3069 ^ v3065
		b.A[v1549] = v3070
		v3077 = v3070
		v3079 = rotr64(v3077, 63)
		b.A[v1549] = v3079
	}
}

func is_above_l(x []uint32) int {
	_ = x[7]
	var v2 uint64
	var v14 uint32
	v2 = 1
	v14 = ^uint32(L[0]) & 0xffffffff
	v2 += (uint64(x[0]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[1]) & 0xffffffff
	v2 += (uint64(x[1]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[2]) & 0xffffffff
	v2 += (uint64(x[2]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[3]) & 0xffffffff
	v2 += (uint64(x[3]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[4]) & 0xffffffff
	v2 += (uint64(x[4]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[5]) & 0xffffffff
	v2 += (uint64(x[5]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[6]) & 0xffffffff
	v2 += (uint64(x[6]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	v14 = ^uint32(L[7]) & 0xffffffff
	v2 += (uint64(x[7]) + uint64(v14))
	v2 = uint64(v2 >> 32)
	return int(v2)
}

func hash_reduce(h []byte, a []byte, a_size uint64, b []byte, b_size uint64, c []byte, c_size uint64) {
	var v7 [64]byte
	var v8 Crypto_blake2b_ctx
	Crypto_blake2b_init(&v8, uint64(64))
	Crypto_blake2b_update(&v8, a[:], a_size)
	Crypto_blake2b_update(&v8, b[:], b_size)
	Crypto_blake2b_update(&v8, c[:], c_size)
	Crypto_blake2b_final(&v8, v7[:])
	Crypto_eddsa_reduce(h[:], v7[:])
}
