// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

type Crypto_aead_ctx struct {
	Counter uint64
	Key     [32]uint8
	Nonce   [8]uint8
}

type Crypto_blake2b_ctx struct {
	Hash         [8]uint64
	Input_offset [2]uint64
	Input        [16]uint64
	Input_idx    uint64
	Hash_size    uint64
}

type Crypto_argon2_config struct {
	Algorithm uint32
	Nb_blocks uint32
	Nb_passes uint32
	Nb_lanes  uint32
}

type Crypto_argon2_inputs struct {
	Pass      []uint8
	Salt      []uint8
	Pass_size uint32
	Salt_size uint32
}

type Crypto_argon2_extras struct {
	Key      []uint8
	Ad       []uint8
	Key_size uint32
	Ad_size  uint32
}

type Crypto_poly1305_ctx struct {
	C     [16]uint8
	C_idx uint64
	R     [4]uint32
	Pad   [4]uint32
	H     [5]uint32
}

type Blk struct {
	A [128]uint64
}

type Ge struct {
	X [10]int32
	Y [10]int32
	Z [10]int32
	T [10]int32
}

type Ge_cached struct {
	Yp [10]int32
	Ym [10]int32
	Z  [10]int32
	T2 [10]int32
}

type Ge_precomp struct {
	Yp [10]int32
	Ym [10]int32
	T2 [10]int32
}

var chacha20_constant = []byte("expand 32-byte k")

var zero_arr [128]byte

var zero = zero_arr[:]

var iv = [8]uint64{0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1, 0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179}

var L = []uint32{0x5cf5d3ed, 0x5812631a, 0xa2f79cd6, 0x14def9de, 0x00000000, 0x00000000, 0x00000000, 0x10000000}

var r = [9]uint32{0x0a2c131b, 0xed9ce5a3, 0x086329a7, 0x2106215d, 0xffffffeb, 0xffffffff, 0xffffffff, 0xffffffff, 0xf}

var half_mod_L = [32]byte{247, 233, 122, 46, 141, 49, 9, 44, 107, 206, 123, 81, 239, 124, 111, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8}

var half_ones = [32]byte{142, 74, 204, 70, 186, 24, 118, 107, 184, 231, 190, 57, 250, 173, 119, 99, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 7}

var dirty_base_point = [32]byte{0xd8, 0x86, 0x1a, 0xa2, 0x78, 0x7a, 0xd9, 0x26, 0x8b, 0x74, 0x74, 0xb6, 0x82, 0xe3, 0xbe, 0xc3, 0xce, 0x36, 0x9a, 0x1e, 0x5e, 0x31, 0x47, 0xa2, 0x6d, 0x37, 0x7c, 0xfd, 0x20, 0xb5, 0xdf, 0x75}

var k = [8]uint32{0x12547e1b, 0xd2b51da3, 0xfdba84ff, 0xb1a206f2, 0xffa36bea, 0x14e75438, 0x6fe91836, 0x9db6c6f2}

var s = [8]uint32{0, 0, 0, 0, 0, 0, 0, 0}

var Lm2 = [32]byte{0xeb, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10}

var m_inv = [8]uint32{0x8d98951d, 0xd6ec3174, 0x737dcf70, 0xc6ef5bf4, 0xfffffffe, 0xffffffff, 0xffffffff, 0x0fffffff}

var fe_one = [10]int32{1, 0, 0, 0, 0, 0, 0, 0, 0, 0}

var sqrtm1 = [10]int32{-32595792, -7943725, 9377950, 3500415, 12389472, -272473, -25146209, -2005654, 326686, 11406482}

var d = [10]int32{-10913610, 13857413, -15372611, 6949391, 114729, -8787816, -6275908, -3247719, -18696448, -12055116}

var D2 = [10]int32{-21827239, -5839606, -30745221, 13898782, 229458, 15978800, -12551817, -6495438, 29715968, 9444199}

var lop_x = [10]int32{21352778, 5345713, 4660180, -8347857, 24143090, 14568123, 30185756, -12247770, -33528939, 8345319}

var lop_y = [10]int32{-6952922, -1265500, 6862341, -7057498, -4037696, -5447722, 31680899, -15325402, -19365852, 1569102}

var ufactor = [10]int32{-1917299, 15887451, -18755900, -7000830, -24778944, 544946, -16816446, 4011309, -653372, 10741468}

var A2 = [10]int32{12721188, 3529, 0, 0, 0, 0, 0, 0, 0, 0}

var A = [10]int32{486662, 0, 0, 0, 0, 0, 0, 0, 0, 0}

var crypto_x25519_public_key_base_point_arr = [32]byte{9}

var crypto_x25519_public_key_base_point = crypto_x25519_public_key_base_point_arr[:]
