// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=dd6552a61c3d7977bceddc90f5bab7e65e0b1e907aa53ab25bfa3966b8817ab7
package monocypher55

import (
	"runtime"
)

func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	var v27 uint32
	var v29 uint64
	var v37 uint32
	clear(ctx.H[:5])
	ctx.C_idx = 0
	load32_le_buf(ctx.R[:], key[:], uint64(4))
	load32_le_buf(ctx.Pad[:], key[16:], uint64(4))
	v27 = ctx.R[0] & 0xfffffff
	ctx.R[0] = v27
	for v29 = 1; v29 < 4; v29++ {
		v37 = ctx.R[v29] & 0xffffffc
		ctx.R[v29] = v37
	}
}

func Crypto_poly1305_update(ctx *Crypto_poly1305_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v14 uint64
	var v15 uint64
	var v24 uint64
	var v49 uint64
	var v59 uint64
	v3 = 0
	_ = v3
	if message_size == 0 {
		return
	}
	v14 = min(gap(ctx.C_idx, 16), message_size)
	for v15 = 0; v15 < v14; v15++ {
		ctx.C[ctx.C_idx] = message[v3]
		v24 = ctx.C_idx + 1
		ctx.C_idx = v24
		v3++
		message_size--
	}
	if ctx.C_idx == 16 {
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(1))
		ctx.C_idx = 0
	}
	v40 := uint64(message_size >> 4)
	Poly_blocks(ctx, message[v3:], v40, uint32(1))
	v3 += uint64(v40 << 4)
	v48 := message_size & 15
	message_size = v48
	for v49 = 0; v49 < message_size; v49++ {
		ctx.C[ctx.C_idx] = message[v3+v49]
		v59 = ctx.C_idx + 1
		ctx.C_idx = v59
	}
}

func Crypto_poly1305_final(ctx *Crypto_poly1305_ctx, mac []byte) {
	var v6 uint64
	var v25 uint64
	var v45 uint64
	var v60 []byte
	var v61 uint32
	var v68 uint32
	var v73 uint32
	var v78 uint32
	var v83 uint32
	_ = 0
	if ctx.C_idx != 0 {
		for v6 = 0; v6 < (uint64(16) - ctx.C_idx); v6++ {
			ctx.C[ctx.C_idx+v6] = 0
		}
		ctx.C[ctx.C_idx] = 1
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(0))
	}
	v25 = 5
	v25 += uint64(ctx.H[0])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[1])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[2])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[3])
	v25 = uint64(v25 >> 32)
	v25 += uint64(ctx.H[4])
	v25 = uint64(v25>>2) * 5
	for v45 = 0; v45 < 4; v45++ {
		v25 += (uint64(ctx.H[v45]) + uint64(ctx.Pad[v45]))
		v60 = mac[int(v45*4):]
		v61 = uint32(v25)
		v68 = v61 & 0xff
		v60[0] = byte(v68)
		v73 = (v61 >> 8) & 0xff
		v60[1] = byte(v73)
		v78 = (v61 >> 16) & 0xff
		v60[2] = byte(v78)
		v83 = (v61 >> 24) & 0xff
		v60[3] = byte(v83)
		v25 = uint64(v25 >> 32)
	}
	*ctx = Crypto_poly1305_ctx{}
	runtime.KeepAlive(ctx)
}

func Crypto_poly1305(mac []byte, message []byte, message_size uint64, key []byte) {
	var v4 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v4, key[:])
	Crypto_poly1305_update(&v4, message[:], message_size)
	Crypto_poly1305_final(&v4, mac[:])
}
