// Code generated by sgoiter emit go127; DO NOT EDIT.
package monocypher55

func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	var v30 uint64
	clear(ctx.H[:5])
	ctx.C_idx = 0
	Load32_le_buf(ctx.R[:], key, uint64(4))
	Load32_le_buf(ctx.Pad[:], key[16:], uint64(4))
	ctx.R[0] &= 0xfffffff
	v30 = 1
	for v30 < 4 {
		ctx.R[v30] &= 0xffffffc
		v30++
	}
}

func Crypto_poly1305_update(ctx *Crypto_poly1305_ctx, message []byte, message_size uint64) {
	var v3 uint64
	var v15 uint64
	var v47 uint64
	v3 = 0
	if message_size == 0 {
		return
	}
	v14 := min((-ctx.C_idx)&15, message_size)
	v15 = 0
	for v15 < v14 {
		ctx.C[ctx.C_idx] = message[v3]
		v24 := ctx.C_idx + 1
		ctx.C_idx = v24
		v3++
		message_size--
		v15++
	}
	if ctx.C_idx == 16 {
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(1))
		ctx.C_idx = 0
	}
	v38 := message_size >> 4
	Poly_blocks(ctx, message[v3:], v38, uint32(1))
	v3 += (v38 << 4)
	message_size &= 15
	v47 = 0
	for v47 < message_size {
		ctx.C[ctx.C_idx] = message[v3+v47]
		v57 := ctx.C_idx + 1
		ctx.C_idx = v57
		v47++
	}
}

func Crypto_poly1305_final(ctx *Crypto_poly1305_ctx, mac []byte) {
	var v4 uint64
	var v23 uint64
	if ctx.C_idx != 0 {
		v4 = 0
		for v4 < (uint64(16) - ctx.C_idx) {
			ctx.C[ctx.C_idx+v4] = 0
			v4++
		}
		ctx.C[ctx.C_idx] = 1
		Poly_blocks(ctx, ctx.C[:], uint64(1), uint32(0))
	}
	v23 = 5
	v23 += uint64(ctx.H[0])
	v23 >>= 32
	v23 += uint64(ctx.H[1])
	v23 >>= 32
	v23 += uint64(ctx.H[2])
	v23 >>= 32
	v23 += uint64(ctx.H[3])
	v23 >>= 32
	v23 += uint64(ctx.H[4])
	v23 = (v23 >> 2) * 5
	v23 += (uint64(ctx.H[0]) + uint64(ctx.Pad[0]))
	Store32_le(mac[int(0*4):], uint32(v23))
	v23 >>= 32
	v23 += (uint64(ctx.H[1]) + uint64(ctx.Pad[1]))
	Store32_le(mac[int(1*4):], uint32(v23))
	v23 >>= 32
	v23 += (uint64(ctx.H[2]) + uint64(ctx.Pad[2]))
	Store32_le(mac[int(2*4):], uint32(v23))
	v23 >>= 32
	v23 += (uint64(ctx.H[3]) + uint64(ctx.Pad[3]))
	Store32_le(mac[int(3*4):], uint32(v23))
	v23 >>= 32
}

func Crypto_poly1305(mac []byte, message []byte, message_size uint64, key []byte) {
	var v4 Crypto_poly1305_ctx
	Crypto_poly1305_init(&v4, key)
	Crypto_poly1305_update(&v4, message, message_size)
	Crypto_poly1305_final(&v4, mac)
}
